// <auto-generated>
//   Gerado por tools/gen-scaffold.ps1 a partir do pacote POC_Epat.
//   Fonte fixada por sha256 em artifacts/POC_Epat/manifest.json.
//   NAO EDITAR: uma nova extraccao reescreve este ficheiro.
// </auto-generated>
#nullable enable

namespace SefazSp.Epat.Domain.Abstractions;

/// <summary>
/// O prazo por expressao precisa de tempo, e tempo e dependencia.
/// Nunca DateTime.Now: sem relogio injectado nao ha teste de prazo reproduzivel,
/// e a etapa 4 do plano de cumprimento exige exactamente isso.
/// </summary>
public interface IClock
{
    DateTimeOffset Now { get; }
    TimeZoneInfo TimeZone { get; }
}
