// <auto-generated>
//   Gerado por tools/gen-scaffold.ps1 a partir do pacote POC_Epat.
//   Fonte fixada por sha256 em artifacts/POC_Epat/manifest.json.
//   NAO EDITAR: uma nova extraccao reescreve este ficheiro.
// </auto-generated>
#nullable enable

namespace SefazSp.Epat.Domain.Abstractions;

/// <summary>
/// Marca estado que o legado carrega mas que o cenario da POC nao exercita.
/// Nao altera comportamento: existe para que a fronteira do escopo seja visivel no codigo
/// e consultavel por ferramenta, em vez de viver so num relatorio.
/// O veredicto e o motivo vem de artifacts/&lt;pacote&gt;/scope.json.
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public sealed class OutOfPocScopeAttribute(string reason) : Attribute
{
    public string Reason { get; } = reason;
}
