// <auto-generated>
//   Gerado por tools/gen-scaffold.ps1 a partir do pacote POC_Epat.
//   Fonte fixada por sha256 em artifacts/POC_Epat/manifest.json.
//   NAO EDITAR: uma nova extraccao reescreve este ficheiro.
// </auto-generated>
#nullable enable

namespace SefazSp.Epat.Application.Abstractions;

/// <summary>
/// Identidade do caso atravessando uma fronteira. PROCESS_ID e a chave de correlacao
/// que o legado ja constroi nos scripts, no formato 'idAiim-<n>idProc-<n>' - nao precisa
/// de ser inventada, so transcrita.
/// </summary>
public readonly record struct AiimCaseRef(long IdAiim, string ProcessId);

/// <summary>Desfecho de uma chamada a subprocesso resolvida em runtime.</summary>
public readonly record struct ProcessCallResult(bool Started, string? ChildInstanceId, string? Failure);

/// <summary>
/// O envelope tecnico devolvido pelo BusinessWorks, declarado no EPAT.wsdl.
/// STATUS_CODE = '0' e sucesso, confirmado no glossario. Os valores daqui sao copiados
/// para o ProcessExecutionContext num passo explicito de mapeamento.
/// </summary>
public readonly record struct ServiceEnvelope(string? STATUS_CODE, string? STERRORCODE, string? STERRORDESC);
