#Workspace Lite Forms Catelog for package: 'Process Packages/POC_Epat.xpdl'.
#Tue Jun 09 15:23:14 BRT 2026
POCEPATP_VRFRETDE=POC_Epat/POC_EpatProcess/VerificarRetornoDecisions/VerificarRetornoDecisions.form.xslt
