<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>SefazSp.Epat.Domain</RootNamespace>
  </PropertyGroup>

  <!-- Domain nao referencia projecto nenhum, por desenho. -->

</Project>
