// <auto-generated>
//   Gerado por tools/gen-scaffold.ps1 a partir do pacote POC_Epat.
//   Fonte fixada por sha256 em artifacts/POC_Epat/manifest.json.
//   NAO EDITAR: uma nova extraccao reescreve este ficheiro.
// </auto-generated>
#nullable enable

using SefazSp.Epat.Application.Abstractions;

namespace SefazSp.Epat.Application.Abstractions.Services;

/// <summary>
/// As 5 operacoes que o processo realmente invoca, de 127 catalogadas.
/// Sao PORTAS: a implementacao SOAP e os dubles vivem na infraestrutura.
/// </summary>
public interface IEpatServices
{
    /// <summary>
    /// Operacao TIBCO: __sol_Business_sp_Processes_sol_Decision_sol_Sub_sp_Processes_sol_Intimacao_sol_PrepararIntimacao
    /// Declarada em DecisionsEPAT.wsdl.
    /// </summary>
    Task<ServiceEnvelope> PrepararintimacaoAsync(AiimCaseRef caseRef, CancellationToken ct);

    /// <summary>
    /// Operacao TIBCO: __sol_EPATInterfaceWrappers_sol_atualizarIntimacao.1
    /// Declarada em EPAT.wsdl.
    /// </summary>
    Task<ServiceEnvelope> AtualizarintimacaoAsync(AiimCaseRef caseRef, CancellationToken ct);

    /// <summary>
    /// Operacao TIBCO: __sol_EPATInterfaceWrappers_sol_buscarVistasAtivasPorAiim.1
    /// Declarada em EPAT.wsdl.
    /// </summary>
    Task<ServiceEnvelope> BuscarvistasativasporaiimAsync(AiimCaseRef caseRef, CancellationToken ct);

    /// <summary>
    /// Operacao TIBCO: __sol_EPATInterfaceWrappers_sol_criarNotificacoesAIIM.1
    /// Declarada em EPAT.wsdl.
    /// </summary>
    Task<ServiceEnvelope> CriarnotificacoesaiimAsync(AiimCaseRef caseRef, CancellationToken ct);

    /// <summary>
    /// Operacao TIBCO: __sol_EPATInterfaceWrappers_sol_obterPrimeiroDiaUtilAposPeriodoDeDiasCorridosDEAT.1
    /// Declarada em EPAT.wsdl.
    /// </summary>
    Task<ServiceEnvelope> ObterprimeirodiautilaposperiododediascorridosdeatAsync(AiimCaseRef caseRef, CancellationToken ct);

}
