// @ts-check
// Docs are generated by tools/gen-docs.ps1 - do not edit docs/ by hand.

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'ePAT - Sistema legado TIBCO',
  tagline: 'Documentacao gerada a partir dos artefatos de extracao',
  favicon: 'img/favicon.ico',

  url: 'http://localhost',
  baseUrl: '/',

  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',

  i18n: {
    defaultLocale: 'pt-BR',
    locales: ['pt-BR'],
  },

  markdown: {
    mermaid: true,
    format: 'detect',
  },
  themes: ['@docusaurus/theme-mermaid'],

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          path: 'docs',
          routeBasePath: '/',
          sidebarPath: './sidebars.js',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      navbar: {
        title: 'ePAT / TIBCO',
        items: [
          { type: 'docSidebar', sidebarId: 'main', position: 'left', label: 'Documentacao' },
          { to: '/migration-gaps', label: 'Lacunas de migracao', position: 'left' },
          { to: '/open-questions', label: 'Questoes em aberto', position: 'left' },
        ],
      },
      footer: {
        style: 'dark',
        copyright:
          'Conteudo gerado automaticamente a partir de artifacts/. Regenerar com tools/gen-docs.ps1.',
      },
      colorMode: {
        defaultMode: 'dark',
        respectPrefersColorScheme: true,
      },
    }),
};

export default config;
