// Sidebar is derived from the docs/ folder, which is generated. Adding a page to
// gen-docs.ps1 is enough - nothing here needs to change.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  main: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
