// <auto-generated>
//   Gerado por tools/gen-scaffold.ps1 a partir do pacote POC_Epat.
//   Fonte fixada por sha256 em artifacts/POC_Epat/manifest.json.
//   NAO EDITAR: uma nova extraccao reescreve este ficheiro.
// </auto-generated>
#nullable enable

namespace SefazSp.Epat.Application.Execution;

/// <summary>
/// Os 19 campos que NAO sao dominio: envelope de servico, contadores de
/// retentativa e decisao do operador. Ficaram aqui por decisao registada no glossario,
/// seccao unresolved. Nao sao persistidos como dados do caso.
/// </summary>
public sealed class ProcessExecutionContext
{
    /// <summary>
    /// DATETIME
    /// </summary>
    // Read-only for the process: supplied by the service envelope or engine. Reproduce as an input of the step, never as persisted case data.
    public string? DATETIME { get; set; }

    /// <summary>
    /// DUMP
    /// </summary>
    // Read-only for the process: supplied by the service envelope or engine. Reproduce as an input of the step, never as persisted case data.
    public string? DUMP { get; set; }

    /// <summary>
    /// Indicador de erro de aplicacao
    /// Marca que a chamada de servico falhou por regra de negocio, por oposicao a falha de infraestrutura. E esta distincao que decide se o caso volta ao laco de retry ou vai para tratamento manual: erro de negocio nao se resolve repetindo a chamada. Confirmado em 2026-08-06 que 'N' e ausencia de erro, e nao 'ainda nao avaliado'.
    /// Dominio: 'N' = sem erro de aplicacao; 'Y' = erro de aplicacao. Dominio fechado, confirmado em 2026-08-06.
    /// </summary>
    // Read-only for the process: supplied by the service envelope or engine. Reproduce as an input of the step, never as persisted case data.
    public string? ISAPPERROR { get; set; }

    /// <summary>
    /// Indicador de erro tecnico
    /// Marca que a chamada de servico falhou por infraestrutura - fila, rede, indisponibilidade - e nao por regra de negocio. E o par de ISAPPERROR: so o erro tecnico e retentavel automaticamente.
    /// Dominio: 'N' = sem erro tecnico; 'Y' = erro tecnico. Dominio fechado, confirmado em 2026-08-06.
    /// </summary>
    // Read-only for the process: supplied by the service envelope or engine. Reproduce as an input of the step, never as persisted case data.
    public string? ISTECHERROR { get; set; }

    /// <summary>
    /// Tecto de tentativas
    /// Numero maximo de tentativas do laco de retry das chamadas de servico. Parametro de resiliencia, sem significado de negocio. Comparado contra DOIS contadores independentes: NUMAPPRETRIES (falhas de aplicacao) e IPESystemValues.SW_QRETRYCOUNT (falhas de entrega da fila) - confirmado em 2026-08-06 que sao mesmo independentes e devem ser reproduzidos tal e qual.
    /// Dominio: 5 por omissao, escrito no SetParameters dos cinco subprocessos de servico como 'if (MAXRETRIES == null) MAXRETRIES = 5'. Confirmado em 2026-08-06.
    /// </summary>
    // Read-only for the process: supplied by the service envelope or engine. Reproduce as an input of the step, never as persisted case data.
    public int MAXRETRIES { get; set; }

    /// <summary>
    /// Contador de tentativas de aplicacao
    /// Conta as falhas de APLICACAO ja tentadas no laco de retry, distinto do contador tecnico do motor (SW_QRETRYCOUNT). Inicializado no passo Start Loop com 'if (NUMAPPRETRIES == null)' e comparado no passo More Retries contra MAXRETRIES.
    /// Dominio: Comeca em 0 e incrementa de 1 a cada tentativa. Confirmado em 2026-08-06.
    /// </summary>
    // Mutated by the process or by the user on the form. Needs a real home in the .NET execution state.
    public int NUMAPPRETRIES { get; set; }

    /// <summary>
    /// Decisao do operador na excepcao
    /// Decisao que uma pessoa toma quando o laco de retry se esgota e o caso cai em tratamento manual. Lido nos passos Try Again e Manually Fixed, que ficam depois do formulario MANEXC. Os dois literais NAO sao divergencia entre clones: sao passos diferentes do mesmo laco.
    /// Dominio: 'R' = repetir a chamada (passo Try Again); 'OK' = dar por resolvido manualmente (passo Manually Fixed). Dominio fechado, confirmado em 2026-08-06.
    /// </summary>
    // Mutated by the process or by the user on the form. Needs a real home in the .NET execution state.
    public string? OUTCOME { get; set; }

    /// <summary>
    /// participante
    /// </summary>
    // Mutated by the process or by the user on the form. Needs a real home in the .NET execution state.
    public string? PARTICIPANTE { get; set; }

    /// <summary>
    /// PROCESS_ID
    /// </summary>
    // Read-only for the process: supplied by the service envelope or engine. Reproduce as an input of the step, never as persisted case data.
    public string? PROCESS_ID { get; set; }

    /// <summary>
    /// SERVICE_NAME
    /// </summary>
    // Read-only for the process: supplied by the service envelope or engine. Reproduce as an input of the step, never as persisted case data.
    public string? SERVICE_NAME { get; set; }

    /// <summary>
    /// Codigo de retorno do servico
    /// Codigo devolvido pelo envelope tecnico do BusinessWorks a cada chamada de servico. Decide o desvio para o ramo AppError em cinco subprocessos.
    /// Dominio: '0' = sucesso. Confirmado em 2026-08-06. ATENCAO: o PRPINTPC compara com SW_NA em vez de '0' - ja tratado como defeito em rulings.CLONE-PRPINTPC, com decisao de corrigir.
    /// </summary>
    // Read-only for the process: supplied by the service envelope or engine. Reproduce as an input of the step, never as persisted case data.
    public string? STATUS_CODE { get; set; }

    /// <summary>
    /// STErrorCode
    /// </summary>
    // Read-only for the process: supplied by the service envelope or engine. Reproduce as an input of the step, never as persisted case data.
    public string? STERRORCODE { get; set; }

    /// <summary>
    /// STErrorDesc
    /// </summary>
    // Read-only for the process: supplied by the service envelope or engine. Reproduce as an input of the step, never as persisted case data.
    public string? STERRORDESC { get; set; }

    /// <summary>
    /// SW_CASENUM
    /// </summary>
    // iProcess engine variable, supplied by the runtime. In .NET it must come from the workflow execution context, not from the case data.
    public int SW_CASENUM { get; set; }

    /// <summary>
    /// SW_HOSTNAME
    /// </summary>
    // iProcess engine variable, supplied by the runtime. In .NET it must come from the workflow execution context, not from the case data.
    public string? SW_HOSTNAME { get; set; }

    /// <summary>
    /// SW_MAINCASE
    /// </summary>
    // iProcess engine variable, supplied by the runtime. In .NET it must come from the workflow execution context, not from the case data.
    public int SW_MAINCASE { get; set; }

    /// <summary>
    /// SW_MAINPROC
    /// </summary>
    // iProcess engine variable, supplied by the runtime. In .NET it must come from the workflow execution context, not from the case data.
    public string? SW_MAINPROC { get; set; }

    /// <summary>
    /// SW_PARENTCASE
    /// </summary>
    // iProcess engine variable, supplied by the runtime. In .NET it must come from the workflow execution context, not from the case data.
    public int SW_PARENTCASE { get; set; }

    /// <summary>
    /// SW_PARENTPROC
    /// </summary>
    // iProcess engine variable, supplied by the runtime. In .NET it must come from the workflow execution context, not from the case data.
    public string? SW_PARENTPROC { get; set; }

}
