// <auto-generated>
//   Gerado por tools/gen-scaffold.ps1 a partir do pacote POC_Epat.
//   Fonte fixada por sha256 em artifacts/POC_Epat/manifest.json.
//   NAO EDITAR: uma nova extraccao reescreve este ficheiro.
// </auto-generated>
#nullable enable

namespace SefazSp.Epat.Infrastructure.Legacy;

/// <summary>
/// CAMADA ANTICORRUPCAO. Unico sitio do codigo onde a palavra iProcess aparece.
///
/// BLOQUEADO: rulings.BUILTIN-SEMANTICS decidiu consultar a documentacao TIBCO antes de
/// implementar. SUBSTR e SEARCH sao base 1 ou base 0? O terceiro argumento de SUBSTR e
/// comprimento ou posicao final? Um desvio de uma posicao nao falha - devolve valor errado.
/// O vector de comportamento de builtin-contract.json e o oraculo que qualquer implementacao
/// candidata tem de satisfazer.
/// </summary>
public interface IProcessBuiltins
{
    // IPEConversionUtil.DATESTR - 6 chamada(s), aridade observada 1
    // IPEConversionUtil.NUM - 1 chamada(s), aridade observada 1
    // IPEConversionUtil.STR - 16 chamada(s), aridade observada 2
    // IPEDateTimeUtil.CALCTIME - 3 chamada(s), aridade observada 4
    // IPEStringUtil.SEARCH - 1 chamada(s), aridade observada 2
    // IPEStringUtil.STRLEN - 1 chamada(s), aridade observada 1
    // IPEStringUtil.SUBSTR - 2 chamada(s), aridade observada 3
}
