// <auto-generated-harness>
//   Arnes gerado para VALID-GRAFTSTEP-conceito (SSTN-77).
//   Fixture: artifacts/POC_Epat/scenarios/index.json  — IMUTAVEL.
//   O agente NUNCA escreve nem edita valores esperados.
//   Invariantes: graft-step, criacao-dinamica, compatibilidade-iprocess.
// </auto-generated-harness>
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Nodes;
using Xunit;

namespace SefazSp.Epat.Oracles.Tests;

/// <summary>
/// Helpers para localizar o diretório raiz do repositório a partir da localização
/// do assembly em execução (bin/Debug/net8.0/…).
/// </summary>
internal static class RepoRoot
{
    private static readonly string _root = FindRoot();

    private static string FindRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir != null)
        {
            if (File.Exists(Path.Combine(dir.FullName, "artifacts", "POC_Epat", "scenarios", "index.json")))
                return dir.FullName;
            dir = dir.Parent;
        }
        throw new InvalidOperationException(
            "Não foi possível localizar a raiz do repositório a partir de: " + AppContext.BaseDirectory);
    }

    public static string ArtifactsPath(params string[] parts) =>
        Path.Combine(new[] { _root, "artifacts" }.Concat(parts).ToArray());
}
