// <auto-generated>
//   Gerado por tools/gen-scaffold.ps1 a partir do pacote POC_Epat.
//   Fonte fixada por sha256 em artifacts/POC_Epat/manifest.json.
//   NAO EDITAR: uma nova extraccao reescreve este ficheiro.
// </auto-generated>
#nullable enable

namespace SefazSp.Epat.Domain.Enums;

/// <summary>
/// Dominio fechado observado no pacote para TIPOVISTAS.
/// </summary>
public enum TIPOVISTAS
{
    /// <summary>Literal no XPDL: 'JUIZ'</summary>
    JUIZ,
    /// <summary>Literal no XPDL: 'MISTA'</summary>
    MISTA,
}
