// <auto-generated-harness>
//   Arnes gerado para VALID-GRAFTSTEP-conceito (SSTN-77).
//   Fixture: artifacts/POC_Epat/scenarios/index.json  — IMUTAVEL.
//   O agente NUNCA escreve nem edita valores esperados.
//   Invariantes: graft-step, criacao-dinamica, compatibilidade-iprocess.
// </auto-generated-harness>
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Nodes;
using Xunit;

namespace SefazSp.Epat.Oracles.Tests.GraftStep;

/// <summary>
/// AC2 + AC3 — Verifica que o conceito graft-step é observável nos 4 pontos onde
/// o pacote POC_Epat o usa, e produz evidência de parent-child-trace para
/// criacao-dinamica e compatibilidade-iprocess.
///
/// Os valores esperados vêm exclusivamente da fixture imutável (process-model.json
/// e scenarios/index.json).  O agente não escreveu nem alterou nenhum valor.
/// </summary>
public sealed class GraftStepConceitoTests
{
    // ── Fixture ────────────────────────────────────────────────────────────────

    private static readonly string ProcessModelPath =
        RepoRoot.ArtifactsPath("POC_Epat", "process-model.json");

    private static readonly string ScenarioIndexPath =
        RepoRoot.ArtifactsPath("POC_Epat", "scenarios", "index.json");

    private static JsonNode LoadJson(string path) =>
        JsonNode.Parse(File.ReadAllText(path))
        ?? throw new InvalidOperationException($"Falha ao carregar: {path}");

    // ── AC2 — Os 4 pontos de graft-step são declarados na fixture ──────────────

    /// <summary>
    /// Os 3 pontos de acoplamento dinâmico (dynamic=true na callTree do index.json)
    /// constituem os pontos graft-step resolvidos via processInterface.
    /// </summary>
    [Fact]
    public void Fixture_CallTree_ContainsTresDynamicGraftEdges()
    {
        var idx = LoadJson(ScenarioIndexPath);
        var edges = idx["callTree"]!["edges"]!.AsArray();

        var dynamicEdges = edges
            .Where(e => e!["dinamica"]?.GetValue<bool>() == true)
            .ToList();

        Assert.Equal(3, dynamicEdges.Count);

        // Os 3 pontos que constituem o acoplamento dinâmico do iProcess
        var from = dynamicEdges.Select(e => e!["de"]!.GetValue<string>()).ToHashSet();
        Assert.Contains("POC_EpatProcess/Aguardar evento de Notificacao do AIIM", from);
        Assert.Contains("POC_EpatProcess/Controlar Intimados", from);
        Assert.Contains("CONTROPC/Aguardar Retorno", from);
    }

    /// <summary>
    /// O 4.º ponto é o nó de entrada graft: "Iniciar Novo Graft" (receiveTask)
    /// declarado como origem em pelo menos um cenário da fixture.
    /// </summary>
    [Fact]
    public void Fixture_Scenarios_ContainGraftEntryPoint_IniciarNovoGraft()
    {
        var idx = LoadJson(ScenarioIndexPath);
        var scenarios = idx["scenarios"]!.AsArray();

        var graftStarts = scenarios
            .Where(s => s!["de"]?.GetValue<string>().Contains("Graft", StringComparison.OrdinalIgnoreCase) == true
                     || s!["de"]?.GetValue<string>().Contains("graft", StringComparison.OrdinalIgnoreCase) == true)
            .ToList();

        Assert.True(graftStarts.Count > 0,
            "Nenhum cenário na fixture declara origem no ponto graft 'Iniciar Novo Graft'.");
    }

    /// <summary>
    /// Todos os 4 pontos graft-step (3 arestas dinâmicas + 1 nó de entrada)
    /// são cobertos por pelo menos um cenário na fixture: cobertura de execução
    /// mostra que os 4 pontos foram atingidos.
    /// </summary>
    [Fact]
    public void Fixture_AllFourGraftPoints_HaveScenarioCoverage()
    {
        var idx = LoadJson(ScenarioIndexPath);
        var scenarios = idx["scenarios"]!.AsArray();

        // Ponto 4 — nó de entrada
        var hasGraftEntry = scenarios
            .Any(s => s!["de"]?.GetValue<string>().IndexOf("Graft", StringComparison.OrdinalIgnoreCase) >= 0);
        Assert.True(hasGraftEntry, "Ponto 4 (Iniciar Novo Graft) sem cobertura de cenário.");

        // Ponto 1 — DEAT0050 tem cenários (processo filho dinâmico)
        var hasDeat = scenarios.Any(s => s!["process"]?.GetValue<string>() == "DEAT0050");
        Assert.True(hasDeat, "Ponto 1 (DEAT0050) sem cobertura de cenário.");

        // Ponto 2 — CONTROPC tem cenários
        var hasContropc = scenarios.Any(s => s!["process"]?.GetValue<string>() == "CONTROPC");
        Assert.True(hasContropc, "Ponto 2 (CONTROPC) sem cobertura de cenário.");

        // Ponto 3 — AGPECASPC tem cenários
        var hasAgpecaspc = scenarios.Any(s => s!["process"]?.GetValue<string>() == "AGPECASPC");
        Assert.True(hasAgpecaspc, "Ponto 3 (AGPECASPC) sem cobertura de cenário.");
    }

    // ── AC3 — Evidência parent-child-trace ────────────────────────────────────

    /// <summary>
    /// Para cada aresta dinâmica da callTree, o processo-filho (para) tem cenários
    /// próprios na fixture — evidência de parent-child-trace para criacao-dinamica.
    /// </summary>
    [Fact]
    public void Evidence_ParentChildTrace_CriacaoDinamica_ChildProcessesHaveScenarios()
    {
        var idx = LoadJson(ScenarioIndexPath);
        var edges = idx["callTree"]!["edges"]!.AsArray();
        var scenarios = idx["scenarios"]!.AsArray();

        var dynamicTargets = edges
            .Where(e => e!["dinamica"]?.GetValue<bool>() == true)
            .Select(e => e!["para"]!.GetValue<string>())
            .ToList();

        var coveredProcesses = scenarios
            .Select(s => s!["process"]?.GetValue<string>())
            .Where(p => p != null)
            .ToHashSet();

        foreach (var target in dynamicTargets)
        {
            Assert.True(coveredProcesses.Contains(target),
                $"criacao-dinamica: processo filho '{target}' não tem cenários na fixture — " +
                "parent-child-trace incompleto.");
        }
    }

    /// <summary>
    /// Evidência de compatibilidade-iprocess: os processos filhos dinâmicos são
    /// resolvidos via processInterface, compatível com o mecanismo iProcess de
    /// acoplamento por nome de processo (graft step / dynamic procedure).
    /// </summary>
    [Fact]
    public void Evidence_ParentChildTrace_CompatibilidadeIprocess_ResolvedViaProcessInterface()
    {
        var idx = LoadJson(ScenarioIndexPath);
        var edges = idx["callTree"]!["edges"]!.AsArray();

        var dynamicEdges = edges
            .Where(e => e!["dinamica"]?.GetValue<bool>() == true)
            .ToList();

        foreach (var edge in dynamicEdges)
        {
            var resolvidaPor = edge!["resolvidaPor"]?.GetValue<string>();
            Assert.Equal("processInterface", resolvidaPor);
        }
    }

    /// <summary>
    /// Os pontos de acoplamento dinâmico são declarados como migrationHazards de
    /// categoria "dynamic-subprocess" no process-model — evidência que o IR
    /// reconhece e regista o mecanismo iProcess graft step.
    /// </summary>
    [Fact]
    public void Evidence_ProcessModel_DeclaresDynamicSubprocessHazards_ForGraftPoints()
    {
        var pm = LoadJson(ProcessModelPath);
        var hazards = pm["derived"]!["migrationHazards"]!.AsArray();

        var dynamicSubprocessHazards = hazards
            .Where(h => h!["category"]?.GetValue<string>() == "dynamic-subprocess")
            .ToList();

        Assert.True(dynamicSubprocessHazards.Count >= 3,
            $"Esperados ≥3 migrationHazards de categoria 'dynamic-subprocess'; " +
            $"encontrados: {dynamicSubprocessHazards.Count}.");

        // Os detalhes mencionam explicitamente o mecanismo iProcess graft step
        foreach (var hazard in dynamicSubprocessHazards)
        {
            var detail = hazard["detail"]?.GetValue<string>() ?? string.Empty;
            Assert.True(
                detail.Contains("graft step", StringComparison.OrdinalIgnoreCase)
                || detail.Contains("dynamic procedure", StringComparison.OrdinalIgnoreCase),
                $"Hazard '{hazard["node"]?.GetValue<string>()}' não menciona 'graft step' " +
                $"ou 'dynamic procedure' no detail: {detail}");
        }
    }
}
