// <auto-generated>
//   Gerado por tools/gen-scaffold.ps1 a partir do pacote POC_Epat.
//   Fonte fixada por sha256 em artifacts/POC_Epat/manifest.json.
//   NAO EDITAR: uma nova extraccao reescreve este ficheiro.
// </auto-generated>
#nullable enable

namespace SefazSp.Epat.Domain.ValueObjects;

/// <summary>
/// O sentinela SW_NA do iProcess e um TERCEIRO estado: nao e nulo e nao e vazio.
/// 18 campos do pacote comparam-se com ele.
/// Colapsar SW_NA em null troca o ramo que dispara, sem erro de compilacao e sem teste vermelho.
/// Decidido em config/glossary: gaps.iprocess-builtin = shim-tri-state.
/// </summary>
public readonly record struct FieldValue<T>
{
    private readonly T? _value;
    private readonly FieldState _state;

    private FieldValue(T? value, FieldState state) { _value = value; _state = state; }

    public static FieldValue<T> Of(T value) => new(value, FieldState.HasValue);

    /// <summary>SW_NA: o motor diz explicitamente que o valor nao esta disponivel.</summary>
    public static FieldValue<T> NotAvailable => new(default, FieldState.IsNotAvailable);

    /// <summary>Declarado mas nunca preenchido. Distinto de SW_NA.</summary>
    public static FieldValue<T> Empty => new(default, FieldState.Empty);

    public bool HasValue      => _state == FieldState.HasValue;
    public bool IsNotAvailable => _state == FieldState.IsNotAvailable;
    public bool IsEmpty       => _state == FieldState.Empty;

    /// <summary>
    /// Forca o chamador a decidir os tres casos. O switch exaustivo do C# e
    /// o que impede que um ramo desapareca em silencio.
    /// </summary>
    public TResult Match<TResult>(
        Func<T, TResult> hasValue,
        Func<TResult> notAvailable,
        Func<TResult> empty) => _state switch
        {
            FieldState.HasValue      => hasValue(_value!),
            FieldState.IsNotAvailable => notAvailable(),
            _                         => empty()
        };
}

public enum FieldState { Empty = 0, HasValue = 1, IsNotAvailable = 2 }
