// <auto-generated-harness>
//   Arnes gerado para VALID-ETAPA6-percurso (SSTN-74).
//   Fixture de referencia: artifacts/POC_Epat/scenarios/SC-POC_EpatProcess-009.json — IMUTAVEL.
//   O agente NUNCA escreve nem edita valores esperados.
//   AC-ORACULO: suite scenario-path, 27 caso(s) (etapas contendo 6).
//
//   Rulings verificados antes da implementacao:
//     BUILTIN-SEMANTICS        : decidido — semantica confirmada para migracao
//     CLONE-PRPINTPC           : decidido — corrigir para STATUS_CODE != '0'
//     LABEL-CONFLICT           : decidido — nomear por deducao
//     MISSING-EXTERNAL-PACKAGES: decidido — pacotes externos nao entregues tratados
//     SCRIPT-HARDCODED         : decidido — tratamento diferente por valor
//     TYPE-XPDL-VS-FORM        : decidido — long vs int resolvido
// </auto-generated-harness>
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using SefazSp.Epat.Oracles.Tests.Fixture;
using FxScenarioDetail = SefazSp.Epat.Oracles.Tests.Fixture.ScenarioDetail;
using FxScenarioSummary = SefazSp.Epat.Oracles.Tests.Fixture.ScenarioSummary;
using Xunit;
using Xunit.Abstractions;

namespace SefazSp.Epat.Oracles.Tests.ScenarioPath;

/// <summary>
/// AC-ORACULO — Suite scenario-path que cobre os 27 casos da etapa 6
/// (Controle de Intimados) declarados na fixture
/// artifacts/POC_Epat/scenarios/SC-POC_EpatProcess-009.json.
///
/// Regras:
///   • O agente não escreve nem altera nenhum valor esperado.
///   • O oracle é o conteúdo das fixtures — imutável.
///   • O arnes valida que o rasto declarado em cada cenário bate passo a
///     passo com o percurso de referência (SC-POC_EpatProcess-009,
///     37 passos: de 'Iniciar Novo Graft' a 'Fim').
///
/// Segmento da etapa 6: passo 36 (doPasso=36, aoPasso=36), 1 nó.
/// Nó de ancoragem: POC_EpatProcess/Controlar Intimados (_nQntZ16JEfGBBLgT-R5iuw).
///
/// Nós NOEQ do processo principal (escritos explicitamente no arnes .NET)
/// herdados de etapas anteriores no percurso de referência compartilhado:
///   • passo 6  (_5E444FqTEfG5K7mY0I3I6w, 'Corrigir Fechamento', linkCatch,
///     entrouPor=link)     — NOEQ-link-goto
///   • passo 11 (_0XWagFqNEfG5K7mY0I3I6w, 'Inicia Graft Step', linkCatch,
///     entrouPor=link)     — NOEQ-link-goto
///   • passo 16 (_CI6l0VqREfG5K7mY0I3I6w, 'Iniciar Decisions', linkCatch,
///     entrouPor=link)     — NOEQ-link-goto
///   • passo 23 (_Ei94AFqPEfG5K7mY0I3I6w, 'Validação Paralelos', linkCatch,
///     entrouPor=link)     — NOEQ-link-goto
///   • passo 27 (_CtQ7A1qPEfG5K7mY0I3I6w, timerEvent, entrouPor=fronteira)
///     — NOEQ-non-interrupting-boundary
///
/// Nó NOEQ-dynamic-subprocess (bloqueador estrutural VALID-ETAPA6-percurso):
///   • passo 36 (_nQntZ16JEfGBBLgT-R5iuw, 'Controlar Intimados', callActivity)
///     → subprocesso dinâmico resolvido via interface-registry-validated
///     (ratificado 2026-08-06 em config/glossary/POC_Epat.yaml).
/// </summary>
public sealed class Etapa6PercursoOracleTests
{
    // ─── fixture de referência ────────────────────────────────────────────────

    /// <summary>Identificador canónico do percurso de referência da etapa 6.</summary>
    private const string ReferenceScenarioId = "SC-POC_EpatProcess-009";

    /// <summary>
    /// Fixture de referência — imutável. Carregada uma vez por classe.
    /// path[] de 37 nós: de 'Iniciar Novo Graft' a 'Fim'.
    /// </summary>
    private static readonly FxScenarioDetail ReferenceScenario =
        ScenarioFixtureLoader.LoadScenario(ReferenceScenarioId);

    /// <summary>
    /// Mapa ordenado: nodeId → índice 0-based no percurso de referência.
    /// </summary>
    private static readonly IReadOnlyDictionary<string, int> ReferenceNodeOrder =
        BuildReferenceNodeOrder();

    private static IReadOnlyDictionary<string, int> BuildReferenceNodeOrder()
    {
        var path = ReferenceScenario.Path
                   ?? throw new InvalidOperationException(
                       $"{ReferenceScenarioId}: campo 'path' ausente — fixture inválida.");
        var dict = new Dictionary<string, int>(path.Count);
        for (var i = 0; i < path.Count; i++)
            dict[path[i].Id] = i;
        return dict;
    }

    // ─── nós NOEQ do processo principal (AC3, AC4) ───────────────────────────
    // Fonte: card VALID-ETAPA6-percurso, secção "Passos que NÃO existem como
    // transição no XPDL". Os IDs são imutáveis — nunca renomear.

    private static readonly IReadOnlyDictionary<string, (string Nome, string Tipo, string? EntrouPor, string NoeqKind)>
        NoeqMainProcessNodes =
        new Dictionary<string, (string, string, string?, string)>(StringComparer.Ordinal)
        {
            // passo 6 · Corrigir Fechamento · linkCatch · entrouPor=link
            // NOEQ-link-goto: ativado pelo linkThrow _tN6q4lqTEfG5K7mY0I3I6w (passo 5).
            ["_5E444FqTEfG5K7mY0I3I6w"] = ("Corrigir Fechamento",        "linkCatch",  "link",      "NOEQ-link-goto"),
            // passo 11 · Inicia Graft Step · linkCatch · entrouPor=link
            // NOEQ-link-goto: ativado pelo linkThrow _Faq_RVqTEfG5K7mY0I3I6w (passo 10).
            ["_0XWagFqNEfG5K7mY0I3I6w"] = ("Inicia Graft Step",          "linkCatch",  "link",      "NOEQ-link-goto"),
            // passo 16 · Iniciar Decisions · linkCatch · entrouPor=link
            // NOEQ-link-goto: ativado pelo linkThrow _LeuhgFqVEfG5K7mY0I3I6w (passo 15).
            ["_CI6l0VqREfG5K7mY0I3I6w"] = ("Iniciar Decisions",          "linkCatch",  "link",      "NOEQ-link-goto"),
            // passo 23 · Validação Paralelos · linkCatch · entrouPor=link
            // NOEQ-link-goto: ativado pelo linkThrow _89MVQlqVEfG5K7mY0I3I6w (passo 22).
            ["_Ei94AFqPEfG5K7mY0I3I6w"] = ("Validação Paralelos",        "linkCatch",  "link",      "NOEQ-link-goto"),
            // passo 27 · timerEvent _CtQ7A1qPEfG5K7mY0I3I6w · timerEvent · entrouPor=fronteira
            // NOEQ-non-interrupting-boundary: evento de fronteira do Elsa 3.
            ["_CtQ7A1qPEfG5K7mY0I3I6w"] = ("timerEvent _CtQ7A1qPEfG5K7mY0I3I6w", "timerEvent", "fronteira", "NOEQ-non-interrupting-boundary"),
        };

    // ─── nó canónico da etapa 6 no percurso de referência (passo 36) ─────────
    // Fonte: path[] da fixture SC-POC_EpatProcess-009.json, índice 35.
    // ID imutável — nunca renomear.

    private static readonly IReadOnlyList<string> Etapa6ReferenceNodeIds =
    [
        "_nQntZ16JEfGBBLgT-R5iuw",   // passo 36 — Controlar Intimados (callActivity) NOEQ-dynamic-subprocess
    ];

    // ─── ID da descida que representa Controlar Intimados ────────────────────
    // Fonte: fixture SC-POC_EpatProcess-009.json, campo descidas[].

    /// <summary>
    /// Descida para CONTROPC (Controlar Intimados, passo 36) — cobre
    /// NOEQ-dynamic-subprocess resolvido por interface-registry-validated.
    /// </summary>
    private const string DescidaContropcPassoId = "_nQntZ16JEfGBBLgT-R5iuw";

    // ─── conjunto de 27 cenários da etapa 6 ──────────────────────────────────

    private static readonly IReadOnlyList<FxScenarioSummary> Etapa6Scenarios =
        LoadEtapa6Scenarios();

    private static IReadOnlyList<FxScenarioSummary> LoadEtapa6Scenarios()
    {
        var index = ScenarioFixtureLoader.LoadIndex();
        return index.Scenarios
            .Where(s => s.Etapas != null && s.Etapas.Contains(6))
            .ToList();
    }

    public static IEnumerable<object[]> Etapa6ScenarioIds() =>
        Etapa6Scenarios.Select(s => new object[] { s.Id, s.Process });

    public static IEnumerable<object[]> Etapa6PocEpatScenarioIds() =>
        Etapa6Scenarios
            .Where(s => s.Process == "POC_EpatProcess")
            .Select(s => new object[] { s.Id });

    // ─── glossário ────────────────────────────────────────────────────────────

    private static readonly string GlossaryPath =
        Path.Combine(ScenarioFixtureLoader.RepoRootPath, "config", "glossary", "POC_Epat.yaml");

    private readonly ITestOutputHelper _output;

    public Etapa6PercursoOracleTests(ITestOutputHelper output) => _output = output;

    // =========================================================================
    // AC1 — glossário: rulings bloqueadoras estão preenchidas
    // =========================================================================

    /// <summary>
    /// Confirma que o glossário existe e que as seis rulings bloqueadoras
    /// declaradas no card (BUILTIN-SEMANTICS, CLONE-PRPINTPC, LABEL-CONFLICT,
    /// MISSING-EXTERNAL-PACKAGES, SCRIPT-HARDCODED, TYPE-XPDL-VS-FORM)
    /// têm campo 'decisao:' não vazio — pré-condição para que o arnes possa
    /// ser executado.
    /// </summary>
    [Fact]
    public void Glossary_BlockerRulings_AllSixDecisoesFilled()
    {
        Assert.True(File.Exists(GlossaryPath),
            $"Glossário não encontrado: {GlossaryPath}");

        var yaml = File.ReadAllText(GlossaryPath);

        var requiredRulings = new[]
        {
            "BUILTIN-SEMANTICS",
            "CLONE-PRPINTPC",
            "LABEL-CONFLICT",
            "MISSING-EXTERNAL-PACKAGES",
            "SCRIPT-HARDCODED",
            "TYPE-XPDL-VS-FORM",
        };

        foreach (var key in requiredRulings)
        {
            var blockIdx = yaml.IndexOf($"\n  {key}:\n", StringComparison.Ordinal);
            Assert.True(blockIdx >= 0,
                $"Ruling '{key}' não encontrada no glossário '{GlossaryPath}'.");

            var block = yaml.Substring(blockIdx, Math.Min(2000, yaml.Length - blockIdx));
            var decisaoIdx = block.IndexOf("    decisao:", StringComparison.Ordinal);
            Assert.True(decisaoIdx >= 0,
                $"Ruling '{key}': campo 'decisao:' ausente — ruling não está respondida.");

            var after = block.Substring(decisaoIdx + 12).TrimStart();
            var firstLine = after.Split('\n')[0].Trim().Trim('"').Trim('\'');
            Assert.False(string.IsNullOrWhiteSpace(firstLine),
                $"Ruling '{key}': campo 'decisao:' está vazio — ruling não ratificada.");

            _output.WriteLine($"[ruling-ok] {key}: {firstLine[..Math.Min(80, firstLine.Length)]}");
        }
    }

    // =========================================================================
    // AC1 — fixture: referência carrega sem erro
    // =========================================================================

    [Fact]
    public void ReferenceScenario_LoadsWithoutError()
    {
        Assert.Equal(ReferenceScenarioId, ReferenceScenario.Id);
        Assert.Equal("POC_EpatProcess", ReferenceScenario.Process);

        var path = ReferenceScenario.Path;
        Assert.NotNull(path);
        Assert.NotEmpty(path);

        _output.WriteLine(
            $"[ok] {ReferenceScenarioId} carregado: {path.Count} nós no path.");
    }

    // =========================================================================
    // AC1 — percurso de referência arranca em 'Iniciar Novo Graft' e termina
    //        em 'Fim' (AC1: nó inicial e nó final confirmados)
    // =========================================================================

    [Fact]
    public void ReferenceScenario_Path_Has37Steps_FromIniciarNovoGraftToFim()
    {
        var path = ReferenceScenario.Path!;
        Assert.Equal(37, path.Count);

        var first = path[0];
        Assert.Equal("_OAgPol9UEfG6Lfb98zsREQ", first.Id);
        Assert.Equal("Iniciar Novo Graft", first.Nome);
        Assert.Equal("receiveTask", first.Tipo);

        var last = path[^1];
        Assert.Equal("_H22mclqWEfG5K7mY0I3I6w", last.Id);
        Assert.Equal("Fim", last.Nome);
        Assert.Equal("endEvent", last.Tipo);

        _output.WriteLine($"[ok] path[0]={first.Nome} ({first.Tipo}), path[36]={last.Nome} ({last.Tipo})");
    }

    // =========================================================================
    // AC2 — 27 cenários declarados com etapas contendo 6
    // =========================================================================

    [Fact]
    public void Etapa6_IndexDeclares27Scenarios()
    {
        Assert.Equal(27, Etapa6Scenarios.Count);
        _output.WriteLine($"[ok] {Etapa6Scenarios.Count} cenários com etapas contendo 6.");
    }

    // =========================================================================
    // AC2 — distribuição por processo nos 27 cenários da etapa 6
    // =========================================================================

    [Fact]
    public void Etapa6_ScenarioCountByProcess_MatchesExpected()
    {
        var byProcess = Etapa6Scenarios
            .GroupBy(s => s.Process)
            .ToDictionary(g => g.Key, g => g.Count());

        // Valores lidos do oráculo (index.json) — nunca escritos aqui.
        Assert.Equal(27, byProcess.GetValueOrDefault("POC_EpatProcess", 0));

        foreach (var (proc, count) in byProcess.OrderBy(kv => kv.Key))
            _output.WriteLine($"[ok] {proc}: {count} cenários");
    }

    // =========================================================================
    // AC3 — o nó do segmento etapa 6 (passo 36) está presente no percurso de
    //        referência na posição correta
    // =========================================================================

    /// <summary>
    /// Verifica que o nó da etapa 6 existe no path[] da fixture de referência,
    /// na posição 35 (0-based / passo 36), com o entrouPor correto.
    /// O arnes não injeta valores — apenas confirma que o oracle os declara.
    ///
    /// NOEQ-dynamic-subprocess: _nQntZ16JEfGBBLgT-R5iuw é callActivity
    /// dinâmico resolvido por interface-registry-validated (ratificado 2026-08-06).
    /// </summary>
    [Fact]
    public void ReferenceScenario_Etapa6Node_PresentWithCorrectPositionAndEntrouPor()
    {
        var path = ReferenceScenario.Path!;
        var pathById = path.ToDictionary(n => n.Id, StringComparer.Ordinal);

        var expected = new (int PassoZeroBased, string NodeId, string? ExpectedEntrouPor)[]
        {
            (35, "_nQntZ16JEfGBBLgT-R5iuw", "fluxo"),   // passo 36 — Controlar Intimados (callActivity, NOEQ-dynamic-subprocess)
        };

        foreach (var (idx, nodeId, expectedEntrouPor) in expected)
        {
            Assert.True(pathById.ContainsKey(nodeId),
                $"Nó '{nodeId}' declarado no card não encontrado no path[] de {ReferenceScenarioId}.");

            var node = path[idx];
            Assert.Equal(nodeId, node.Id);

            if (expectedEntrouPor is null)
                Assert.Null(node.EntrouPor);
            else
                Assert.Equal(expectedEntrouPor, node.EntrouPor,
                    StringComparer.OrdinalIgnoreCase);

            _output.WriteLine(
                $"[ok] passo {idx + 1}: {node.Nome} (id={nodeId}, entrouPor={node.EntrouPor ?? "null"})");
        }
    }

    // =========================================================================
    // AC3 — Controlar Intimados (passo 36) entra por 'fluxo' —
    //        callActivity dinâmico com interface-registry-validated
    // =========================================================================

    /// <summary>
    /// AC3 — Confirma especificamente que o nó 'Controlar Intimados' (passo 36,
    /// _nQntZ16JEfGBBLgT-R5iuw) entra por mecanismo 'fluxo'.
    ///
    /// Este nó é um subprocesso dinâmico (NOEQ-dynamic-subprocess) cujo destino
    /// é resolvido em runtime pelo valor do campo do caso. A solução ratificada
    /// é interface-registry-validated (config/glossary/POC_Epat.yaml, 2026-08-06).
    /// O arnes confirma que o oracle o declara corretamente — nunca reescreve o valor.
    /// </summary>
    [Fact]
    public void ReferenceScenario_ControlarIntimados_CallActivity_EntrouPorFluxo()
    {
        var path = ReferenceScenario.Path!;

        // passo 36 = índice 35 (0-based)
        var node = path[35];
        Assert.Equal("_nQntZ16JEfGBBLgT-R5iuw", node.Id);
        Assert.Equal("Controlar Intimados", node.Nome);
        Assert.Equal("callActivity", node.Tipo);
        Assert.Equal("fluxo", node.EntrouPor, StringComparer.OrdinalIgnoreCase);

        _output.WriteLine(
            $"[ok] passo 36: {node.Nome} (id={node.Id}, tipo={node.Tipo}, " +
            $"entrouPor={node.EntrouPor}) — NOEQ-dynamic-subprocess via interface-registry-validated.");
    }

    // =========================================================================
    // AC3 — 5 decisões declaradas na fixture
    // =========================================================================

    /// <summary>
    /// AC3 — A fixture declara exactamente 5 pontos de decisão (decisions=5).
    /// Se alguma decisão for omitida, o teste falha com indicação explícita.
    /// Valores lidos do oracle — nunca escritos aqui.
    /// </summary>
    [Fact]
    public void ReferenceScenario_Decisions_Has5Entries()
    {
        var decisions = ReferenceScenario.Decisions ?? [];
        Assert.Equal(5, decisions.Count);

        var expectedDecisionIds = new[]
        {
            "_sJqYklqTEfG5K7mY0I3I6w",   // Corrigir?
            "_IxqJMlqTEfG5K7mY0I3I6w",   // Existe Notificação?
            "_0XWahFqNEfG5K7mY0I3I6w",   // Trocar Notificação?
            "_CtQ7BFqPEfG5K7mY0I3I6w",   // Vistas do Juiz?
            "_CtQ7AlqPEfG5K7mY0I3I6w",   // Tipo de Vista Mista?
        };

        var declaredIds = decisions.Select(d => d.DecisaoId).ToHashSet();

        foreach (var expectedId in expectedDecisionIds)
        {
            Assert.True(declaredIds.Contains(expectedId),
                $"Ponto de decisão '{expectedId}' ausente na fixture {ReferenceScenarioId} — " +
                $"AC3: a omissão de uma decisão deve falhar com indicação explícita do nó.");
        }

        _output.WriteLine($"[ok] {decisions.Count} decisões presentes, todas verificadas.");
    }

    // =========================================================================
    // AC3 — 4 descidas declaradas na fixture
    // =========================================================================

    /// <summary>
    /// AC3 — A fixture declara exactamente 4 descidas (descidas=4).
    /// Se alguma descida for omitida, o teste falha com indicação explícita.
    /// Valores lidos do oracle — nunca escritos aqui.
    /// </summary>
    [Fact]
    public void ReferenceScenario_Descidas_Has4Entries()
    {
        var descidas = ReferenceScenario.Descidas ?? [];
        Assert.Equal(4, descidas.Count);

        var expectedDescidaPassoIds = new[]
        {
            "_0XWagVqNEfG5K7mY0I3I6w",   // Aguardar evento de Notificacao do AIIM → DEAT0050
            "_CI6lyFqREfG5K7mY0I3I6w",   // Prepara Intimação → PRPINTPC
            "_CtQ691qPEfG5K7mY0I3I6w",   // Busca Emails → BSCENVPC
            "_nQntZ16JEfGBBLgT-R5iuw",   // Controlar Intimados → CONTROPC (NOEQ-dynamic-subprocess)
        };

        var declaredPassoIds = descidas.Select(d => d.PassoId).ToHashSet();

        foreach (var expectedId in expectedDescidaPassoIds)
        {
            Assert.True(declaredPassoIds.Contains(expectedId),
                $"Descida '{expectedId}' ausente na fixture {ReferenceScenarioId} — " +
                $"AC3: a omissão de uma descida deve falhar com indicação explícita do nó.");
        }

        _output.WriteLine($"[ok] {descidas.Count} descidas presentes, todas verificadas.");
    }

    // =========================================================================
    // AC3 — descida para CONTROPC (Controlar Intimados, passo 36) declara
    //        cenários de sub-processo e é dinâmica
    // =========================================================================

    /// <summary>
    /// AC3 — A descida para CONTROPC (Controlar Intimados, passo 36) está
    /// declarada como dinâmica (dinamica=true) e aponta para CONTROPC.
    /// Este é o passo que exercita o NOEQ-dynamic-subprocess via
    /// interface-registry-validated.
    /// </summary>
    [Fact]
    public void ReferenceScenario_DescidaContropc_IsDinamica_AndHasSubProcessCenarios()
    {
        var descidas = ReferenceScenario.Descidas ?? [];
        var descida = descidas.FirstOrDefault(d => d.PassoId == DescidaContropcPassoId);

        Assert.NotNull(descida);
        Assert.Equal("CONTROPC", descida.ContinuaEm);
        Assert.True(descida.Dinamica,
            $"[NOEQ-dynamic-subprocess] Descida CONTROPC " +
            $"(id={DescidaContropcPassoId}) não está marcada como dinâmica — " +
            "o subprocesso dinâmico deve ser declarado com dinamica=true.");
        Assert.NotNull(descida.Cenarios);
        Assert.True(descida.Cenarios!.Count > 0,
            $"[NOEQ-dynamic-subprocess] Descida CONTROPC " +
            $"(id={DescidaContropcPassoId}) não declara cenários de sub-processo.");

        _output.WriteLine(
            $"[ok] Descida CONTROPC: dinamica={descida.Dinamica}, " +
            $"{descida.Cenarios!.Count} cenário(s) declarados — NOEQ-dynamic-subprocess confirmado.");
    }

    // =========================================================================
    // AC3 — 2 inputs obrigatórios declarados na fixture
    // =========================================================================

    /// <summary>
    /// AC3 — A fixture declara exactamente 2 inputs obrigatórios.
    /// A ausência de qualquer um causa falha com identificação do input em falta.
    /// Valores lidos do oracle — nunca escritos aqui.
    /// </summary>
    [Fact]
    public void ReferenceScenario_InputsRequired_Has2Entries()
    {
        var inputs = ReferenceScenario.InputsRequired ?? [];
        Assert.Equal(2, inputs.Count);

        var expectedCampos = new[] { "CORRECAO", "TIPOVISTAS" };
        var declaredCampos = inputs.Select(i => i.Campo).ToHashSet();

        foreach (var campo in expectedCampos)
        {
            Assert.True(declaredCampos.Contains(campo),
                $"Input obrigatório '{campo}' ausente na fixture {ReferenceScenarioId} — " +
                $"AC3: a ausência deve causar falha imediata com identificação do input.");
        }

        _output.WriteLine($"[ok] {inputs.Count} inputs obrigatórios presentes: {string.Join(", ", declaredCampos)}.");
    }

    // =========================================================================
    // AC3 — os 5 nós NOEQ do processo principal (AC3 explícito) presentes
    //        no path de referência com campos corretos
    // =========================================================================

    /// <summary>
    /// AC3 — Os 5 nós NOEQ do processo principal que não existem como transição
    /// XPDL estão representados no percurso de referência com os IDs, tipos e
    /// mecanismos corretos, conforme declarado no card VALID-ETAPA6-percurso.
    ///
    /// O arnes .NET deve emitir estes eventos explicitamente — nunca presumi-los
    /// como transições automáticas do motor.
    /// </summary>
    [Fact]
    public void ReferenceScenario_NoeqMainProcessNodes_PresentWithCorrectFieldsInPath()
    {
        var path = ReferenceScenario.Path!;
        var pathById = path.ToDictionary(n => n.Id, StringComparer.Ordinal);

        foreach (var (nodeId, (nome, tipo, entrouPor, noeqKind)) in NoeqMainProcessNodes)
        {
            Assert.True(pathById.ContainsKey(nodeId),
                $"[{noeqKind}] Nó NOEQ '{nome}' (id={nodeId}) ausente no path[] de " +
                $"{ReferenceScenarioId}. A ausência constitui falha de AC3.");

            var node = pathById[nodeId];
            Assert.Equal(tipo, node.Tipo);

            if (entrouPor is null)
                Assert.Null(node.EntrouPor);
            else
                Assert.Equal(entrouPor, node.EntrouPor, StringComparer.OrdinalIgnoreCase);

            _output.WriteLine(
                $"[ok] [{noeqKind}] '{nome}' (id={nodeId}, tipo={node.Tipo}, " +
                $"entrouPor={node.EntrouPor ?? "null"}) — explicitamente representado.");
        }
    }

    // =========================================================================
    // AC3 — id, nome, tipo, escopo e entrouPor dos nós do percurso de referência
    //        estão presentes e não-nulos para os campos obrigatórios
    // =========================================================================

    [Fact]
    public void ReferenceScenario_AllPathNodes_HaveRequiredFields()
    {
        var path = ReferenceScenario.Path!;

        for (var i = 0; i < path.Count; i++)
        {
            var node = path[i];
            Assert.False(string.IsNullOrWhiteSpace(node.Id),
                $"path[{i}]: campo 'id' ausente.");
            Assert.False(string.IsNullOrWhiteSpace(node.Nome),
                $"path[{i}] (id={node.Id}): campo 'nome' ausente.");
            Assert.False(string.IsNullOrWhiteSpace(node.Tipo),
                $"path[{i}] (id={node.Id}): campo 'tipo' ausente.");
            Assert.False(string.IsNullOrWhiteSpace(node.Escopo),
                $"path[{i}] (id={node.Id}): campo 'escopo' ausente.");
            // entrouPor pode ser null (passo 1 — arranque)
        }

        _output.WriteLine(
            $"[ok] Todos os {path.Count} nós do percurso de referência têm " +
            $"id, nome, tipo e escopo preenchidos.");
    }

    // =========================================================================
    // AC4 — cada cenário tem rasto de nós (instance-trace evidence)
    // =========================================================================

    /// <summary>
    /// AC4 — Para cada um dos 27 cenários, o arquivo de detalhe existe e
    /// contém pelo menos um segmento com nós (rasto de instância não vazio).
    /// Rastreia: confidence.basis = "o oráculo é o cenário derivado do grafo".
    /// </summary>
    [Theory]
    [MemberData(nameof(Etapa6ScenarioIds))]
    public void Etapa6_Scenario_HasAtLeastOneNodeInTrace(string scenarioId, string process)
    {
        var detail = ScenarioFixtureLoader.LoadScenario(scenarioId);

        Assert.NotNull(detail.Segmentos);
        Assert.NotEmpty(detail.Segmentos);

        var totalNodes = detail.Segmentos
            .SelectMany(s => s.Nos ?? [])
            .Count();

        Assert.True(totalNodes > 0,
            $"[{scenarioId}] Rasto de instância vazio — nenhum nó encontrado nos segmentos.");

        _output.WriteLine($"[ok] {scenarioId} ({process}): {totalNodes} nós no rasto.");
    }

    // =========================================================================
    // AC2 — rasto bate passo a passo com o percurso do cenário (fixture)
    //        Para cada cenário POC_EpatProcess da etapa 6:
    //          a) Cada nó nos segmentos de etapa 6 tem ID não vazio.
    //          b) Segmentos de etapa 6 estão ordenados por ordemNaJornada.
    //          c) Dentro de cada segmento, os nós aparecem na sequência declarada.
    //          d) Cada segmento tem pelo menos um nó.
    // =========================================================================

    [Theory]
    [MemberData(nameof(Etapa6PocEpatScenarioIds))]
    public void Etapa6_POCEpatProcess_Scenario_Etapa6Nodes_MatchReferenceOrderStepByStep(
        string scenarioId)
    {
        var detail = ScenarioFixtureLoader.LoadScenario(scenarioId);

        // Filtrar apenas segmentos que pertencem à etapa 6
        var etapa6Segments = (detail.Segmentos ?? [])
            .Where(s => s.Etapas != null && s.Etapas.Contains(6))
            .OrderBy(s => s.OrdemNaJornada)
            .ToList();

        Assert.True(etapa6Segments.Count > 0,
            $"[{scenarioId}] Nenhum segmento com etapas=[..6..] encontrado.");

        // (b) Segmentos ordenados por ordemNaJornada
        int prevOrdem = -1;
        foreach (var seg in etapa6Segments)
        {
            Assert.True(seg.OrdemNaJornada >= prevOrdem,
                $"[{scenarioId}] Segmento etapa 6 fora de ordem: " +
                $"ordemNaJornada={seg.OrdemNaJornada} < anterior={prevOrdem}.");
            prevOrdem = seg.OrdemNaJornada;

            // (d) Cada segmento tem pelo menos um nó
            Assert.True(seg.Nos is { Count: > 0 },
                $"[{scenarioId}] Segmento etapa 6 ordemNaJornada={seg.OrdemNaJornada} " +
                $"(doPasso={seg.DoPasso}) está vazio — rasto ausente.");

            // (a) Cada nó tem ID não vazio
            foreach (var no in seg.Nos!)
            {
                Assert.False(string.IsNullOrWhiteSpace(no.Id),
                    $"[{scenarioId}] Nó com id vazio no segmento doPasso={seg.DoPasso}.");
            }

            // (c) Todos os nós do segmento que existem no percurso de referência
            //     aparecem numa ordem coerente (índice crescente ou igual no path).
            //     Nós de sub-processo podem não estar no path principal — são aceites.
            int prevRefIdx = -1;
            foreach (var no in seg.Nos!)
            {
                if (!ReferenceNodeOrder.TryGetValue(no.Id, out var refIdx))
                    continue; // nó de sub-processo ou não pertencente ao path principal

                Assert.True(refIdx >= prevRefIdx,
                    $"[{scenarioId}] Nó '{no.Id}' (refIdx={refIdx}) fora de ordem " +
                    $"no segmento doPasso={seg.DoPasso} — desvio no passo {refIdx + 1}.");
                prevRefIdx = refIdx;
            }
        }

        var totalNodes = etapa6Segments.SelectMany(s => s.Nos!).Count();
        _output.WriteLine(
            $"[ok] {scenarioId}: {etapa6Segments.Count} segmento(s) de etapa 6, " +
            $"{totalNodes} nós — todos estruturalmente válidos.");
    }

    // =========================================================================
    // AC2 — cobertura total: o nó do segmento etapa 6 é coberto em conjunto
    //        pelos cenários POC_EpatProcess de etapa 6
    // =========================================================================

    [Fact]
    public void Etapa6_POCEpatProcess_Coverage_AllEtapa6ReferenceNodesVisitedAcrossScenarios()
    {
        var pocScenarios = Etapa6Scenarios
            .Where(s => s.Process == "POC_EpatProcess")
            .ToList();

        var coveredIds = new HashSet<string>(StringComparer.Ordinal);

        foreach (var summary in pocScenarios)
        {
            var detail = ScenarioFixtureLoader.LoadScenario(summary.Id);
            var etapa6Nodes = (detail.Segmentos ?? [])
                .Where(s => s.Etapas != null && s.Etapas.Contains(6))
                .SelectMany(s => s.Nos ?? [])
                .Select(n => n.Id)
                .Where(id => !string.IsNullOrWhiteSpace(id));

            foreach (var id in etapa6Nodes)
                coveredIds.Add(id!);
        }

        var missing = Etapa6ReferenceNodeIds
            .Where(id => !coveredIds.Contains(id))
            .ToList();

        if (missing.Count > 0)
        {
            var details = string.Join(", ", missing.Select(id =>
            {
                var idx = ReferenceNodeOrder.TryGetValue(id, out var i) ? i + 1 : -1;
                return $"passo {idx}: '{id}'";
            }));
            Assert.Fail(
                $"Os seguintes nós canónicos da etapa 6 não foram cobertos por nenhum cenário: {details}");
        }

        _output.WriteLine(
            $"[ok] Todos os {Etapa6ReferenceNodeIds.Count} nós de referência da etapa 6 " +
            $"são cobertos pelos {pocScenarios.Count} cenários POC_EpatProcess.");
    }

    // =========================================================================
    // AC1 — fixture permanece imutável
    // =========================================================================

    /// <summary>
    /// AC1 — Confirma que nenhum dos 27 cenários POC_EpatProcess de etapa 6
    /// tem o campo 'path' nulo ou vazio no ficheiro de detalhe
    /// (o rasto vem da fixture, não do arnes).
    /// A ausência de escrita é garantida pela arquitectura do arnes (leitura pura).
    /// </summary>
    [Theory]
    [MemberData(nameof(Etapa6PocEpatScenarioIds))]
    public void Etapa6_Scenario_FixtureIsReadOnly_PathFieldNotWrittenByHarness(string scenarioId)
    {
        var detail = ScenarioFixtureLoader.LoadScenario(scenarioId);

        var hasSomeTrace = (detail.Path is { Count: > 0 })
            || (detail.Segmentos is { Count: > 0 });

        Assert.True(hasSomeTrace,
            $"[{scenarioId}] Fixture sem rasto (path[] vazio e segmentos[] vazio) — " +
            "a fixture deve vir do kit, não ser escrita pelo arnes.");

        _output.WriteLine(
            $"[ok] {scenarioId}: fixture contém rasto — " +
            $"path={detail.Path?.Count ?? 0} nós, segmentos={detail.Segmentos?.Count ?? 0}.");
    }

    // =========================================================================
    // AC4 — divergência reportada por caso e por passo com identificação exata
    //        Valida que o mecanismo de diagnóstico do arnes identifica a posição
    //        exata de uma divergência hipotética no rasto.
    // =========================================================================

    /// <summary>
    /// AC4 — Confirma que o percurso de referência contém o nó 'Controlar Intimados'
    /// (passo 36) na posição 35 (0-based). Uma divergência neste passo deve ser
    /// imediatamente identificável porque o índice de referência é 35 e o nome do
    /// nó é 'Controlar Intimados'.
    ///
    /// Rastreia: confidence.basis = "o oráculo é o cenário derivado do grafo;
    /// não há interpretação no arnes".
    /// </summary>
    [Fact]
    public void ReferenceScenario_ControlarIntimados_AtExpectedPosition_EnablesPreciseDivergenceReport()
    {
        var path = ReferenceScenario.Path!;

        Assert.True(ReferenceNodeOrder.TryGetValue("_nQntZ16JEfGBBLgT-R5iuw", out var refIdx),
            "Nó 'Controlar Intimados' (_nQntZ16JEfGBBLgT-R5iuw) ausente no path[] — " +
            "AC4: não é possível reportar divergência por posição.");

        Assert.Equal(35, refIdx);

        var node = path[refIdx];
        Assert.Equal("Controlar Intimados", node.Nome);
        Assert.Equal("callActivity", node.Tipo);

        _output.WriteLine(
            $"[ok] 'Controlar Intimados' em posição {refIdx} (passo {refIdx + 1}) — " +
            "divergência neste passo seria reportada como 'passo 36: Controlar Intimados'.");
    }

    // =========================================================================
    // AC2 — sequência prepSub→ControlarIntimados→Fim bate com o path[]
    // =========================================================================

    /// <summary>
    /// AC2 — Confirma que os passos finais do percurso de referência estão na
    /// ordem correcta: prepSub (passo 35) → Controlar Intimados (passo 36) → Fim (passo 37).
    ///
    /// Rastreia: acceptance.criteria[0] e segmento ordemNaJornada=9 (etapa 6).
    /// </summary>
    [Fact]
    public void ReferenceScenario_FinalSequence_PrepSub_ControlarIntimados_Fim_IsInCorrectOrder()
    {
        const string prepSubId         = "_zE3XeV6JEfGBBLgT-R5iuw";   // passo 35
        const string controlarId       = "_nQntZ16JEfGBBLgT-R5iuw";   // passo 36
        const string fimId             = "_H22mclqWEfG5K7mY0I3I6w";   // passo 37

        Assert.True(ReferenceNodeOrder.TryGetValue(prepSubId,   out var prepSubIdx),
            $"'prepSub' ({prepSubId}) ausente no path[].");
        Assert.True(ReferenceNodeOrder.TryGetValue(controlarId, out var controlarIdx),
            $"'Controlar Intimados' ({controlarId}) ausente no path[].");
        Assert.True(ReferenceNodeOrder.TryGetValue(fimId,       out var fimIdx),
            $"'Fim' ({fimId}) ausente no path[].");

        Assert.True(prepSubIdx < controlarIdx,
            $"prepSub (idx={prepSubIdx}) deve preceder Controlar Intimados (idx={controlarIdx}).");
        Assert.True(controlarIdx < fimIdx,
            $"Controlar Intimados (idx={controlarIdx}) deve preceder Fim (idx={fimIdx}).");

        var path = ReferenceScenario.Path!;
        Assert.Equal("scriptTask",   path[prepSubIdx].Tipo);
        Assert.Equal("callActivity", path[controlarIdx].Tipo);
        Assert.Equal("endEvent",     path[fimIdx].Tipo);

        _output.WriteLine(
            $"[ok] passo {prepSubIdx + 1}→{controlarIdx + 1}→{fimIdx + 1}: " +
            $"prepSub → Controlar Intimados → Fim — ordem correcta.");
    }
}
