// <auto-generated-harness>
//   Arnes gerado para VALID-ETAPA5-percurso (SSTN-73).
//   Fixture de referencia: artifacts/POC_Epat/scenarios/SC-POC_EpatProcess-009.json — IMUTAVEL.
//   O agente NUNCA escreve nem edita valores esperados.
//   AC-ORACULO: suite scenario-path, 45 caso(s) (etapas contendo 5).
//
//   Rulings verificados antes da implementacao:
//     BUILTIN-SEMANTICS        : decidido — semantica confirmada para migracao
//     CLONE-PRPINTPC           : decidido — corrigir para STATUS_CODE != '0'
//     LABEL-CONFLICT           : decidido — nomear por deducao
//     MISSING-EXTERNAL-PACKAGES: decidido — pacotes externos nao entregues tratados
//     SCRIPT-HARDCODED         : decidido — tratamento diferente por valor
//     TYPE-XPDL-VS-FORM        : decidido — long vs int resolvido
// </auto-generated-harness>
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using SefazSp.Epat.Oracles.Tests.Fixture;
using FxScenarioDetail = SefazSp.Epat.Oracles.Tests.Fixture.ScenarioDetail;
using FxScenarioSummary = SefazSp.Epat.Oracles.Tests.Fixture.ScenarioSummary;
using Xunit;
using Xunit.Abstractions;

namespace SefazSp.Epat.Oracles.Tests.ScenarioPath;

/// <summary>
/// AC-ORACULO — Suite scenario-path que cobre os 45 casos da etapa 5
/// (Validação de Gateways Paralelos) declarados na fixture
/// artifacts/POC_Epat/scenarios/SC-POC_EpatProcess-009.json.
///
/// Regras:
///   • O agente não escreve nem altera nenhum valor esperado.
///   • O oracle é o conteúdo das fixtures — imutável.
///   • O arnes valida que o rasto declarado em cada cenário bate passo a
///     passo com o percurso de referência (SC-POC_EpatProcess-009,
///     37 passos: de 'Iniciar Novo Graft' a 'Fim').
///
/// Segmento da etapa 5: passos 22–35 (doPasso=22, aoPasso=35), 14 nós.
///
/// Nós NOEQ do processo principal (escritos explicitamente no arnes .NET):
///   • passo 23 (_Ei94AFqPEfG5K7mY0I3I6w, 'Validação Paralelos', linkCatch,
///     entrouPor=link)      — NOEQ-link-goto: POC_EpatProcess/Validação Paralelos.
///   • passo 27 (_CtQ7A1qPEfG5K7mY0I3I6w, timerEvent, entrouPor=fronteira)
///     — NOEQ-non-interrupting-boundary: timer boundary Elsa 3, escrever explicitamente.
///
/// Nós NOEQ em sub-processos (representados via descidas declaradas na fixture):
///   • NOEQ-non-interrupting-boundary : BSCENVPC/Busca Emails
///     → descida 'Busca Emails' (id=_CtQ691qPEfG5K7mY0I3I6w, continuaEm=BSCENVPC)
/// </summary>
public sealed class Etapa5PercursoOracleTests
{
    // ─── fixture de referência ────────────────────────────────────────────────

    /// <summary>Identificador canónico do percurso de referência da etapa 5.</summary>
    private const string ReferenceScenarioId = "SC-POC_EpatProcess-009";

    /// <summary>
    /// Fixture de referência — imutável. Carregada uma vez por classe.
    /// path[] de 37 nós: de 'Iniciar Novo Graft' a 'Fim'.
    /// </summary>
    private static readonly FxScenarioDetail ReferenceScenario =
        ScenarioFixtureLoader.LoadScenario(ReferenceScenarioId);

    /// <summary>
    /// Mapa ordenado: nodeId → índice 0-based no percurso de referência.
    /// </summary>
    private static readonly IReadOnlyDictionary<string, int> ReferenceNodeOrder =
        BuildReferenceNodeOrder();

    private static IReadOnlyDictionary<string, int> BuildReferenceNodeOrder()
    {
        var path = ReferenceScenario.Path
                   ?? throw new InvalidOperationException(
                       $"{ReferenceScenarioId}: campo 'path' ausente — fixture inválida.");
        var dict = new Dictionary<string, int>(path.Count);
        for (var i = 0; i < path.Count; i++)
            dict[path[i].Id] = i;
        return dict;
    }

    // ─── nós NOEQ do processo principal (AC4, AC5) ───────────────────────────
    // Fonte: card VALID-ETAPA5-percurso, secção "Passos que NÃO existem como
    // transição no XPDL".  Os IDs são imutáveis — nunca renomear.

    private static readonly IReadOnlyDictionary<string, (string Nome, string Tipo, string? EntrouPor, string NoeqKind)>
        NoeqMainProcessNodes =
        new Dictionary<string, (string, string, string?, string)>(StringComparer.Ordinal)
        {
            // passo 23 · Validação Paralelos · linkCatch · entrouPor=link
            // NOEQ-link-goto: ativado pelo linkThrow _89MVQlqVEfG5K7mY0I3I6w (passo 22).
            // Não existe como transição XPDL directa — escrever a resolução do link explicitamente.
            ["_Ei94AFqPEfG5K7mY0I3I6w"] = ("Validação Paralelos", "linkCatch",  "link",      "NOEQ-link-goto"),
            // passo 27 · timerEvent _CtQ7A1qPEfG5K7mY0I3I6w · timerEvent · entrouPor=fronteira
            // NOEQ-non-interrupting-boundary: evento de fronteira do Elsa 3.
            // Não existe como transição XPDL directa — escrever o timer boundary explicitamente.
            ["_CtQ7A1qPEfG5K7mY0I3I6w"] = ("timerEvent _CtQ7A1qPEfG5K7mY0I3I6w", "timerEvent", "fronteira", "NOEQ-non-interrupting-boundary"),
        };

    // ─── nós canónicos da etapa 5 no percurso de referência (passos 22–35) ──
    // Fonte: path[] da fixture SC-POC_EpatProcess-009.json, índices 21–34.
    // IDs imutáveis — nunca renomear.

    private static readonly IReadOnlyList<string> Etapa5ReferenceNodeIds =
    [
        "_89MVQlqVEfG5K7mY0I3I6w",   // passo 22 — Validar Paralelos (linkThrow)
        "_Ei94AFqPEfG5K7mY0I3I6w",   // passo 23 — Validação Paralelos (linkCatch, link) NOEQ-link-goto
        "_CtQ7BFqPEfG5K7mY0I3I6w",   // passo 24 — Vistas do Juiz ? (gateway)
        "_CtQ7BVqPEfG5K7mY0I3I6w",   // passo 25 — gateway _CtQ7BVqPEfG5K7mY0I3I6w (gateway)
        "_CtQ68lqPEfG5K7mY0I3I6w",   // passo 26 — Pedido de Vistas (receiveTask)
        "_CtQ7A1qPEfG5K7mY0I3I6w",   // passo 27 — timerEvent (timerEvent, fronteira) NOEQ-non-interrupting-boundary
        "_CtQ66FqPEfG5K7mY0I3I6w",   // passo 28 — FimDRF (signalThrow)
        "_CtQ691qPEfG5K7mY0I3I6w",   // passo 29 — Busca Emails (callActivity) → BSCENVPC
        "_CtQ7AVqPEfG5K7mY0I3I6w",   // passo 30 — VoltaAgenda (scriptTask)
        "_CtQ7AlqPEfG5K7mY0I3I6w",   // passo 31 — Tipo de Vista Mista? (gateway)
        "_CtQ7AFqPEfG5K7mY0I3I6w",   // passo 32 — gateway _CtQ7AFqPEfG5K7mY0I3I6w (gateway)
        "_CtQ69FqPEfG5K7mY0I3I6w",   // passo 33 — gateway _CtQ69FqPEfG5K7mY0I3I6w (gateway)
        "_CtQ6-lqPEfG5K7mY0I3I6w",   // passo 34 — gateway _CtQ6-lqPEfG5K7mY0I3I6w (gateway)
        "_zE3XeV6JEfGBBLgT-R5iuw",   // passo 35 — prepSub (scriptTask)
    ];

    // ─── ID da descida que representa nós NOEQ de sub-processos ──────────────
    // Fonte: fixture SC-POC_EpatProcess-009.json, campo descidas[].

    /// <summary>
    /// Descida para BSCENVPC (Busca Emails, passo 29) — cobre
    /// NOEQ-non-interrupting-boundary de BSCENVPC.
    /// </summary>
    private const string DescidaBscenvpcPassoId = "_CtQ691qPEfG5K7mY0I3I6w";

    // ─── conjunto de 45 cenários da etapa 5 ──────────────────────────────────

    private static readonly IReadOnlyList<FxScenarioSummary> Etapa5Scenarios =
        LoadEtapa5Scenarios();

    private static IReadOnlyList<FxScenarioSummary> LoadEtapa5Scenarios()
    {
        var index = ScenarioFixtureLoader.LoadIndex();
        return index.Scenarios
            .Where(s => s.Etapas != null && s.Etapas.Contains(5))
            .ToList();
    }

    public static IEnumerable<object[]> Etapa5ScenarioIds() =>
        Etapa5Scenarios.Select(s => new object[] { s.Id, s.Process });

    public static IEnumerable<object[]> Etapa5PocEpatScenarioIds() =>
        Etapa5Scenarios
            .Where(s => s.Process == "POC_EpatProcess")
            .Select(s => new object[] { s.Id });

    // ─── glossário ────────────────────────────────────────────────────────────

    private static readonly string GlossaryPath =
        Path.Combine(ScenarioFixtureLoader.RepoRootPath, "config", "glossary", "POC_Epat.yaml");

    private readonly ITestOutputHelper _output;

    public Etapa5PercursoOracleTests(ITestOutputHelper output) => _output = output;

    // =========================================================================
    // AC1 — glossário: rulings bloqueadoras estão preenchidas
    // =========================================================================

    /// <summary>
    /// Confirma que o glossário existe e que as seis rulings bloqueadoras
    /// declaradas no card (BUILTIN-SEMANTICS, CLONE-PRPINTPC, LABEL-CONFLICT,
    /// MISSING-EXTERNAL-PACKAGES, SCRIPT-HARDCODED, TYPE-XPDL-VS-FORM)
    /// têm campo 'decisao:' não vazio — pré-condição para que o arnes possa
    /// ser executado.
    /// </summary>
    [Fact]
    public void Glossary_BlockerRulings_AllSixDecisoesFilled()
    {
        Assert.True(File.Exists(GlossaryPath),
            $"Glossário não encontrado: {GlossaryPath}");

        var yaml = File.ReadAllText(GlossaryPath);

        var requiredRulings = new[]
        {
            "BUILTIN-SEMANTICS",
            "CLONE-PRPINTPC",
            "LABEL-CONFLICT",
            "MISSING-EXTERNAL-PACKAGES",
            "SCRIPT-HARDCODED",
            "TYPE-XPDL-VS-FORM",
        };

        foreach (var key in requiredRulings)
        {
            var blockIdx = yaml.IndexOf($"\n  {key}:\n", StringComparison.Ordinal);
            Assert.True(blockIdx >= 0,
                $"Ruling '{key}' não encontrada no glossário '{GlossaryPath}'.");

            var block = yaml.Substring(blockIdx, Math.Min(2000, yaml.Length - blockIdx));
            var decisaoIdx = block.IndexOf("    decisao:", StringComparison.Ordinal);
            Assert.True(decisaoIdx >= 0,
                $"Ruling '{key}': campo 'decisao:' ausente — ruling não está respondida.");

            var after = block.Substring(decisaoIdx + 12).TrimStart();
            var firstLine = after.Split('\n')[0].Trim().Trim('"').Trim('\'');
            Assert.False(string.IsNullOrWhiteSpace(firstLine),
                $"Ruling '{key}': campo 'decisao:' está vazio — ruling não ratificada.");

            _output.WriteLine($"[ruling-ok] {key}: {firstLine[..Math.Min(80, firstLine.Length)]}");
        }
    }

    // =========================================================================
    // AC1 — fixture: referência carrega sem erro
    // =========================================================================

    [Fact]
    public void ReferenceScenario_LoadsWithoutError()
    {
        Assert.Equal(ReferenceScenarioId, ReferenceScenario.Id);
        Assert.Equal("POC_EpatProcess", ReferenceScenario.Process);

        var path = ReferenceScenario.Path;
        Assert.NotNull(path);
        Assert.NotEmpty(path);

        _output.WriteLine(
            $"[ok] {ReferenceScenarioId} carregado: {path.Count} nós no path.");
    }

    // =========================================================================
    // AC1 — percurso de referência arranca em 'Iniciar Novo Graft' e termina
    //        em 'Fim' (AC1: nó inicial e nó final confirmados)
    // =========================================================================

    [Fact]
    public void ReferenceScenario_Path_Has37Steps_FromIniciarNovoGraftToFim()
    {
        var path = ReferenceScenario.Path!;
        Assert.Equal(37, path.Count);

        var first = path[0];
        Assert.Equal("_OAgPol9UEfG6Lfb98zsREQ", first.Id);
        Assert.Equal("Iniciar Novo Graft", first.Nome);
        Assert.Equal("receiveTask", first.Tipo);

        var last = path[^1];
        Assert.Equal("_H22mclqWEfG5K7mY0I3I6w", last.Id);
        Assert.Equal("Fim", last.Nome);
        Assert.Equal("endEvent", last.Tipo);

        _output.WriteLine($"[ok] path[0]={first.Nome} ({first.Tipo}), path[36]={last.Nome} ({last.Tipo})");
    }

    // =========================================================================
    // AC2 — 45 cenários declarados com etapas contendo 5
    // =========================================================================

    [Fact]
    public void Etapa5_IndexDeclares45Scenarios()
    {
        Assert.Equal(45, Etapa5Scenarios.Count);
        _output.WriteLine($"[ok] {Etapa5Scenarios.Count} cenários com etapas contendo 5.");
    }

    // =========================================================================
    // AC2 — distribuição por processo nos 45 cenários da etapa 5
    // =========================================================================

    [Fact]
    public void Etapa5_ScenarioCountByProcess_MatchesExpected()
    {
        var byProcess = Etapa5Scenarios
            .GroupBy(s => s.Process)
            .ToDictionary(g => g.Key, g => g.Count());

        // Valores lidos do oráculo (index.json) — nunca escritos aqui.
        Assert.Equal(39, byProcess.GetValueOrDefault("POC_EpatProcess", 0));
        Assert.Equal(6,  byProcess.GetValueOrDefault("BSCENVPC",        0));

        foreach (var (proc, count) in byProcess.OrderBy(kv => kv.Key))
            _output.WriteLine($"[ok] {proc}: {count} cenários");
    }

    // =========================================================================
    // AC3 — os 14 nós do segmento etapa 5 (passos 22–35) estão presentes no
    //        percurso de referência nas posições corretas
    // =========================================================================

    /// <summary>
    /// Verifica que os 14 nós da etapa 5 existem no path[] da fixture de
    /// referência, nas posições 21–34 (0-based), e que os nós NOEQ têm os
    /// valores de entrouPor declarados no card.
    /// O arnes não injeta valores — apenas confirma que o oracle os declara.
    /// </summary>
    [Fact]
    public void ReferenceScenario_Etapa5Nodes_PresentWithCorrectPositionAndEntrouPor()
    {
        var path = ReferenceScenario.Path!;
        var pathById = path.ToDictionary(n => n.Id, StringComparer.Ordinal);

        // Posições esperadas (0-based = passo - 1) conforme a fixture
        var expected = new (int PassoZeroBased, string NodeId, string? ExpectedEntrouPor)[]
        {
            (21, "_89MVQlqVEfG5K7mY0I3I6w", "fluxo"),    // passo 22 — Validar Paralelos (linkThrow)
            (22, "_Ei94AFqPEfG5K7mY0I3I6w", "link"),     // passo 23 — Validação Paralelos (linkCatch, NOEQ-link-goto)
            (23, "_CtQ7BFqPEfG5K7mY0I3I6w", "fluxo"),    // passo 24 — Vistas do Juiz ?
            (24, "_CtQ7BVqPEfG5K7mY0I3I6w", "fluxo"),    // passo 25 — gateway
            (25, "_CtQ68lqPEfG5K7mY0I3I6w", "fluxo"),    // passo 26 — Pedido de Vistas
            (26, "_CtQ7A1qPEfG5K7mY0I3I6w", "fronteira"), // passo 27 — timerEvent (NOEQ)
            (27, "_CtQ66FqPEfG5K7mY0I3I6w", "fluxo"),    // passo 28 — FimDRF
            (28, "_CtQ691qPEfG5K7mY0I3I6w", "fluxo"),    // passo 29 — Busca Emails
            (29, "_CtQ7AVqPEfG5K7mY0I3I6w", "fluxo"),    // passo 30 — VoltaAgenda
            (30, "_CtQ7AlqPEfG5K7mY0I3I6w", "fluxo"),    // passo 31 — Tipo de Vista Mista?
            (31, "_CtQ7AFqPEfG5K7mY0I3I6w", "fluxo"),    // passo 32 — gateway
            (32, "_CtQ69FqPEfG5K7mY0I3I6w", "fluxo"),    // passo 33 — gateway
            (33, "_CtQ6-lqPEfG5K7mY0I3I6w", "fluxo"),    // passo 34 — gateway
            (34, "_zE3XeV6JEfGBBLgT-R5iuw", "fluxo"),    // passo 35 — prepSub
        };

        foreach (var (idx, nodeId, expectedEntrouPor) in expected)
        {
            Assert.True(pathById.ContainsKey(nodeId),
                $"Nó '{nodeId}' declarado no card não encontrado no path[] de {ReferenceScenarioId}.");

            var node = path[idx];
            Assert.Equal(nodeId, node.Id);

            if (expectedEntrouPor is null)
                Assert.Null(node.EntrouPor);
            else
                Assert.Equal(expectedEntrouPor, node.EntrouPor,
                    StringComparer.OrdinalIgnoreCase);

            _output.WriteLine(
                $"[ok] passo {idx + 1}: {node.Nome} (id={nodeId}, entrouPor={node.EntrouPor ?? "null"})");
        }
    }

    // =========================================================================
    // AC3 — fluxos paralelos: Validação Paralelos (linkCatch, passo 23) entra
    //        por mecanismo 'link' — conceito central 'fluxos-paralelos' / 'paralelo-sincronizacao'
    // =========================================================================

    /// <summary>
    /// AC3 — Confirma especificamente que o nó 'Validação Paralelos' (passo 23,
    /// _Ei94AFqPEfG5K7mY0I3I6w) entra por mecanismo 'link' — NOEQ-link-goto:
    /// não existe como transição XPDL directa; deve ser escrito explicitamente
    /// no arnes .NET, conforme declarado no card VALID-ETAPA5-percurso.
    ///
    /// Rastreia: fulfills.concepts='fluxos-paralelos', AC5 e passo 22→23 do path[].
    /// </summary>
    [Fact]
    public void ReferenceScenario_ValidacaoParalelos_LinkCatch_EntrouPorLink()
    {
        var path = ReferenceScenario.Path!;

        // passo 23 = índice 22 (0-based)
        var node = path[22];
        Assert.Equal("_Ei94AFqPEfG5K7mY0I3I6w", node.Id);
        Assert.Equal("Validação Paralelos", node.Nome);
        Assert.Equal("linkCatch", node.Tipo);
        Assert.Equal("link", node.EntrouPor, StringComparer.OrdinalIgnoreCase);

        _output.WriteLine(
            $"[ok] passo 23: {node.Nome} (id={node.Id}, tipo={node.Tipo}, entrouPor={node.EntrouPor})");
    }

    // =========================================================================
    // AC4 — timerEvent (passo 27) entra por 'fronteira' — timer boundary Elsa 3
    // =========================================================================

    /// <summary>
    /// AC4 — Confirma que o nó timerEvent (passo 27, _CtQ7A1qPEfG5K7mY0I3I6w)
    /// entra por mecanismo 'fronteira' — NOEQ-non-interrupting-boundary:
    /// evento de fronteira de timer do Elsa 3; não é transição XPDL directa.
    /// Deve ser escrito explicitamente no arnes .NET.
    ///
    /// Rastreia: AC4 do card VALID-ETAPA5-percurso, passo 27 do path[].
    /// </summary>
    [Fact]
    public void ReferenceScenario_TimerEvent_EntrouPorFronteira()
    {
        var path = ReferenceScenario.Path!;

        // passo 27 = índice 26 (0-based)
        var node = path[26];
        Assert.Equal("_CtQ7A1qPEfG5K7mY0I3I6w", node.Id);
        Assert.Equal("timerEvent", node.Tipo);
        Assert.Equal("fronteira", node.EntrouPor, StringComparer.OrdinalIgnoreCase);

        _output.WriteLine(
            $"[ok] passo 27: {node.Nome} (id={node.Id}, tipo={node.Tipo}, entrouPor={node.EntrouPor})");
    }

    // =========================================================================
    // AC3 — 5 decisões declaradas na fixture
    // =========================================================================

    /// <summary>
    /// AC3 — A fixture declara exactamente 5 pontos de decisão (decisions=5).
    /// Se alguma decisão for omitida, o teste falha com indicação explícita.
    /// Valores lidos do oracle — nunca escritos aqui.
    /// </summary>
    [Fact]
    public void ReferenceScenario_Decisions_Has5Entries()
    {
        var decisions = ReferenceScenario.Decisions ?? [];
        Assert.Equal(5, decisions.Count);

        var expectedDecisionIds = new[]
        {
            "_sJqYklqTEfG5K7mY0I3I6w",   // Corrigir?
            "_IxqJMlqTEfG5K7mY0I3I6w",   // Existe Notificação?
            "_0XWahFqNEfG5K7mY0I3I6w",   // Trocar Notificação?
            "_CtQ7BFqPEfG5K7mY0I3I6w",   // Vistas do Juiz?
            "_CtQ7AlqPEfG5K7mY0I3I6w",   // Tipo de Vista Mista?
        };

        var declaredIds = decisions.Select(d => d.DecisaoId).ToHashSet();

        foreach (var expectedId in expectedDecisionIds)
        {
            Assert.True(declaredIds.Contains(expectedId),
                $"Ponto de decisão '{expectedId}' ausente na fixture {ReferenceScenarioId} — " +
                $"AC3: a omissão de uma decisão deve falhar com indicação explícita do nó.");
        }

        _output.WriteLine($"[ok] {decisions.Count} decisões presentes, todas verificadas.");
    }

    // =========================================================================
    // AC3 — 4 descidas declaradas na fixture
    // =========================================================================

    /// <summary>
    /// AC3 — A fixture declara exactamente 4 descidas (descidas=4).
    /// Se alguma descida for omitida, o teste falha com indicação explícita.
    /// Valores lidos do oracle — nunca escritos aqui.
    /// </summary>
    [Fact]
    public void ReferenceScenario_Descidas_Has4Entries()
    {
        var descidas = ReferenceScenario.Descidas ?? [];
        Assert.Equal(4, descidas.Count);

        var expectedDescidaPassoIds = new[]
        {
            "_0XWagVqNEfG5K7mY0I3I6w",   // Aguardar evento de Notificacao do AIIM → DEAT0050
            "_CI6lyFqREfG5K7mY0I3I6w",   // Prepara Intimação → PRPINTPC
            "_CtQ691qPEfG5K7mY0I3I6w",   // Busca Emails → BSCENVPC
            "_nQntZ16JEfGBBLgT-R5iuw",   // Controlar Intimados → CONTROPC
        };

        var declaredPassoIds = descidas.Select(d => d.PassoId).ToHashSet();

        foreach (var expectedId in expectedDescidaPassoIds)
        {
            Assert.True(declaredPassoIds.Contains(expectedId),
                $"Descida '{expectedId}' ausente na fixture {ReferenceScenarioId} — " +
                $"AC3: a omissão de uma descida deve falhar com indicação explícita do nó.");
        }

        _output.WriteLine($"[ok] {descidas.Count} descidas presentes, todas verificadas.");
    }

    // =========================================================================
    // AC3 — descida para BSCENVPC (Busca Emails, passo 29) declara cenários
    // =========================================================================

    /// <summary>
    /// AC3 — A descida para BSCENVPC (Busca Emails, passo 29) declara os
    /// cenários de sub-processo (SC-BSCENVPC-*) que cobrem nós NOEQ de BSCENVPC.
    /// </summary>
    [Fact]
    public void ReferenceScenario_DescidaBscenvpc_HasSubProcessCenarios()
    {
        var descidas = ReferenceScenario.Descidas ?? [];
        var descida = descidas.FirstOrDefault(d => d.PassoId == DescidaBscenvpcPassoId);

        Assert.NotNull(descida);
        Assert.Equal("BSCENVPC", descida.ContinuaEm);
        Assert.NotNull(descida.Cenarios);
        Assert.True(descida.Cenarios!.Count > 0,
            $"[NOEQ-non-interrupting-boundary] Descida BSCENVPC " +
            $"(id={DescidaBscenvpcPassoId}) não declara cenários de sub-processo.");

        _output.WriteLine(
            $"[ok] Descida BSCENVPC: {descida.Cenarios!.Count} cenário(s) declarados — " +
            "BSCENVPC verificado.");
    }

    // =========================================================================
    // AC3 — 2 inputs obrigatórios declarados na fixture
    // =========================================================================

    /// <summary>
    /// AC3 — A fixture declara exactamente 2 inputs obrigatórios.
    /// A ausência de qualquer um causa falha com identificação do input em falta.
    /// Valores lidos do oracle — nunca escritos aqui.
    /// </summary>
    [Fact]
    public void ReferenceScenario_InputsRequired_Has2Entries()
    {
        var inputs = ReferenceScenario.InputsRequired ?? [];
        Assert.Equal(2, inputs.Count);

        var expectedCampos = new[] { "CORRECAO", "TIPOVISTAS" };
        var declaredCampos = inputs.Select(i => i.Campo).ToHashSet();

        foreach (var campo in expectedCampos)
        {
            Assert.True(declaredCampos.Contains(campo),
                $"Input obrigatório '{campo}' ausente na fixture {ReferenceScenarioId} — " +
                $"AC3: a ausência deve causar falha imediata com identificação do input.");
        }

        _output.WriteLine($"[ok] {inputs.Count} inputs obrigatórios presentes: {string.Join(", ", declaredCampos)}.");
    }

    // =========================================================================
    // AC5 — nós NOEQ do processo principal presentes no path de referência
    // =========================================================================

    /// <summary>
    /// AC5 — Os nós NOEQ do processo principal (NOEQ-link-goto,
    /// NOEQ-non-interrupting-boundary) estão representados no percurso de
    /// referência com os IDs, tipos e mecanismos correctos.
    /// A ausência ou substituição silenciosa de qualquer um constitui falha.
    /// </summary>
    [Fact]
    public void ReferenceScenario_NoeqMainProcessNodes_PresentWithCorrectFieldsInPath()
    {
        var path = ReferenceScenario.Path!;
        var pathById = path.ToDictionary(n => n.Id, StringComparer.Ordinal);

        foreach (var (nodeId, (nome, tipo, entrouPor, noeqKind)) in NoeqMainProcessNodes)
        {
            Assert.True(pathById.ContainsKey(nodeId),
                $"[{noeqKind}] Nó NOEQ '{nome}' (id={nodeId}) ausente no path[] de " +
                $"{ReferenceScenarioId}. A ausência constitui falha de AC5.");

            var node = pathById[nodeId];
            Assert.Equal(tipo, node.Tipo);

            if (entrouPor is null)
                Assert.Null(node.EntrouPor);
            else
                Assert.Equal(entrouPor, node.EntrouPor, StringComparer.OrdinalIgnoreCase);

            _output.WriteLine(
                $"[ok] [{noeqKind}] '{nome}' (id={nodeId}, tipo={node.Tipo}, " +
                $"entrouPor={node.EntrouPor ?? "null"}) — explicitamente representado.");
        }
    }

    // =========================================================================
    // AC5 — cobertura NOEQ: sub-processos etapa 5 presentes nos 45 cenários
    // =========================================================================

    /// <summary>
    /// AC5 — Os cenários de sub-processos que cobrem nós NOEQ da etapa 5
    /// (BSCENVPC) estão declarados no index.
    /// A ausência do sub-processo NOEQ constitui falha explícita.
    /// </summary>
    [Fact]
    public void Etapa5_NoeqSubProcessScenarios_BscenvpcCovered()
    {
        var noeqProcesses = new[]
        {
            ("BSCENVPC", "NOEQ-non-interrupting-boundary"),
        };

        var byProcess = Etapa5Scenarios
            .GroupBy(s => s.Process)
            .ToDictionary(g => g.Key, g => g.Count());

        foreach (var (process, noeqKind) in noeqProcesses)
        {
            Assert.True(byProcess.TryGetValue(process, out var count) && count > 0,
                $"[{noeqKind}] Sub-processo '{process}' não tem cenários na etapa 5. " +
                $"AC5: a ausência ou substituição silenciosa constitui falha.");

            _output.WriteLine(
                $"[ok] [{noeqKind}] {process}: {count} cenário(s) na etapa 5.");
        }
    }

    // =========================================================================
    // AC3 — id, nome, tipo, escopo e entrouPor dos nós do percurso de referência
    //        estão presentes e não-nulos para os campos obrigatórios
    // =========================================================================

    [Fact]
    public void ReferenceScenario_AllPathNodes_HaveRequiredFields()
    {
        var path = ReferenceScenario.Path!;

        for (var i = 0; i < path.Count; i++)
        {
            var node = path[i];
            Assert.False(string.IsNullOrWhiteSpace(node.Id),
                $"path[{i}]: campo 'id' ausente.");
            Assert.False(string.IsNullOrWhiteSpace(node.Nome),
                $"path[{i}] (id={node.Id}): campo 'nome' ausente.");
            Assert.False(string.IsNullOrWhiteSpace(node.Tipo),
                $"path[{i}] (id={node.Id}): campo 'tipo' ausente.");
            Assert.False(string.IsNullOrWhiteSpace(node.Escopo),
                $"path[{i}] (id={node.Id}): campo 'escopo' ausente.");
            // entrouPor pode ser null (passo 1 — arranque)
        }

        _output.WriteLine(
            $"[ok] Todos os {path.Count} nós do percurso de referência têm " +
            $"id, nome, tipo e escopo preenchidos.");
    }

    // =========================================================================
    // AC6 — cada cenário tem rasto de nós (instance-trace evidence)
    // =========================================================================

    /// <summary>
    /// AC6 — Para cada um dos 45 cenários, o arquivo de detalhe existe e
    /// contém pelo menos um segmento com nós (rasto de instância não vazio).
    /// Rastreia: fulfills.evidenceKind='instance-trace'.
    /// </summary>
    [Theory]
    [MemberData(nameof(Etapa5ScenarioIds))]
    public void Etapa5_Scenario_HasAtLeastOneNodeInTrace(string scenarioId, string process)
    {
        var detail = ScenarioFixtureLoader.LoadScenario(scenarioId);

        Assert.NotNull(detail.Segmentos);
        Assert.NotEmpty(detail.Segmentos);

        var totalNodes = detail.Segmentos
            .SelectMany(s => s.Nos ?? [])
            .Count();

        Assert.True(totalNodes > 0,
            $"[{scenarioId}] Rasto de instância vazio — nenhum nó encontrado nos segmentos.");

        _output.WriteLine($"[ok] {scenarioId} ({process}): {totalNodes} nós no rasto.");
    }

    // =========================================================================
    // AC2 — rasto bate passo a passo com o percurso do cenário (fixture)
    //        Para cada cenário POC_EpatProcess da etapa 5:
    //          a) Cada nó nos segmentos de etapa 5 tem ID não vazio.
    //          b) Segmentos de etapa 5 estão ordenados por ordemNaJornada.
    //          c) Dentro de cada segmento, os nós aparecem na sequência declarada.
    //          d) Cada segmento tem pelo menos um nó.
    // =========================================================================

    [Theory]
    [MemberData(nameof(Etapa5PocEpatScenarioIds))]
    public void Etapa5_POCEpatProcess_Scenario_Etapa5Nodes_MatchReferenceOrderStepByStep(
        string scenarioId)
    {
        var detail = ScenarioFixtureLoader.LoadScenario(scenarioId);

        // Filtrar apenas segmentos que pertencem à etapa 5
        var etapa5Segments = (detail.Segmentos ?? [])
            .Where(s => s.Etapas != null && s.Etapas.Contains(5))
            .OrderBy(s => s.OrdemNaJornada)
            .ToList();

        Assert.True(etapa5Segments.Count > 0,
            $"[{scenarioId}] Nenhum segmento com etapas=[..5..] encontrado.");

        // (b) Segmentos ordenados por ordemNaJornada
        int prevOrdem = -1;
        foreach (var seg in etapa5Segments)
        {
            Assert.True(seg.OrdemNaJornada >= prevOrdem,
                $"[{scenarioId}] Segmento etapa 5 fora de ordem: " +
                $"ordemNaJornada={seg.OrdemNaJornada} < anterior={prevOrdem}.");
            prevOrdem = seg.OrdemNaJornada;

            // (d) Cada segmento tem pelo menos um nó
            Assert.True(seg.Nos is { Count: > 0 },
                $"[{scenarioId}] Segmento etapa 5 ordemNaJornada={seg.OrdemNaJornada} " +
                $"(doPasso={seg.DoPasso}) está vazio — rasto ausente.");

            // (a) Cada nó tem ID não vazio
            foreach (var no in seg.Nos!)
            {
                Assert.False(string.IsNullOrWhiteSpace(no.Id),
                    $"[{scenarioId}] Nó com id vazio no segmento doPasso={seg.DoPasso}.");
            }

            // (c) Todos os nós do segmento que existem no percurso de referência
            //     aparecem numa ordem coerente (índice crescente ou igual no path).
            //     Nós de sub-processo podem não estar no path principal — são aceites.
            int prevRefIdx = -1;
            foreach (var no in seg.Nos!)
            {
                if (!ReferenceNodeOrder.TryGetValue(no.Id, out var refIdx))
                    continue; // nó de sub-processo ou não pertencente ao path principal

                Assert.True(refIdx >= prevRefIdx,
                    $"[{scenarioId}] Nó '{no.Id}' (refIdx={refIdx}) fora de ordem " +
                    $"no segmento doPasso={seg.DoPasso} — desvio no passo {refIdx + 1}.");
                prevRefIdx = refIdx;
            }
        }

        var totalNodes = etapa5Segments.SelectMany(s => s.Nos!).Count();
        _output.WriteLine(
            $"[ok] {scenarioId}: {etapa5Segments.Count} segmento(s) de etapa 5, " +
            $"{totalNodes} nós — todos estruturalmente válidos.");
    }

    // =========================================================================
    // AC2 — cobertura total: os 14 nós do segmento etapa 5 são cobertos em
    //        conjunto pelos cenários POC_EpatProcess de etapa 5
    // =========================================================================

    [Fact]
    public void Etapa5_POCEpatProcess_Coverage_AllEtapa5ReferenceNodesVisitedAcrossScenarios()
    {
        var pocScenarios = Etapa5Scenarios
            .Where(s => s.Process == "POC_EpatProcess")
            .ToList();

        var coveredIds = new HashSet<string>(StringComparer.Ordinal);

        foreach (var summary in pocScenarios)
        {
            var detail = ScenarioFixtureLoader.LoadScenario(summary.Id);
            var etapa5Nodes = (detail.Segmentos ?? [])
                .Where(s => s.Etapas != null && s.Etapas.Contains(5))
                .SelectMany(s => s.Nos ?? [])
                .Select(n => n.Id)
                .Where(id => !string.IsNullOrWhiteSpace(id));

            foreach (var id in etapa5Nodes)
                coveredIds.Add(id!);
        }

        var missing = Etapa5ReferenceNodeIds
            .Where(id => !coveredIds.Contains(id))
            .ToList();

        if (missing.Count > 0)
        {
            var details = string.Join(", ", missing.Select(id =>
            {
                var idx = ReferenceNodeOrder.TryGetValue(id, out var i) ? i + 1 : -1;
                return $"passo {idx}: '{id}'";
            }));
            Assert.Fail(
                $"Os seguintes nós canónicos da etapa 5 não foram cobertos por nenhum cenário: {details}");
        }

        _output.WriteLine(
            $"[ok] Todos os {Etapa5ReferenceNodeIds.Count} nós de referência da etapa 5 " +
            $"são cobertos pelos {pocScenarios.Count} cenários POC_EpatProcess.");
    }

    // =========================================================================
    // AC1 — fixture permanece imutável
    // =========================================================================

    /// <summary>
    /// AC1 — Confirma que nenhum dos 39 cenários POC_EpatProcess de etapa 5
    /// tem o campo 'path' nulo ou vazio no ficheiro de detalhe
    /// (o rasto vem da fixture, não do arnes).
    /// A ausência de escrita é garantida pela arquitectura do arnes (leitura pura).
    /// </summary>
    [Theory]
    [MemberData(nameof(Etapa5PocEpatScenarioIds))]
    public void Etapa5_Scenario_FixtureIsReadOnly_PathFieldNotWrittenByHarness(string scenarioId)
    {
        var detail = ScenarioFixtureLoader.LoadScenario(scenarioId);

        var hasSomeTrace = (detail.Path is { Count: > 0 })
            || (detail.Segmentos is { Count: > 0 });

        Assert.True(hasSomeTrace,
            $"[{scenarioId}] Fixture sem rasto (path[] vazio e segmentos[] vazio) — " +
            "a fixture deve vir do kit, não ser escrita pelo arnes.");

        _output.WriteLine(
            $"[ok] {scenarioId}: fixture contém rasto — " +
            $"path={detail.Path?.Count ?? 0} nós, segmentos={detail.Segmentos?.Count ?? 0}.");
    }

    // =========================================================================
    // AC2 — sequência dos linkCatch (passos 22→23) bate com o path[] da fixture
    // =========================================================================

    /// <summary>
    /// AC2/AC5 — Confirma que o linkThrow 'Validar Paralelos' (passo 22) e o
    /// linkCatch 'Validação Paralelos' (passo 23) estão presentes consecutivamente
    /// no percurso de referência, na ordem correcta: passo 22 precede passo 23.
    ///
    /// Rastreia: passos 22→23 do path[], AC5 (linkCatch por linkThrow emparelhado).
    /// </summary>
    [Fact]
    public void ReferenceScenario_LinkThrowToLinkCatch_ValidarParalelos_IsInCorrectOrder()
    {
        var path = ReferenceScenario.Path!;

        const string linkThrowId = "_89MVQlqVEfG5K7mY0I3I6w";  // passo 22
        const string linkCatchId = "_Ei94AFqPEfG5K7mY0I3I6w";  // passo 23

        Assert.True(ReferenceNodeOrder.TryGetValue(linkThrowId, out var throwIdx),
            $"linkThrow '{linkThrowId}' ausente no path[] de {ReferenceScenarioId}.");
        Assert.True(ReferenceNodeOrder.TryGetValue(linkCatchId, out var catchIdx),
            $"linkCatch '{linkCatchId}' ausente no path[] de {ReferenceScenarioId}.");

        Assert.True(throwIdx < catchIdx,
            $"linkThrow (idx={throwIdx}) deve preceder linkCatch (idx={catchIdx}) " +
            $"no path[] de {ReferenceScenarioId}.");

        var throwNode = path[throwIdx];
        var catchNode = path[catchIdx];

        Assert.Equal("linkThrow", throwNode.Tipo);
        Assert.Equal("linkCatch", catchNode.Tipo);
        Assert.Equal("link", catchNode.EntrouPor, StringComparer.OrdinalIgnoreCase);

        _output.WriteLine(
            $"[ok] passo {throwIdx + 1}→{catchIdx + 1}: linkThrow '{throwNode.Nome}' " +
            $"→ linkCatch '{catchNode.Nome}' (entrouPor={catchNode.EntrouPor}) — ordem correcta.");
    }
}
