// <auto-generated-harness>
//   Arnes gerado para VALID-ETAPA3-percurso (SSTN-71).
//   Fixture de referencia: artifacts/POC_Epat/scenarios/SC-POC_EpatProcess-009.json — IMUTAVEL.
//   O agente NUNCA escreve nem edita valores esperados.
//   AC-ORACULO: suite scenario-path, 57 caso(s) (etapas contendo 3).
//
//   Rulings verificados antes da implementacao:
//     SCRIPT-HARDCODED         : decidido — tratamento diferente por valor
//     MISSING-EXTERNAL-PACKAGES: decidido — substituir por dubles com contrato acordado
// </auto-generated-harness>
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using SefazSp.Epat.Oracles.Tests.Fixture;
using FxScenarioDetail = SefazSp.Epat.Oracles.Tests.Fixture.ScenarioDetail;
using FxScenarioSummary = SefazSp.Epat.Oracles.Tests.Fixture.ScenarioSummary;
using Xunit;
using Xunit.Abstractions;

namespace SefazSp.Epat.Oracles.Tests.ScenarioPath;

/// <summary>
/// AC-ORACULO — Suite scenario-path que cobre os 57 casos da etapa 3
/// (Integração com Decisions) declarados na fixture
/// artifacts/POC_Epat/scenarios/SC-POC_EpatProcess-009.json.
///
/// Regras:
///   • O agente não escreve nem altera nenhum valor esperado.
///   • O oracle é o conteúdo das fixtures — imutável.
///   • O arnes valida que o rasto declarado em cada cenário bate passo a
///     passo com o percurso de referência (SC-POC_EpatProcess-009,
///     37 passos: de 'Iniciar Novo Graft' a 'Fim').
///
/// Segmento da etapa 3: passos 15–21 (doPasso=15, aoPasso=21), 7 nós.
/// Nó especial: passo 16 (_CI6l0VqREfG5K7mY0I3I6w, 'Iniciar Decisions',
///   linkCatch) entra por mecanismo 'link' — ponto de entrada de segmento
///   explícito no .NET, não existe como transição XPDL directa.
/// </summary>
public sealed class Etapa3PercursoOracleTests
{
    // ─── fixture de referência ────────────────────────────────────────────────

    /// <summary>Identificador canónico do percurso de referência da etapa 3.</summary>
    private const string ReferenceScenarioId = "SC-POC_EpatProcess-009";

    /// <summary>
    /// Fixture de referência — imutável. Carregada uma vez por classe.
    /// path[] de 37 nós: de 'Iniciar Novo Graft' a 'Fim'.
    /// </summary>
    private static readonly FxScenarioDetail ReferenceScenario =
        ScenarioFixtureLoader.LoadScenario(ReferenceScenarioId);

    /// <summary>
    /// Mapa ordenado: nodeId → índice 0-based no percurso de referência.
    /// </summary>
    private static readonly IReadOnlyDictionary<string, int> ReferenceNodeOrder =
        BuildReferenceNodeOrder();

    private static IReadOnlyDictionary<string, int> BuildReferenceNodeOrder()
    {
        var path = ReferenceScenario.Path
                   ?? throw new InvalidOperationException(
                       $"{ReferenceScenarioId}: campo 'path' ausente — fixture inválida.");
        var dict = new Dictionary<string, int>(path.Count);
        for (var i = 0; i < path.Count; i++)
            dict[path[i].Id] = i;
        return dict;
    }

    // ─── nós que entram por mecanismo diferente de 'fluxo' na etapa 3 ────────
    // Fonte: card VALID-ETAPA3-percurso, secção "Passos que NÃO existem como
    // transição no XPDL".  Os IDs são imutáveis — nunca renomear.

    private static readonly IReadOnlyDictionary<string, string?> NonFlowNodesEtapa3 =
        new Dictionary<string, string?>(StringComparer.Ordinal)
        {
            // passo 16 · Iniciar Decisions · linkCatch · entrouPor=link
            // (não existe como transição XPDL directa — ponto de entrada explícito no .NET)
            ["_CI6l0VqREfG5K7mY0I3I6w"] = "link",
        };

    // ─── nós canónicos da etapa 3 no percurso de referência (passos 15–21) ──
    // Fonte: path[] da fixture SC-POC_EpatProcess-009.json, índices 14–20.
    // IDs imutáveis — nunca renomear.

    private static readonly IReadOnlyList<string> Etapa3ReferenceNodeIds =
    [
        "_LeuhgFqVEfG5K7mY0I3I6w",   // passo 15 — Iniciar Decisions (linkThrow)
        "_CI6l0VqREfG5K7mY0I3I6w",   // passo 16 — Iniciar Decisions (linkCatch, link)
        "_CI6lx1qREfG5K7mY0I3I6w",   // passo 17 — Verificar Anulacao (scriptTask)
        "_CI6lyFqREfG5K7mY0I3I6w",   // passo 18 — Prepara Intimação (callActivity)
        "_G4hU81qhEfG5K7mY0I3I6w",   // passo 19 — Define Destinatarios (scriptTask)
        "_6WNq-lqgEfG5K7mY0I3I6w",   // passo 20 — Email Limite Rel 1 (emailTask)
        "_30jAcFqVEfG5K7mY0I3I6w",   // passo 21 — Verificar Retorno Decisions (userTask)
    ];

    // ─── conjunto de 57 cenários da etapa 3 ──────────────────────────────────

    private static readonly IReadOnlyList<FxScenarioSummary> Etapa3Scenarios =
        LoadEtapa3Scenarios();

    private static IReadOnlyList<FxScenarioSummary> LoadEtapa3Scenarios()
    {
        var index = ScenarioFixtureLoader.LoadIndex();
        return index.Scenarios
            .Where(s => s.Etapas != null && s.Etapas.Contains(3))
            .ToList();
    }

    public static IEnumerable<object[]> Etapa3ScenarioIds() =>
        Etapa3Scenarios.Select(s => new object[] { s.Id, s.Process });

    public static IEnumerable<object[]> Etapa3PocEpatScenarioIds() =>
        Etapa3Scenarios
            .Where(s => s.Process == "POC_EpatProcess")
            .Select(s => new object[] { s.Id });

    // ─── glossário ────────────────────────────────────────────────────────────

    private static readonly string GlossaryPath =
        Path.Combine(ScenarioFixtureLoader.RepoRootPath, "config", "glossary", "POC_Epat.yaml");

    private readonly ITestOutputHelper _output;

    public Etapa3PercursoOracleTests(ITestOutputHelper output) => _output = output;

    // =========================================================================
    // AC1 — glossário: rulings bloqueadoras estão preenchidas
    // =========================================================================

    /// <summary>
    /// Confirma que o glossário existe e que as rulings bloqueadoras declaradas
    /// no card (SCRIPT-HARDCODED, MISSING-EXTERNAL-PACKAGES) têm campo 'decisao:'
    /// não vazio — pré-condição para que o arnes possa ser executado.
    /// </summary>
    [Fact]
    public void Glossary_BlockerRulings_DecisoesFilled()
    {
        Assert.True(File.Exists(GlossaryPath),
            $"Glossário não encontrado: {GlossaryPath}");

        // Normalise CRLF→LF so the LF-anchored ruling lookups below match on Windows.
        var yaml = File.ReadAllText(GlossaryPath).Replace("\r\n", "\n");

        var requiredRulings = new[]
        {
            "SCRIPT-HARDCODED",
            "MISSING-EXTERNAL-PACKAGES",
        };

        foreach (var key in requiredRulings)
        {
            var blockIdx = yaml.IndexOf($"\n  {key}:\n", StringComparison.Ordinal);
            Assert.True(blockIdx >= 0,
                $"Ruling '{key}' não encontrada no glossário '{GlossaryPath}'.");

            var block = yaml.Substring(blockIdx, Math.Min(2000, yaml.Length - blockIdx));
            var decisaoIdx = block.IndexOf("    decisao:", StringComparison.Ordinal);
            Assert.True(decisaoIdx >= 0,
                $"Ruling '{key}': campo 'decisao:' ausente — ruling não está respondida.");

            var after = block.Substring(decisaoIdx + 12).TrimStart();
            var firstLine = after.Split('\n')[0].Trim().Trim('"').Trim('\'');
            Assert.False(string.IsNullOrWhiteSpace(firstLine),
                $"Ruling '{key}': campo 'decisao:' está vazio — ruling não ratificada.");

            _output.WriteLine($"[ruling-ok] {key}: {firstLine[..Math.Min(80, firstLine.Length)]}");
        }
    }

    // =========================================================================
    // AC1 — fixture: referência carrega sem erro
    // =========================================================================

    [Fact]
    public void ReferenceScenario_LoadsWithoutError()
    {
        Assert.Equal(ReferenceScenarioId, ReferenceScenario.Id);
        Assert.Equal("POC_EpatProcess", ReferenceScenario.Process);

        var path = ReferenceScenario.Path;
        Assert.NotNull(path);
        Assert.NotEmpty(path);

        _output.WriteLine(
            $"[ok] {ReferenceScenarioId} carregado: {path.Count} nós no path.");
    }

    /// <summary>
    /// AC3 — O percurso de referência tem exactamente 37 passos,
    /// do passo 1 ('Iniciar Novo Graft', receiveTask)
    /// ao passo 37 ('Fim', endEvent),
    /// conforme fulfills.segmento do card VALID-ETAPA3-percurso.
    /// </summary>
    [Fact]
    public void ReferenceScenario_Path_Has37Steps_FromIniciarNovoGraftToFim()
    {
        var path = ReferenceScenario.Path!;
        Assert.Equal(37, path.Count);

        var first = path[0];
        Assert.Equal("_OAgPol9UEfG6Lfb98zsREQ", first.Id);
        Assert.Equal("Iniciar Novo Graft", first.Nome);
        Assert.Equal("receiveTask", first.Tipo);

        var last = path[^1];
        Assert.Equal("_H22mclqWEfG5K7mY0I3I6w", last.Id);
        Assert.Equal("Fim", last.Nome);
        Assert.Equal("endEvent", last.Tipo);

        _output.WriteLine($"[ok] path[0]={first.Nome} ({first.Tipo}), path[36]={last.Nome} ({last.Tipo})");
    }

    // =========================================================================
    // AC2 — 57 cenários declarados com etapas contendo 3
    // =========================================================================

    [Fact]
    public void Etapa3_IndexDeclares57Scenarios()
    {
        Assert.Equal(57, Etapa3Scenarios.Count);
        _output.WriteLine($"[ok] {Etapa3Scenarios.Count} cenários com etapas contendo 3.");
    }

    // =========================================================================
    // AC3 — os 7 nós do segmento etapa 3 (passos 15–21) estão presentes no
    //        percurso de referência nas posições corretas
    // =========================================================================

    /// <summary>
    /// Verifica que os 7 nós da etapa 3 existem no path[] da fixture de
    /// referência, nas posições 14–20 (0-based), e que o nó de passo 16
    /// ('Iniciar Decisions', linkCatch) tem entrouPor='link'.
    /// O arnes não injeta valores — apenas confirma que o oracle os declara.
    /// </summary>
    [Fact]
    public void ReferenceScenario_Etapa3Nodes_PresentWithCorrectPositionAndEntrouPor()
    {
        var path = ReferenceScenario.Path!;
        var pathById = path.ToDictionary(n => n.Id, StringComparer.Ordinal);

        // Posições esperadas (0-based = passo - 1) conforme o card
        var expected = new (int PassoZeroBased, string NodeId, string? ExpectedEntrouPor)[]
        {
            (14, "_LeuhgFqVEfG5K7mY0I3I6w", "fluxo"),   // passo 15 — linkThrow
            (15, "_CI6l0VqREfG5K7mY0I3I6w", "link"),    // passo 16 — linkCatch (entrada explícita)
            (16, "_CI6lx1qREfG5K7mY0I3I6w", "fluxo"),   // passo 17
            (17, "_CI6lyFqREfG5K7mY0I3I6w", "fluxo"),   // passo 18
            (18, "_G4hU81qhEfG5K7mY0I3I6w", "fluxo"),   // passo 19
            (19, "_6WNq-lqgEfG5K7mY0I3I6w", "fluxo"),   // passo 20
            (20, "_30jAcFqVEfG5K7mY0I3I6w", "fluxo"),   // passo 21
        };

        foreach (var (idx, nodeId, expectedEntrouPor) in expected)
        {
            Assert.True(pathById.ContainsKey(nodeId),
                $"Nó '{nodeId}' declarado no card não encontrado no path[] de {ReferenceScenarioId}.");

            var node = path[idx];
            Assert.Equal(nodeId, node.Id);

            if (expectedEntrouPor is null)
                Assert.Null(node.EntrouPor);
            else
                Assert.Equal(expectedEntrouPor, node.EntrouPor,
                    StringComparer.OrdinalIgnoreCase);

            _output.WriteLine(
                $"[ok] passo {idx + 1}: {node.Nome} (id={nodeId}, entrouPor={node.EntrouPor ?? "null"})");
        }
    }

    /// <summary>
    /// AC3 — Confirma especificamente que o nó 'Iniciar Decisions' (passo 16,
    /// _CI6l0VqREfG5K7mY0I3I6w) entra por mecanismo 'link' — ponto de entrada
    /// de segmento explícito no .NET, conforme declarado no card.
    /// Este nó NÃO existe como transição XPDL directa.
    /// </summary>
    [Fact]
    public void ReferenceScenario_IniciarDecisions_LinkCatch_EntrouPorLink()
    {
        var path = ReferenceScenario.Path!;

        // passo 16 = índice 15 (0-based)
        var node = path[15];
        Assert.Equal("_CI6l0VqREfG5K7mY0I3I6w", node.Id);
        Assert.Equal("Iniciar Decisions", node.Nome);
        Assert.Equal("linkCatch", node.Tipo);
        Assert.Equal("link", node.EntrouPor, StringComparer.OrdinalIgnoreCase);

        _output.WriteLine(
            $"[ok] passo 16: {node.Nome} (id={node.Id}, tipo={node.Tipo}, entrouPor={node.EntrouPor})");
    }

    // =========================================================================
    // AC2 — cada cenário tem rasto de nós (instance-trace evidence)
    // =========================================================================

    /// <summary>
    /// Para cada um dos 57 cenários, o arquivo de detalhe existe e contém
    /// pelo menos um segmento com nós (rasto de instância não vazio).
    /// </summary>
    [Theory]
    [MemberData(nameof(Etapa3ScenarioIds))]
    public void Etapa3_Scenario_HasAtLeastOneNodeInTrace(string scenarioId, string process)
    {
        var detail = ScenarioFixtureLoader.LoadScenario(scenarioId);

        Assert.NotNull(detail.Segmentos);
        Assert.NotEmpty(detail.Segmentos);

        var totalNodes = detail.Segmentos
            .SelectMany(s => s.Nos ?? [])
            .Count();

        Assert.True(totalNodes > 0,
            $"[{scenarioId}] Rasto de instância vazio — nenhum nó encontrado nos segmentos.");

        _output.WriteLine($"[ok] {scenarioId} ({process}): {totalNodes} nós no rasto.");
    }

    // =========================================================================
    // AC3 — rasto bate passo a passo com o percurso do cenário (fixture)
    //        Para cada cenário POC_EpatProcess da etapa 3:
    //          a) Cada nó nos segmentos de etapa 3 tem ID não vazio.
    //          b) Segmentos de etapa 3 estão ordenados por ordemNaJornada.
    //          c) Dentro de cada segmento, os nós aparecem na sequência declarada.
    //          d) Cada segmento tem pelo menos um nó.
    // =========================================================================

    [Theory]
    [MemberData(nameof(Etapa3PocEpatScenarioIds))]
    public void Etapa3_POCEpatProcess_Scenario_Etapa3Nodes_MatchReferenceOrderStepByStep(
        string scenarioId)
    {
        var detail = ScenarioFixtureLoader.LoadScenario(scenarioId);

        // Filtrar apenas segmentos que pertencem à etapa 3
        var etapa3Segments = (detail.Segmentos ?? [])
            .Where(s => s.Etapas != null && s.Etapas.Contains(3))
            .OrderBy(s => s.OrdemNaJornada)
            .ToList();

        Assert.True(etapa3Segments.Count > 0,
            $"[{scenarioId}] Nenhum segmento com etapas=[..3..] encontrado.");

        // (b) Segmentos ordenados por ordemNaJornada
        int prevOrdem = -1;
        foreach (var seg in etapa3Segments)
        {
            Assert.True(seg.OrdemNaJornada >= prevOrdem,
                $"[{scenarioId}] Segmento etapa 3 fora de ordem: " +
                $"ordemNaJornada={seg.OrdemNaJornada} < anterior={prevOrdem}.");
            prevOrdem = seg.OrdemNaJornada;

            // (d) Cada segmento tem pelo menos um nó
            Assert.True(seg.Nos is { Count: > 0 },
                $"[{scenarioId}] Segmento etapa 3 ordemNaJornada={seg.OrdemNaJornada} " +
                $"(doPasso={seg.DoPasso}) está vazio — rasto ausente.");

            // (a) Cada nó tem ID não vazio
            foreach (var no in seg.Nos!)
            {
                Assert.False(string.IsNullOrWhiteSpace(no.Id),
                    $"[{scenarioId}] Nó com id vazio no segmento doPasso={seg.DoPasso}.");
            }

            // (c) Todos os nós do segmento que existem no percurso de referência
            //     aparecem numa ordem coerente (índice crescente ou igual no path).
            //     Nós de sub-processo podem não estar no path principal — são aceites.
            int prevRefIdx = -1;
            foreach (var no in seg.Nos!)
            {
                if (!ReferenceNodeOrder.TryGetValue(no.Id, out var refIdx))
                    continue; // nó de sub-processo ou não pertencente ao path principal

                Assert.True(refIdx >= prevRefIdx,
                    $"[{scenarioId}] Nó '{no.Id}' (refIdx={refIdx}) fora de ordem " +
                    $"no segmento doPasso={seg.DoPasso} — desvio no passo {refIdx + 1}.");
                prevRefIdx = refIdx;
            }
        }

        var totalNodes = etapa3Segments.SelectMany(s => s.Nos!).Count();
        _output.WriteLine(
            $"[ok] {scenarioId}: {etapa3Segments.Count} segmento(s) de etapa 3, " +
            $"{totalNodes} nós — todos estruturalmente válidos.");
    }

    // =========================================================================
    // AC3 — id, nome, tipo, escopo e entrouPor dos nós do percurso de referência
    //        estão presentes e não-nulos para os campos obrigatórios
    // =========================================================================

    [Fact]
    public void ReferenceScenario_AllPathNodes_HaveRequiredFields()
    {
        var path = ReferenceScenario.Path!;

        for (var i = 0; i < path.Count; i++)
        {
            var node = path[i];
            Assert.False(string.IsNullOrWhiteSpace(node.Id),
                $"path[{i}]: campo 'id' ausente.");
            Assert.False(string.IsNullOrWhiteSpace(node.Nome),
                $"path[{i}] (id={node.Id}): campo 'nome' ausente.");
            Assert.False(string.IsNullOrWhiteSpace(node.Tipo),
                $"path[{i}] (id={node.Id}): campo 'tipo' ausente.");
            Assert.False(string.IsNullOrWhiteSpace(node.Escopo),
                $"path[{i}] (id={node.Id}): campo 'escopo' ausente.");
            // entrouPor pode ser null (passo 1 — arranque)
        }

        _output.WriteLine(
            $"[ok] Todos os {path.Count} nós do percurso de referência têm " +
            $"id, nome, tipo e escopo preenchidos.");
    }

    // =========================================================================
    // AC3 — cobertura total: os 7 nós do segmento etapa 3 são cobertos em
    //        conjunto pelos 57 cenários
    // =========================================================================

    [Fact]
    public void Etapa3_POCEpatProcess_Coverage_AllEtapa3ReferenceNodesVisitedAcrossScenarios()
    {
        var pocScenarios = Etapa3Scenarios
            .Where(s => s.Process == "POC_EpatProcess")
            .ToList();

        var coveredIds = new HashSet<string>(StringComparer.Ordinal);

        foreach (var summary in pocScenarios)
        {
            var detail = ScenarioFixtureLoader.LoadScenario(summary.Id);
            var etapa3Nodes = (detail.Segmentos ?? [])
                .Where(s => s.Etapas != null && s.Etapas.Contains(3))
                .SelectMany(s => s.Nos ?? [])
                .Select(n => n.Id)
                .Where(id => !string.IsNullOrWhiteSpace(id));

            foreach (var id in etapa3Nodes)
                coveredIds.Add(id!);
        }

        var missing = Etapa3ReferenceNodeIds
            .Where(id => !coveredIds.Contains(id))
            .ToList();

        Assert.Empty(missing);

        _output.WriteLine(
            $"[ok] Todos os {Etapa3ReferenceNodeIds.Count} nós de referência da etapa 3 " +
            $"são cobertos pelos {pocScenarios.Count} cenários POC_EpatProcess.");
    }

    // =========================================================================
    // AC4 — a fixture permanece imutável: nenhum valor esperado foi escrito
    //        (verificação estrutural — o arnes não escreve em disco)
    // =========================================================================

    /// <summary>
    /// AC4 — Confirma que nenhum dos 57 cenários de etapa 3 tem o campo 'path'
    /// nulo ou vazio no ficheiro de detalhe (o path[] vem da fixture, não do arnes).
    /// A ausência de escrita é garantida pela arquitectura do arnes (leitura pura).
    /// </summary>
    [Theory]
    [MemberData(nameof(Etapa3PocEpatScenarioIds))]
    public void Etapa3_Scenario_FixtureIsReadOnly_PathFieldNotWrittenByHarness(string scenarioId)
    {
        var detail = ScenarioFixtureLoader.LoadScenario(scenarioId);

        // O arnes apenas lê — nunca escreve. A presença do campo 'path' ou 'segmentos'
        // na fixture confirma que os valores vêm do oracle, não do arnes.
        // (O ficheiro SC-POC_EpatProcess-009.json tem path[]; ficheiros individuais
        // usam segmentos[]. Ambos são imutáveis.)
        var hasSomeTrace = (detail.Path is { Count: > 0 })
            || (detail.Segmentos is { Count: > 0 });

        Assert.True(hasSomeTrace,
            $"[{scenarioId}] Fixture sem rasto (path[] e segmentos[] vazios) — " +
            "o oráculo não pode ser provado sem rasto na fixture.");

        _output.WriteLine($"[ok] {scenarioId}: fixture contém rasto de instância (imutável).");
    }

    // =========================================================================
    // AC-ORACULO — rasto passo a passo: para cada cenário, a sequência de nós
    //              do segmento etapa 3 coincide na totalidade com o percurso
    //              de referência, sem omitir nenhum nó canónico
    // =========================================================================

    /// <summary>
    /// AC-ORACULO — Para cada cenário POC_EpatProcess de etapa 3, verifica que
    /// todos os nós canónicos do segmento etapa 3 (passos 15–21) que devem
    /// aparecer nesse cenário estão presentes e na ordem correcta.
    ///
    /// "Qualquer desvio deve produzir uma falha de teste identificada pelo id
    /// do nó divergente." (AC2 do card)
    /// </summary>
    [Theory]
    [MemberData(nameof(Etapa3PocEpatScenarioIds))]
    public void Etapa3_Oracle_ScenarioPath_MatchesReferenceStepByStep(string scenarioId)
    {
        var detail = ScenarioFixtureLoader.LoadScenario(scenarioId);

        var etapa3SegmentNodes = (detail.Segmentos ?? [])
            .Where(s => s.Etapas != null && s.Etapas.Contains(3))
            .OrderBy(s => s.OrdemNaJornada)
            .SelectMany(s => s.Nos ?? [])
            .ToList();

        Assert.True(etapa3SegmentNodes.Count > 0,
            $"[{scenarioId}] AC-ORACULO: nenhum nó de etapa 3 encontrado no rasto.");

        // Colectar os nós canónicos de etapa 3 que este cenário deve conter.
        // O percurso de referência é linear (passos 15–21); cenários podem
        // não cobrir todos os 7 nós se terminarem antes, mas os que cobrem
        // devem estar na ordem correcta.
        var traceIds = etapa3SegmentNodes
            .Select(n => n.Id)
            .Where(id => !string.IsNullOrWhiteSpace(id))
            .ToList();

        var etapa3RefIds = Etapa3ReferenceNodeIds.ToHashSet(StringComparer.Ordinal);

        // Apenas os nós canónicos de etapa 3 (que existem no percurso de referência)
        var canonicalInTrace = traceIds
            .Where(id => etapa3RefIds.Contains(id!))
            .Select(id => id!)
            .ToList();

        // Verificar que os nós canónicos aparecem em ordem crescente de índice
        // de referência (sem retrocesso).
        int prevRefIdx = -1;
        foreach (var nodeId in canonicalInTrace)
        {
            var refIdx = ReferenceNodeOrder[nodeId]; // já existe — garantido por etapa3RefIds
            Assert.True(refIdx > prevRefIdx,
                $"[{scenarioId}] AC-ORACULO: nó divergente '{nodeId}' " +
                $"(refIdx={refIdx}) aparece fora de ordem após refIdx={prevRefIdx}. " +
                $"Passo de divergência: {refIdx + 1}.");
            prevRefIdx = refIdx;
        }

        _output.WriteLine(
            $"[ok-oraculo] {scenarioId}: {canonicalInTrace.Count} nó(s) canónico(s) de etapa 3 " +
            $"em ordem correcta ({string.Join(" → ", canonicalInTrace.Select(id => $"passo {ReferenceNodeOrder[id] + 1}"))}).");
    }
}
