// <auto-generated-harness>
//   Arnes gerado para VALID-ETAPA4-percurso (SSTN-72).
//   Fixture de referencia: artifacts/POC_Epat/scenarios/SC-POC_EpatProcess-009.json — IMUTAVEL.
//   O agente NUNCA escreve nem edita valores esperados.
//   AC-ORACULO: suite scenario-path, 79 caso(s) (etapas contendo 4).
//
//   Rulings verificados antes da implementacao:
//     BUILTIN-SEMANTICS: decidido — semantica confirmada para migracao
//     CLONE-PRPINTPC   : decidido — corrigir para STATUS_CODE != '0'
//     LABEL-CONFLICT   : decidido — nomear por deducao
//     SCRIPT-HARDCODED : decidido — tratamento diferente por valor
// </auto-generated-harness>
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using SefazSp.Epat.Oracles.Tests.Fixture;
using FxScenarioDetail = SefazSp.Epat.Oracles.Tests.Fixture.ScenarioDetail;
using FxScenarioSummary = SefazSp.Epat.Oracles.Tests.Fixture.ScenarioSummary;
using Xunit;
using Xunit.Abstractions;

namespace SefazSp.Epat.Oracles.Tests.ScenarioPath;

/// <summary>
/// AC-ORACULO — Suite scenario-path que cobre os 79 casos da etapa 4
/// (Verificação do Retorno do Decisions) declarados na fixture
/// artifacts/POC_Epat/scenarios/SC-POC_EpatProcess-009.json.
///
/// Regras:
///   • O agente não escreve nem altera nenhum valor esperado.
///   • O oracle é o conteúdo das fixtures — imutável.
///   • O arnes valida que o rasto declarado em cada cenário bate passo a
///     passo com o percurso de referência (SC-POC_EpatProcess-009,
///     37 passos: de 'Iniciar Novo Graft' a 'Fim').
///
/// Segmento da etapa 4: passos 15–21 (doPasso=15, aoPasso=21), 7 nós.
///
/// Nós NOEQ do processo principal (escritos explicitamente no arnes .NET):
///   • passo 16 (_CI6l0VqREfG5K7mY0I3I6w, 'Iniciar Decisions', linkCatch,
///     entrouPor=link)      — NOEQ-link-goto: POC_EpatProcess/Iniciar Decisions.
///   • passo 17 (_CI6lx1qREfG5K7mY0I3I6w, 'Verificar Anulacao', scriptTask)
///     — NOEQ-iprocess-builtin.
///   • passo 19 (_G4hU81qhEfG5K7mY0I3I6w, 'Define Destinatarios', scriptTask)
///     — NOEQ-iprocess-builtin.
///
/// Nós NOEQ em sub-processos (representados via descidas declaradas na fixture):
///   • NOEQ-dynamic-subprocess : CONTROPC/Aguardar Retorno
///     → descida 'Controlar Intimados' (id=_nQntZ16JEfGBBLgT-R5iuw, dynamic=true)
///   • NOEQ-external-event     : AGPECASPC/Aguardar Interposicoes
///     → cenários SC-AGPECASPC-* cobertos pela descida 'Controlar Intimados' (via CONTROPC)
///   • NOEQ-link-goto          : ATZINTPC/Link To: Try Task, ATZINTPC/Try Task,
///                               PRPINTPC/Link To: Try Task, PRPINTPC/Try Task
///     → descida 'Prepara Intimação' (id=_CI6lyFqREfG5K7mY0I3I6w, continuaEm=PRPINTPC)
///   • NOEQ-iprocess-builtin   : AGPECASPC/Set Values, ATZINTPC/SetParameters,
///                               ATZINTPC/Start Loop, CONTROPC/ISetSubProc,
///                               PRPINTPC/SetParameters, PRPINTPC/Start Loop
///     → representados nos 40 cenários SC-ATZINTPC-*, SC-PRPINTPC-*,
///       SC-AGPECASPC-* e SC-CONTROPC-* da etapa 4.
/// </summary>
public sealed class Etapa4PercursoOracleTests
{
    // ─── fixture de referência ────────────────────────────────────────────────

    /// <summary>Identificador canónico do percurso de referência da etapa 4.</summary>
    private const string ReferenceScenarioId = "SC-POC_EpatProcess-009";

    /// <summary>
    /// Fixture de referência — imutável. Carregada uma vez por classe.
    /// path[] de 37 nós: de 'Iniciar Novo Graft' a 'Fim'.
    /// </summary>
    private static readonly FxScenarioDetail ReferenceScenario =
        ScenarioFixtureLoader.LoadScenario(ReferenceScenarioId);

    /// <summary>
    /// Mapa ordenado: nodeId → índice 0-based no percurso de referência.
    /// </summary>
    private static readonly IReadOnlyDictionary<string, int> ReferenceNodeOrder =
        BuildReferenceNodeOrder();

    private static IReadOnlyDictionary<string, int> BuildReferenceNodeOrder()
    {
        var path = ReferenceScenario.Path
                   ?? throw new InvalidOperationException(
                       $"{ReferenceScenarioId}: campo 'path' ausente — fixture inválida.");
        var dict = new Dictionary<string, int>(path.Count);
        for (var i = 0; i < path.Count; i++)
            dict[path[i].Id] = i;
        return dict;
    }

    // ─── nós NOEQ do processo principal (AC5) ────────────────────────────────
    // Fonte: card VALID-ETAPA4-percurso, secção "Passos que NÃO existem como
    // transição no XPDL".  Os IDs são imutáveis — nunca renomear.

    private static readonly IReadOnlyDictionary<string, (string Nome, string Tipo, string? EntrouPor, string NoeqKind)>
        NoeqMainProcessNodes =
        new Dictionary<string, (string, string, string?, string)>(StringComparer.Ordinal)
        {
            // passo 16 · Iniciar Decisions · linkCatch · entrouPor=link
            // NOEQ-link-goto: não existe como transição XPDL directa.
            ["_CI6l0VqREfG5K7mY0I3I6w"] = ("Iniciar Decisions",   "linkCatch",   "link",  "NOEQ-link-goto"),
            // passo 17 · Verificar Anulacao · scriptTask · entrouPor=fluxo
            // NOEQ-iprocess-builtin: iProcess builtin sem equivalente .NET directo.
            ["_CI6lx1qREfG5K7mY0I3I6w"] = ("Verificar Anulacao",  "scriptTask",  "fluxo", "NOEQ-iprocess-builtin"),
            // passo 19 · Define Destinatarios · scriptTask · entrouPor=fluxo
            // NOEQ-iprocess-builtin: iProcess builtin sem equivalente .NET directo.
            ["_G4hU81qhEfG5K7mY0I3I6w"] = ("Define Destinatarios","scriptTask",  "fluxo", "NOEQ-iprocess-builtin"),
        };

    // ─── nós canónicos da etapa 4 no percurso de referência (passos 15–21) ──
    // Fonte: path[] da fixture SC-POC_EpatProcess-009.json, índices 14–20.
    // IDs imutáveis — nunca renomear.

    private static readonly IReadOnlyList<string> Etapa4ReferenceNodeIds =
    [
        "_LeuhgFqVEfG5K7mY0I3I6w",   // passo 15 — Iniciar Decisions (linkThrow)
        "_CI6l0VqREfG5K7mY0I3I6w",   // passo 16 — Iniciar Decisions (linkCatch, link) NOEQ-link-goto
        "_CI6lx1qREfG5K7mY0I3I6w",   // passo 17 — Verificar Anulacao (scriptTask) NOEQ-iprocess-builtin
        "_CI6lyFqREfG5K7mY0I3I6w",   // passo 18 — Prepara Intimação (callActivity)
        "_G4hU81qhEfG5K7mY0I3I6w",   // passo 19 — Define Destinatarios (scriptTask) NOEQ-iprocess-builtin
        "_6WNq-lqgEfG5K7mY0I3I6w",   // passo 20 — Email Limite Rel 1 (emailTask)
        "_30jAcFqVEfG5K7mY0I3I6w",   // passo 21 — Verificar Retorno Decisions (userTask)
    ];

    // ─── IDs das descidas que representam nós NOEQ de sub-processos ──────────
    // Fonte: fixture SC-POC_EpatProcess-009.json, campo descidas[].
    // Estas descidas representam os nós NOEQ que não aparecem no path principal.

    /// <summary>
    /// Descida para PRPINTPC (Prepara Intimação) — cobre NOEQ-link-goto e
    /// NOEQ-iprocess-builtin dos pacotes ATZINTPC e PRPINTPC.
    /// </summary>
    private const string DescidaPrpintpcPassoId = "_CI6lyFqREfG5K7mY0I3I6w";

    /// <summary>
    /// Descida para CONTROPC (Controlar Intimados) — cobre NOEQ-dynamic-subprocess
    /// (CONTROPC/Aguardar Retorno) e transitivamente NOEQ-external-event
    /// (AGPECASPC/Aguardar Interposicoes) e NOEQ-iprocess-builtin de CONTROPC.
    /// </summary>
    private const string DescidaContropcPassoId = "_nQntZ16JEfGBBLgT-R5iuw";

    // ─── conjunto de 79 cenários da etapa 4 ──────────────────────────────────

    private static readonly IReadOnlyList<FxScenarioSummary> Etapa4Scenarios =
        LoadEtapa4Scenarios();

    private static IReadOnlyList<FxScenarioSummary> LoadEtapa4Scenarios()
    {
        var index = ScenarioFixtureLoader.LoadIndex();
        return index.Scenarios
            .Where(s => s.Etapas != null && s.Etapas.Contains(4))
            .ToList();
    }

    public static IEnumerable<object[]> Etapa4ScenarioIds() =>
        Etapa4Scenarios.Select(s => new object[] { s.Id, s.Process });

    public static IEnumerable<object[]> Etapa4PocEpatScenarioIds() =>
        Etapa4Scenarios
            .Where(s => s.Process == "POC_EpatProcess")
            .Select(s => new object[] { s.Id });

    // ─── glossário ────────────────────────────────────────────────────────────

    private static readonly string GlossaryPath =
        Path.Combine(ScenarioFixtureLoader.RepoRootPath, "config", "glossary", "POC_Epat.yaml");

    private readonly ITestOutputHelper _output;

    public Etapa4PercursoOracleTests(ITestOutputHelper output) => _output = output;

    // =========================================================================
    // AC1 — glossário: rulings bloqueadoras estão preenchidas
    // =========================================================================

    /// <summary>
    /// Confirma que o glossário existe e que as quatro rulings bloqueadoras
    /// declaradas no card (BUILTIN-SEMANTICS, CLONE-PRPINTPC, LABEL-CONFLICT,
    /// SCRIPT-HARDCODED) têm campo 'decisao:' não vazio —
    /// pré-condição para que o arnes possa ser executado.
    /// </summary>
    [Fact]
    public void Glossary_BlockerRulings_AllFourDecisoesFilled()
    {
        Assert.True(File.Exists(GlossaryPath),
            $"Glossário não encontrado: {GlossaryPath}");

        var yaml = File.ReadAllText(GlossaryPath);

        var requiredRulings = new[]
        {
            "BUILTIN-SEMANTICS",
            "CLONE-PRPINTPC",
            "LABEL-CONFLICT",
            "SCRIPT-HARDCODED",
        };

        foreach (var key in requiredRulings)
        {
            var blockIdx = yaml.IndexOf($"\n  {key}:\n", StringComparison.Ordinal);
            Assert.True(blockIdx >= 0,
                $"Ruling '{key}' não encontrada no glossário '{GlossaryPath}'.");

            var block = yaml.Substring(blockIdx, Math.Min(2000, yaml.Length - blockIdx));
            var decisaoIdx = block.IndexOf("    decisao:", StringComparison.Ordinal);
            Assert.True(decisaoIdx >= 0,
                $"Ruling '{key}': campo 'decisao:' ausente — ruling não está respondida.");

            var after = block.Substring(decisaoIdx + 12).TrimStart();
            var firstLine = after.Split('\n')[0].Trim().Trim('"').Trim('\'');
            Assert.False(string.IsNullOrWhiteSpace(firstLine),
                $"Ruling '{key}': campo 'decisao:' está vazio — ruling não ratificada.");

            _output.WriteLine($"[ruling-ok] {key}: {firstLine[..Math.Min(80, firstLine.Length)]}");
        }
    }

    // =========================================================================
    // AC1 — fixture: referência carrega sem erro
    // =========================================================================

    [Fact]
    public void ReferenceScenario_LoadsWithoutError()
    {
        Assert.Equal(ReferenceScenarioId, ReferenceScenario.Id);
        Assert.Equal("POC_EpatProcess", ReferenceScenario.Process);

        var path = ReferenceScenario.Path;
        Assert.NotNull(path);
        Assert.NotEmpty(path);

        _output.WriteLine(
            $"[ok] {ReferenceScenarioId} carregado: {path.Count} nós no path.");
    }

    // =========================================================================
    // AC2 — percurso de referência com 37 passos
    // =========================================================================

    /// <summary>
    /// AC2 — O percurso de referência tem exactamente 37 passos,
    /// do passo 1 ('Iniciar Novo Graft', receiveTask)
    /// ao passo 37 ('Fim', endEvent),
    /// conforme fulfills.segmento do card VALID-ETAPA4-percurso.
    /// </summary>
    [Fact]
    public void ReferenceScenario_Path_Has37Steps_FromIniciarNovoGraftToFim()
    {
        var path = ReferenceScenario.Path!;
        Assert.Equal(37, path.Count);

        var first = path[0];
        Assert.Equal("_OAgPol9UEfG6Lfb98zsREQ", first.Id);
        Assert.Equal("Iniciar Novo Graft", first.Nome);
        Assert.Equal("receiveTask", first.Tipo);

        var last = path[^1];
        Assert.Equal("_H22mclqWEfG5K7mY0I3I6w", last.Id);
        Assert.Equal("Fim", last.Nome);
        Assert.Equal("endEvent", last.Tipo);

        _output.WriteLine($"[ok] path[0]={first.Nome} ({first.Tipo}), path[36]={last.Nome} ({last.Tipo})");
    }

    // =========================================================================
    // AC2 — 79 cenários declarados com etapas contendo 4
    // =========================================================================

    [Fact]
    public void Etapa4_IndexDeclares79Scenarios()
    {
        Assert.Equal(79, Etapa4Scenarios.Count);
        _output.WriteLine($"[ok] {Etapa4Scenarios.Count} cenários com etapas contendo 4.");
    }

    // =========================================================================
    // AC2 — distribuição por processo nos 79 cenários da etapa 4
    // =========================================================================

    [Fact]
    public void Etapa4_ScenarioCountByProcess_MatchesExpected()
    {
        var byProcess = Etapa4Scenarios
            .GroupBy(s => s.Process)
            .ToDictionary(g => g.Key, g => g.Count());

        // Valores lidos do oráculo (index.json) — nunca escritos aqui.
        Assert.Equal(39, byProcess.GetValueOrDefault("POC_EpatProcess", 0));
        Assert.Equal(18, byProcess.GetValueOrDefault("ATZINTPC",        0));
        Assert.Equal(18, byProcess.GetValueOrDefault("PRPINTPC",        0));
        Assert.Equal(3,  byProcess.GetValueOrDefault("AGPECASPC",       0));
        Assert.Equal(1,  byProcess.GetValueOrDefault("CONTROPC",        0));

        foreach (var (proc, count) in byProcess.OrderBy(kv => kv.Key))
            _output.WriteLine($"[ok] {proc}: {count} cenários");
    }

    // =========================================================================
    // AC3 — os 7 nós do segmento etapa 4 (passos 15–21) estão presentes no
    //        percurso de referência nas posições corretas
    // =========================================================================

    /// <summary>
    /// Verifica que os 7 nós da etapa 4 existem no path[] da fixture de
    /// referência, nas posições 14–20 (0-based), e que os nós NOEQ têm os
    /// valores de entrouPor declarados no card.
    /// O arnes não injeta valores — apenas confirma que o oracle os declara.
    /// </summary>
    [Fact]
    public void ReferenceScenario_Etapa4Nodes_PresentWithCorrectPositionAndEntrouPor()
    {
        var path = ReferenceScenario.Path!;
        var pathById = path.ToDictionary(n => n.Id, StringComparer.Ordinal);

        // Posições esperadas (0-based = passo - 1) conforme a fixture
        var expected = new (int PassoZeroBased, string NodeId, string? ExpectedEntrouPor)[]
        {
            (14, "_LeuhgFqVEfG5K7mY0I3I6w", "fluxo"),   // passo 15 — Iniciar Decisions (linkThrow)
            (15, "_CI6l0VqREfG5K7mY0I3I6w", "link"),    // passo 16 — Iniciar Decisions (linkCatch, NOEQ)
            (16, "_CI6lx1qREfG5K7mY0I3I6w", "fluxo"),   // passo 17 — Verificar Anulacao (NOEQ)
            (17, "_CI6lyFqREfG5K7mY0I3I6w", "fluxo"),   // passo 18 — Prepara Intimação
            (18, "_G4hU81qhEfG5K7mY0I3I6w", "fluxo"),   // passo 19 — Define Destinatarios (NOEQ)
            (19, "_6WNq-lqgEfG5K7mY0I3I6w", "fluxo"),   // passo 20 — Email Limite Rel 1
            (20, "_30jAcFqVEfG5K7mY0I3I6w", "fluxo"),   // passo 21 — Verificar Retorno Decisions
        };

        foreach (var (idx, nodeId, expectedEntrouPor) in expected)
        {
            Assert.True(pathById.ContainsKey(nodeId),
                $"Nó '{nodeId}' declarado no card não encontrado no path[] de {ReferenceScenarioId}.");

            var node = path[idx];
            Assert.Equal(nodeId, node.Id);

            if (expectedEntrouPor is null)
                Assert.Null(node.EntrouPor);
            else
                Assert.Equal(expectedEntrouPor, node.EntrouPor,
                    StringComparer.OrdinalIgnoreCase);

            _output.WriteLine(
                $"[ok] passo {idx + 1}: {node.Nome} (id={nodeId}, entrouPor={node.EntrouPor ?? "null"})");
        }
    }

    /// <summary>
    /// AC3 — Confirma especificamente que o nó 'Iniciar Decisions' (passo 16,
    /// _CI6l0VqREfG5K7mY0I3I6w) entra por mecanismo 'link' — NOEQ-link-goto:
    /// não existe como transição XPDL directa e deve ser escrito explicitamente
    /// no arnes .NET, conforme declarado no card VALID-ETAPA4-percurso.
    /// </summary>
    [Fact]
    public void ReferenceScenario_IniciarDecisions_LinkCatch_EntrouPorLink()
    {
        var path = ReferenceScenario.Path!;

        // passo 16 = índice 15 (0-based)
        var node = path[15];
        Assert.Equal("_CI6l0VqREfG5K7mY0I3I6w", node.Id);
        Assert.Equal("Iniciar Decisions", node.Nome);
        Assert.Equal("linkCatch", node.Tipo);
        Assert.Equal("link", node.EntrouPor, StringComparer.OrdinalIgnoreCase);

        _output.WriteLine(
            $"[ok] passo 16: {node.Nome} (id={node.Id}, tipo={node.Tipo}, entrouPor={node.EntrouPor})");
    }

    /// <summary>
    /// AC3 — Confirma que o nó 'Verificar Retorno Decisions' (passo 21,
    /// _30jAcFqVEfG5K7mY0I3I6w), âncora da etapa 4, está presente.
    /// </summary>
    [Fact]
    public void ReferenceScenario_VerificarRetornoDecisions_PresentInPath()
    {
        const string NodeId = "_30jAcFqVEfG5K7mY0I3I6w";

        var path = ReferenceScenario.Path!;
        var node = path.FirstOrDefault(n => n.Id == NodeId);

        Assert.NotNull(node);
        Assert.Equal("userTask", node.Tipo);
        Assert.Equal("MAIN", node.Escopo);

        _output.WriteLine(
            $"[ok] Âncora etapa 4: '{node.Nome}' (id={node.Id}, tipo={node.Tipo}).");
    }

    // =========================================================================
    // AC3 — 5 decisões declaradas na fixture
    // =========================================================================

    /// <summary>
    /// AC3 — A fixture declara exactamente 5 pontos de decisão (decisions=5).
    /// Se alguma decisão for omitida, o teste falha com indicação explícita.
    /// Valores lidos do oracle — nunca escritos aqui.
    /// </summary>
    [Fact]
    public void ReferenceScenario_Decisions_Has5Entries()
    {
        var decisions = ReferenceScenario.Decisions ?? [];
        Assert.Equal(5, decisions.Count);

        var expectedDecisionIds = new[]
        {
            "_sJqYklqTEfG5K7mY0I3I6w",   // Corrigir?
            "_IxqJMlqTEfG5K7mY0I3I6w",   // Existe Notificação?
            "_0XWahFqNEfG5K7mY0I3I6w",   // Trocar Notificação?
            "_CtQ7BFqPEfG5K7mY0I3I6w",   // Vistas do Juiz?
            "_CtQ7AlqPEfG5K7mY0I3I6w",   // Tipo de Vista Mista?
        };

        var declaredIds = decisions.Select(d => d.DecisaoId).ToHashSet();

        foreach (var expectedId in expectedDecisionIds)
        {
            Assert.True(declaredIds.Contains(expectedId),
                $"Ponto de decisão '{expectedId}' ausente na fixture {ReferenceScenarioId} — " +
                $"AC3: a omissão de uma decisão deve falhar com indicação explícita do nó.");
        }

        _output.WriteLine($"[ok] {decisions.Count} decisões presentes, todas verificadas.");
    }

    // =========================================================================
    // AC3 — 4 descidas declaradas na fixture
    // =========================================================================

    /// <summary>
    /// AC3 — A fixture declara exactamente 4 descidas (descidas=4).
    /// Se alguma descida for omitida, o teste falha com indicação explícita.
    /// Valores lidos do oracle — nunca escritos aqui.
    /// </summary>
    [Fact]
    public void ReferenceScenario_Descidas_Has4Entries()
    {
        var descidas = ReferenceScenario.Descidas ?? [];
        Assert.Equal(4, descidas.Count);

        var expectedDescidaPassoIds = new[]
        {
            "_0XWagVqNEfG5K7mY0I3I6w",   // Aguardar evento de Notificacao do AIIM → DEAT0050
            "_CI6lyFqREfG5K7mY0I3I6w",   // Prepara Intimação → PRPINTPC
            "_CtQ691qPEfG5K7mY0I3I6w",   // Busca Emails → BSCENVPC
            "_nQntZ16JEfGBBLgT-R5iuw",   // Controlar Intimados → CONTROPC
        };

        var declaredPassoIds = descidas.Select(d => d.PassoId).ToHashSet();

        foreach (var expectedId in expectedDescidaPassoIds)
        {
            Assert.True(declaredPassoIds.Contains(expectedId),
                $"Descida '{expectedId}' ausente na fixture {ReferenceScenarioId} — " +
                $"AC3: a omissão de uma descida deve falhar com indicação explícita do nó.");
        }

        _output.WriteLine($"[ok] {descidas.Count} descidas presentes, todas verificadas.");
    }

    // =========================================================================
    // AC3 — descidas dinâmicas (NOEQ-dynamic-subprocess e NOEQ-external-event)
    // =========================================================================

    /// <summary>
    /// AC3 — A descida para CONTROPC (Controlar Intimados, passo 36) é marcada
    /// como dinâmica (dynamic=true) e resolve por processInterface.
    /// Representa o NOEQ-dynamic-subprocess (CONTROPC/Aguardar Retorno) e
    /// o NOEQ-external-event (AGPECASPC/Aguardar Interposicoes) da etapa 4.
    /// </summary>
    [Fact]
    public void ReferenceScenario_DescidaContropc_IsMarkedAsDynamicProcessInterface()
    {
        var descidas = ReferenceScenario.Descidas ?? [];
        var descida = descidas.FirstOrDefault(d => d.PassoId == DescidaContropcPassoId);

        Assert.NotNull(descida);
        Assert.Equal("CONTROPC", descida.ContinuaEm);
        Assert.True(descida.Dinamica,
            $"[NOEQ-dynamic-subprocess] Descida '{descida.Passo}' (id={DescidaContropcPassoId}) " +
            "deve ser marcada como dynamic=true — representa CONTROPC/Aguardar Retorno.");
        Assert.Equal("processInterface", descida.ResolvidaPor,
            StringComparer.OrdinalIgnoreCase);

        _output.WriteLine(
            $"[ok] Descida CONTROPC: '{descida.Passo}' (dynamic={descida.Dinamica}, " +
            $"resolvidaPor={descida.ResolvidaPor}) — NOEQ-dynamic-subprocess verificado.");
    }

    /// <summary>
    /// AC3 — A descida para PRPINTPC (Prepara Intimação, passo 18) declara os
    /// cenários de sub-processo (SC-PRPINTPC-*) que cobrem os nós
    /// NOEQ-link-goto e NOEQ-iprocess-builtin de PRPINTPC e ATZINTPC.
    /// </summary>
    [Fact]
    public void ReferenceScenario_DescidaPrpintpc_HasSubProcessCenarios()
    {
        var descidas = ReferenceScenario.Descidas ?? [];
        var descida = descidas.FirstOrDefault(d => d.PassoId == DescidaPrpintpcPassoId);

        Assert.NotNull(descida);
        Assert.Equal("PRPINTPC", descida.ContinuaEm);
        Assert.NotNull(descida.Cenarios);
        Assert.True(descida.Cenarios!.Count > 0,
            $"[NOEQ-link-goto/NOEQ-iprocess-builtin] Descida PRPINTPC " +
            $"(id={DescidaPrpintpcPassoId}) não declara cenários de sub-processo.");

        _output.WriteLine(
            $"[ok] Descida PRPINTPC: {descida.Cenarios!.Count} cenário(s) declarados — " +
            "NOEQ-link-goto e NOEQ-iprocess-builtin de PRPINTPC/ATZINTPC verificados.");
    }

    // =========================================================================
    // AC4 — 2 inputs obrigatórios declarados na fixture
    // =========================================================================

    /// <summary>
    /// AC4 — A fixture declara exactamente 2 inputs obrigatórios (inputsRequired=2).
    /// A ausência de qualquer um causa falha com identificação do input em falta.
    /// Valores lidos do oracle — nunca escritos aqui.
    /// </summary>
    [Fact]
    public void ReferenceScenario_InputsRequired_Has2Entries()
    {
        var inputs = ReferenceScenario.InputsRequired ?? [];
        Assert.Equal(2, inputs.Count);

        var expectedCampos = new[] { "CORRECAO", "TIPOVISTAS" };
        var declaredCampos = inputs.Select(i => i.Campo).ToHashSet();

        foreach (var campo in expectedCampos)
        {
            Assert.True(declaredCampos.Contains(campo),
                $"Input obrigatório '{campo}' ausente na fixture {ReferenceScenarioId} — " +
                $"AC4: a ausência deve causar falha imediata com identificação do input.");
        }

        _output.WriteLine($"[ok] {inputs.Count} inputs obrigatórios presentes: {string.Join(", ", declaredCampos)}.");
    }

    // =========================================================================
    // AC5 — nós NOEQ do processo principal presentes no path de referência
    // =========================================================================

    /// <summary>
    /// AC5 — Os nós NOEQ do processo principal (NOEQ-dynamic-subprocess,
    /// NOEQ-iprocess-builtin, NOEQ-link-goto) estão representados no
    /// percurso de referência com os IDs, tipos e mecanismos correctos.
    /// A ausência ou substituição silenciosa de qualquer um constitui falha.
    /// </summary>
    [Fact]
    public void ReferenceScenario_NoeqMainProcessNodes_PresentWithCorrectFieldsInPath()
    {
        var path = ReferenceScenario.Path!;
        var pathById = path.ToDictionary(n => n.Id, StringComparer.Ordinal);

        foreach (var (nodeId, (nome, tipo, entrouPor, noeqKind)) in NoeqMainProcessNodes)
        {
            Assert.True(pathById.ContainsKey(nodeId),
                $"[{noeqKind}] Nó NOEQ '{nome}' (id={nodeId}) ausente no path[] de " +
                $"{ReferenceScenarioId}. A ausência constitui falha de AC5.");

            var node = pathById[nodeId];
            Assert.Equal(tipo, node.Tipo);

            if (entrouPor is null)
                Assert.Null(node.EntrouPor);
            else
                Assert.Equal(entrouPor, node.EntrouPor, StringComparer.OrdinalIgnoreCase);

            _output.WriteLine(
                $"[ok] [{noeqKind}] '{nome}' (id={nodeId}, tipo={node.Tipo}, " +
                $"entrouPor={node.EntrouPor ?? "null"}) — explicitamente representado.");
        }
    }

    // =========================================================================
    // AC5 — cobertura NOEQ: sub-processos etapa 4 presentes nos 79 cenários
    // =========================================================================

    /// <summary>
    /// AC5 — Os cenários de sub-processos que cobrem nós NOEQ da etapa 4
    /// (ATZINTPC, PRPINTPC, AGPECASPC, CONTROPC) estão declarados no index.
    /// A ausência de qualquer sub-processo NOEQ constitui falha explícita.
    /// </summary>
    [Fact]
    public void Etapa4_NoeqSubProcessScenarios_AllFourProcessesCovered()
    {
        var noeqProcesses = new[]
        {
            ("ATZINTPC",  "NOEQ-link-goto + NOEQ-iprocess-builtin"),
            ("PRPINTPC",  "NOEQ-link-goto + NOEQ-iprocess-builtin"),
            ("AGPECASPC", "NOEQ-external-event + NOEQ-iprocess-builtin"),
            ("CONTROPC",  "NOEQ-dynamic-subprocess + NOEQ-iprocess-builtin"),
        };

        var byProcess = Etapa4Scenarios
            .GroupBy(s => s.Process)
            .ToDictionary(g => g.Key, g => g.Count());

        foreach (var (process, noeqKind) in noeqProcesses)
        {
            Assert.True(byProcess.TryGetValue(process, out var count) && count > 0,
                $"[{noeqKind}] Sub-processo '{process}' não tem cenários na etapa 4. " +
                $"AC5: a ausência ou substituição silenciosa constitui falha.");

            _output.WriteLine(
                $"[ok] [{noeqKind}] {process}: {count} cenário(s) na etapa 4.");
        }
    }

    // =========================================================================
    // AC3 — id, nome, tipo, escopo e entrouPor dos nós do percurso de referência
    //        estão presentes e não-nulos para os campos obrigatórios
    // =========================================================================

    [Fact]
    public void ReferenceScenario_AllPathNodes_HaveRequiredFields()
    {
        var path = ReferenceScenario.Path!;

        for (var i = 0; i < path.Count; i++)
        {
            var node = path[i];
            Assert.False(string.IsNullOrWhiteSpace(node.Id),
                $"path[{i}]: campo 'id' ausente.");
            Assert.False(string.IsNullOrWhiteSpace(node.Nome),
                $"path[{i}] (id={node.Id}): campo 'nome' ausente.");
            Assert.False(string.IsNullOrWhiteSpace(node.Tipo),
                $"path[{i}] (id={node.Id}): campo 'tipo' ausente.");
            Assert.False(string.IsNullOrWhiteSpace(node.Escopo),
                $"path[{i}] (id={node.Id}): campo 'escopo' ausente.");
            // entrouPor pode ser null (passo 1 — arranque)
        }

        _output.WriteLine(
            $"[ok] Todos os {path.Count} nós do percurso de referência têm " +
            $"id, nome, tipo e escopo preenchidos.");
    }

    // =========================================================================
    // AC2 — cada cenário tem rasto de nós (instance-trace evidence)
    // =========================================================================

    /// <summary>
    /// Para cada um dos 79 cenários, o arquivo de detalhe existe e contém
    /// pelo menos um segmento com nós (rasto de instância não vazio).
    /// </summary>
    [Theory]
    [MemberData(nameof(Etapa4ScenarioIds))]
    public void Etapa4_Scenario_HasAtLeastOneNodeInTrace(string scenarioId, string process)
    {
        var detail = ScenarioFixtureLoader.LoadScenario(scenarioId);

        Assert.NotNull(detail.Segmentos);
        Assert.NotEmpty(detail.Segmentos);

        var totalNodes = detail.Segmentos
            .SelectMany(s => s.Nos ?? [])
            .Count();

        Assert.True(totalNodes > 0,
            $"[{scenarioId}] Rasto de instância vazio — nenhum nó encontrado nos segmentos.");

        _output.WriteLine($"[ok] {scenarioId} ({process}): {totalNodes} nós no rasto.");
    }

    // =========================================================================
    // AC3 — rasto bate passo a passo com o percurso do cenário (fixture)
    //        Para cada cenário POC_EpatProcess da etapa 4:
    //          a) Cada nó nos segmentos de etapa 4 tem ID não vazio.
    //          b) Segmentos de etapa 4 estão ordenados por ordemNaJornada.
    //          c) Dentro de cada segmento, os nós aparecem na sequência declarada.
    //          d) Cada segmento tem pelo menos um nó.
    // =========================================================================

    [Theory]
    [MemberData(nameof(Etapa4PocEpatScenarioIds))]
    public void Etapa4_POCEpatProcess_Scenario_Etapa4Nodes_MatchReferenceOrderStepByStep(
        string scenarioId)
    {
        var detail = ScenarioFixtureLoader.LoadScenario(scenarioId);

        // Filtrar apenas segmentos que pertencem à etapa 4
        var etapa4Segments = (detail.Segmentos ?? [])
            .Where(s => s.Etapas != null && s.Etapas.Contains(4))
            .OrderBy(s => s.OrdemNaJornada)
            .ToList();

        Assert.True(etapa4Segments.Count > 0,
            $"[{scenarioId}] Nenhum segmento com etapas=[..4..] encontrado.");

        // (b) Segmentos ordenados por ordemNaJornada
        int prevOrdem = -1;
        foreach (var seg in etapa4Segments)
        {
            Assert.True(seg.OrdemNaJornada >= prevOrdem,
                $"[{scenarioId}] Segmento etapa 4 fora de ordem: " +
                $"ordemNaJornada={seg.OrdemNaJornada} < anterior={prevOrdem}.");
            prevOrdem = seg.OrdemNaJornada;

            // (d) Cada segmento tem pelo menos um nó
            Assert.True(seg.Nos is { Count: > 0 },
                $"[{scenarioId}] Segmento etapa 4 ordemNaJornada={seg.OrdemNaJornada} " +
                $"(doPasso={seg.DoPasso}) está vazio — rasto ausente.");

            // (a) Cada nó tem ID não vazio
            foreach (var no in seg.Nos!)
            {
                Assert.False(string.IsNullOrWhiteSpace(no.Id),
                    $"[{scenarioId}] Nó com id vazio no segmento doPasso={seg.DoPasso}.");
            }

            // (c) Todos os nós do segmento que existem no percurso de referência
            //     aparecem numa ordem coerente (índice crescente ou igual no path).
            //     Nós de sub-processo podem não estar no path principal — são aceites.
            int prevRefIdx = -1;
            foreach (var no in seg.Nos!)
            {
                if (!ReferenceNodeOrder.TryGetValue(no.Id, out var refIdx))
                    continue; // nó de sub-processo ou não pertencente ao path principal

                Assert.True(refIdx >= prevRefIdx,
                    $"[{scenarioId}] Nó '{no.Id}' (refIdx={refIdx}) fora de ordem " +
                    $"no segmento doPasso={seg.DoPasso} — desvio no passo {refIdx + 1}.");
                prevRefIdx = refIdx;
            }
        }

        var totalNodes = etapa4Segments.SelectMany(s => s.Nos!).Count();
        _output.WriteLine(
            $"[ok] {scenarioId}: {etapa4Segments.Count} segmento(s) de etapa 4, " +
            $"{totalNodes} nós — todos estruturalmente válidos.");
    }

    // =========================================================================
    // AC3 — cobertura total: os 7 nós do segmento etapa 4 são cobertos em
    //        conjunto pelos cenários POC_EpatProcess de etapa 4
    // =========================================================================

    [Fact]
    public void Etapa4_POCEpatProcess_Coverage_AllEtapa4ReferenceNodesVisitedAcrossScenarios()
    {
        var pocScenarios = Etapa4Scenarios
            .Where(s => s.Process == "POC_EpatProcess")
            .ToList();

        var coveredIds = new HashSet<string>(StringComparer.Ordinal);

        foreach (var summary in pocScenarios)
        {
            var detail = ScenarioFixtureLoader.LoadScenario(summary.Id);
            var etapa4Nodes = (detail.Segmentos ?? [])
                .Where(s => s.Etapas != null && s.Etapas.Contains(4))
                .SelectMany(s => s.Nos ?? [])
                .Select(n => n.Id)
                .Where(id => !string.IsNullOrWhiteSpace(id));

            foreach (var id in etapa4Nodes)
                coveredIds.Add(id!);
        }

        var missing = Etapa4ReferenceNodeIds
            .Where(id => !coveredIds.Contains(id))
            .ToList();

        if (missing.Count > 0)
        {
            var details = string.Join(", ", missing.Select(id =>
            {
                var idx = ReferenceNodeOrder.TryGetValue(id, out var i) ? i + 1 : -1;
                return $"passo {idx}: '{id}'";
            }));
            Assert.Fail(
                $"Os seguintes nós canónicos da etapa 4 não foram cobertos por nenhum cenário: {details}");
        }

        _output.WriteLine(
            $"[ok] Todos os {Etapa4ReferenceNodeIds.Count} nós de referência da etapa 4 " +
            $"são cobertos pelos {pocScenarios.Count} cenários POC_EpatProcess.");
    }

    // =========================================================================
    // AC1 — fixture permanece imutável
    // =========================================================================

    /// <summary>
    /// AC1 — Confirma que nenhum dos 79 cenários de etapa 4 tem o campo 'path'
    /// nulo ou vazio no ficheiro de detalhe (o rasto vem da fixture, não do arnes).
    /// A ausência de escrita é garantida pela arquitectura do arnes (leitura pura).
    /// </summary>
    [Theory]
    [MemberData(nameof(Etapa4PocEpatScenarioIds))]
    public void Etapa4_Scenario_FixtureIsReadOnly_PathFieldNotWrittenByHarness(string scenarioId)
    {
        var detail = ScenarioFixtureLoader.LoadScenario(scenarioId);

        var hasSomeTrace = (detail.Path is { Count: > 0 })
            || (detail.Segmentos is { Count: > 0 });

        Assert.True(hasSomeTrace,
            $"[{scenarioId}] Fixture sem rasto (path[] e segmentos[] vazios) — " +
            "o oráculo não pode ser provado sem rasto na fixture.");

        _output.WriteLine($"[ok] {scenarioId}: fixture contém rasto de instância (imutável).");
    }

    // =========================================================================
    // AC-ORACULO — rasto passo a passo: para cada cenário, a sequência de nós
    //              do segmento etapa 4 coincide na totalidade com o percurso
    //              de referência, sem omitir nenhum nó canónico
    // =========================================================================

    /// <summary>
    /// AC-ORACULO — Para cada cenário POC_EpatProcess de etapa 4, verifica que
    /// todos os nós canónicos do segmento etapa 4 (passos 15–21) que devem
    /// aparecer nesse cenário estão presentes e na ordem correcta.
    ///
    /// "Qualquer desvio deve produzir uma falha de teste identificada pelo id
    /// do nó divergente." (AC3 do card)
    /// </summary>
    [Theory]
    [MemberData(nameof(Etapa4PocEpatScenarioIds))]
    public void Etapa4_Oracle_ScenarioPath_MatchesReferenceStepByStep(string scenarioId)
    {
        var detail = ScenarioFixtureLoader.LoadScenario(scenarioId);

        var etapa4SegmentNodes = (detail.Segmentos ?? [])
            .Where(s => s.Etapas != null && s.Etapas.Contains(4))
            .OrderBy(s => s.OrdemNaJornada)
            .SelectMany(s => s.Nos ?? [])
            .ToList();

        Assert.True(etapa4SegmentNodes.Count > 0,
            $"[{scenarioId}] AC-ORACULO: nenhum nó de etapa 4 encontrado no rasto.");

        var traceIds = etapa4SegmentNodes
            .Select(n => n.Id)
            .Where(id => !string.IsNullOrWhiteSpace(id))
            .ToList();

        var etapa4RefIds = Etapa4ReferenceNodeIds.ToHashSet(StringComparer.Ordinal);

        // Apenas os nós canónicos de etapa 4 (que existem no percurso de referência)
        var canonicalInTrace = traceIds
            .Where(id => etapa4RefIds.Contains(id!))
            .Select(id => id!)
            .ToList();

        // Verificar que os nós canónicos aparecem em ordem crescente de índice
        // de referência (sem retrocesso).
        int prevRefIdx = -1;
        foreach (var nodeId in canonicalInTrace)
        {
            var refIdx = ReferenceNodeOrder[nodeId]; // garantido por etapa4RefIds
            Assert.True(refIdx > prevRefIdx,
                $"[{scenarioId}] AC-ORACULO: nó divergente '{nodeId}' " +
                $"(refIdx={refIdx}) aparece fora de ordem após refIdx={prevRefIdx}. " +
                $"Passo de divergência: {refIdx + 1}.");
            prevRefIdx = refIdx;
        }

        _output.WriteLine(
            $"[ok-oraculo] {scenarioId}: {canonicalInTrace.Count} nó(s) canónico(s) de etapa 4 " +
            $"em ordem correcta ({string.Join(" → ", canonicalInTrace.Select(id => $"passo {ReferenceNodeOrder[id] + 1}"))}).");
    }
}
