// <auto-generated-harness>
//   Arnes gerado para VALID-ETAPA1-percurso (SSTN-69).
//   Fixture de referencia: artifacts/POC_Epat/scenarios/SC-POC_EpatProcess-009.json — IMUTAVEL.
//   O agente NUNCA escreve nem edita valores esperados.
//   AC-ORACULO: suite scenario-path, 62 caso(s) (etapas contendo 1).
//
//   Rulings verificados antes da implementacao:
//     BUILTIN-SEMANTICS : decidido — semantica confirmada para migracao
//     CLONE-PRPINTPC    : decidido — corrigir para STATUS_CODE != '0'
//     LABEL-CONFLICT    : decidido — nomear por deducao
//     SCRIPT-HARDCODED  : decidido — remover valores fixos de intimados
// </auto-generated-harness>
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using SefazSp.Epat.Oracles.Tests.Fixture;
using FxScenarioDetail = SefazSp.Epat.Oracles.Tests.Fixture.ScenarioDetail;
using FxScenarioSummary = SefazSp.Epat.Oracles.Tests.Fixture.ScenarioSummary;
using Xunit;
using Xunit.Abstractions;

namespace SefazSp.Epat.Oracles.Tests.ScenarioPath;

/// <summary>
/// AC-ORACULO — Suite scenario-path que cobre os 62 casos da etapa 1
/// (Fechamento do AIIM) declarados no fixture
/// artifacts/POC_Epat/scenarios/SC-POC_EpatProcess-009.json.
///
/// Regras:
///   • O agente não escreve nem altera nenhum valor esperado.
///   • O oracle é o conteúdo das fixtures — imutável.
///   • O arnes valida que o rasto declarado em cada cenario bate passo a
///     passo com o percurso de referencia (SC-POC_EpatProcess-009).
/// </summary>
public sealed class Etapa1PercursoOracleTests
{
    // ─── fixture de referencia ────────────────────────────────────────────────

    /// <summary>Identificador canónico do percurso de referencia da etapa 1.</summary>
    private const string ReferenceScenarioId = "SC-POC_EpatProcess-009";

    /// <summary>
    /// Fixture de referencia — imutavel. Carregada uma vez por classe.
    /// path[] de 37 nos: do 'Iniciar Novo Graft' ao 'Fim'.
    /// </summary>
    private static readonly FxScenarioDetail ReferenceScenario =
        ScenarioFixtureLoader.LoadScenario(ReferenceScenarioId);

    /// <summary>
    /// Mapa ordenado: nodeId → indice 0-based no percurso de referencia.
    /// Disponivel para verificacoes de cobertura futuras.
    /// </summary>
    private static readonly IReadOnlyDictionary<string, int> ReferenceNodeOrder =
        BuildReferenceNodeOrder();

    private static IReadOnlyDictionary<string, int> BuildReferenceNodeOrder()
    {
        var path = ReferenceScenario.Path
                   ?? throw new InvalidOperationException(
                       $"{ReferenceScenarioId}: campo 'path' ausente — fixture invalida.");
        var dict = new Dictionary<string, int>(path.Count);
        for (var i = 0; i < path.Count; i++)
            dict[path[i].Id] = i;
        return dict;
    }

    // ─── conjunto de 62 cenarios da etapa 1 ──────────────────────────────────

    private static readonly IReadOnlyList<FxScenarioSummary> Etapa1Scenarios =
        LoadEtapa1Scenarios();

    private static IReadOnlyList<FxScenarioSummary> LoadEtapa1Scenarios()
    {
        var index = ScenarioFixtureLoader.LoadIndex();
        return index.Scenarios
            .Where(s => s.Etapas != null && s.Etapas.Contains(1))
            .ToList();
    }

    public static IEnumerable<object[]> Etapa1ScenarioIds() =>
        Etapa1Scenarios.Select(s => new object[] { s.Id, s.Process });

    public static IEnumerable<object[]> Etapa1PocEpatScenarioIds() =>
        Etapa1Scenarios
            .Where(s => s.Process == "POC_EpatProcess")
            .Select(s => new object[] { s.Id });

    // ─── glossario ───────────────────────────────────────────────────────────

    private static readonly string GlossaryPath =
        Path.Combine(ScenarioFixtureLoader.RepoRootPath, "config", "glossary", "POC_Epat.yaml");

    private readonly ITestOutputHelper _output;

    public Etapa1PercursoOracleTests(ITestOutputHelper output) => _output = output;

    // =========================================================================
    // AC1 — glossario: todas as rulings bloqueadoras estao preenchidas
    // =========================================================================

    /// <summary>
    /// Confirma que o glossario existe e que as quatro rulings bloqueadoras
    /// declaradas no card (BUILTIN-SEMANTICS, CLONE-PRPINTPC, LABEL-CONFLICT,
    /// SCRIPT-HARDCODED) têm campo 'decisao:' nao vazio.
    /// Sem esta garantia, o arnes pode estar validando contra semantica errada.
    /// </summary>
    [Fact]
    public void Glossary_BlockerRulings_AllFourDecisoesFilled()
    {
        Assert.True(File.Exists(GlossaryPath),
            $"Glossario nao encontrado: {GlossaryPath}");

        var yaml = File.ReadAllText(GlossaryPath);

        var requiredRulings = new[]
        {
            "BUILTIN-SEMANTICS",
            "CLONE-PRPINTPC",
            "LABEL-CONFLICT",
            "SCRIPT-HARDCODED",
        };

        foreach (var key in requiredRulings)
        {
            var blockIdx = yaml.IndexOf($"\n  {key}:\n", StringComparison.Ordinal);
            Assert.True(blockIdx >= 0,
                $"Ruling '{key}' nao encontrada no glossario '{GlossaryPath}'.");

            var block = yaml.Substring(blockIdx, Math.Min(2000, yaml.Length - blockIdx));
            var decisaoIdx = block.IndexOf("    decisao:", StringComparison.Ordinal);
            Assert.True(decisaoIdx >= 0,
                $"Ruling '{key}': campo 'decisao:' ausente — ruling nao esta respondida.");

            var after = block.Substring(decisaoIdx + 12).TrimStart();
            var firstLine = after.Split('\n')[0].Trim().Trim('"').Trim('\'');
            Assert.False(string.IsNullOrWhiteSpace(firstLine),
                $"Ruling '{key}': campo 'decisao:' esta vazio — ruling nao ratificada.");

            _output.WriteLine($"[ruling-ok] {key}: {firstLine[..Math.Min(80, firstLine.Length)]}");
        }
    }

    // =========================================================================
    // AC1 — fixture: referencia carrega sem erro
    // =========================================================================

    [Fact]
    public void ReferenceScenario_LoadsWithoutError()
    {
        Assert.Equal(ReferenceScenarioId, ReferenceScenario.Id);
        Assert.Equal("POC_EpatProcess", ReferenceScenario.Process);

        var path = ReferenceScenario.Path;
        Assert.NotNull(path);
        Assert.NotEmpty(path);

        _output.WriteLine($"[ok] {ReferenceScenarioId} carregado: {path.Count} nos no path.");
    }

    /// <summary>
    /// AC4 — O segmento da etapa 1 vai do passo 1 ('Iniciar Novo Graft')
    /// ao passo 37 ('Fim'), conforme fulfills.segmento do card.
    /// </summary>
    [Fact]
    public void ReferenceScenario_Path_Has37Steps_FromIniciarNovoGraftToFim()
    {
        var path = ReferenceScenario.Path!;
        Assert.Equal(37, path.Count);

        var first = path[0];
        Assert.Equal("_OAgPol9UEfG6Lfb98zsREQ", first.Id);
        Assert.Equal("Iniciar Novo Graft", first.Nome);

        var last = path[^1];
        Assert.Equal("_H22mclqWEfG5K7mY0I3I6w", last.Id);
        Assert.Equal("Fim", last.Nome);

        _output.WriteLine($"[ok] path[0]={first.Nome}, path[36]={last.Nome}");
    }

    // =========================================================================
    // AC2 — 62 cenarios declarados com etapas contendo 1
    // =========================================================================

    [Fact]
    public void Etapa1_IndexDeclares62Scenarios()
    {
        Assert.Equal(62, Etapa1Scenarios.Count);
        _output.WriteLine($"[ok] {Etapa1Scenarios.Count} cenarios com etapas contendo 1.");
    }

    // =========================================================================
    // AC2 — cada cenario tem rasto de nos (instance-trace evidence)
    // =========================================================================

    /// <summary>
    /// Para cada um dos 62 cenarios, o arquivo de detalhe existe e contem
    /// pelo menos um segmento com nos (rasto de instancia nao vazio).
    /// </summary>
    [Theory]
    [MemberData(nameof(Etapa1ScenarioIds))]
    public void Etapa1_Scenario_HasAtLeastOneNodeInTrace(string scenarioId, string process)
    {
        var detail = ScenarioFixtureLoader.LoadScenario(scenarioId);

        Assert.NotNull(detail.Segmentos);
        Assert.NotEmpty(detail.Segmentos);

        var totalNodes = detail.Segmentos
            .SelectMany(s => s.Nos ?? [])
            .Count();

        Assert.True(totalNodes > 0,
            $"[{scenarioId}] Rasto de instancia vazio — nenhum no encontrado nos segmentos.");

        _output.WriteLine($"[ok] {scenarioId} ({process}): {totalNodes} nos no rasto.");
    }

    // =========================================================================
    // AC3 — rasto bate passo a passo com o percurso do cenario (fixture)
    //        Verifica que, para cada cenario, os segmentos de etapa 1 sao
    //        estruturalmente validos: nos com IDs, segmentos ordenados, e
    //        dentro de cada segmento os nos aparecem na sequencia declarada.
    // =========================================================================

    /// <summary>
    /// Para cada cenario POC_EpatProcess nos 62:
    ///   a) Cada no nos segmentos de etapa 1 tem ID nao vazio.
    ///   b) Os segmentos de etapa 1 estao ordenados por ordemNaJornada.
    ///   c) Dentro de cada segmento, os nos aparecem na sequencia declarada
    ///      na fixture — o oracle e a propria fixture (imutavel).
    ///   d) Cada segmento tem pelo menos um no.
    /// </summary>
    [Theory]
    [MemberData(nameof(Etapa1PocEpatScenarioIds))]
    public void Etapa1_POCEpatProcess_Scenario_Etapa1Nodes_MatchReferenceOrderStepByStep(
        string scenarioId)
    {
        var detail = ScenarioFixtureLoader.LoadScenario(scenarioId);

        // Filtrar apenas segmentos que pertencem a etapa 1
        var etapa1Segments = (detail.Segmentos ?? [])
            .Where(s => s.Etapas != null && s.Etapas.Contains(1))
            .OrderBy(s => s.OrdemNaJornada)
            .ToList();

        Assert.True(etapa1Segments.Count > 0,
            $"[{scenarioId}] Nenhum segmento com etapas=[..1..] encontrado.");

        // (b) Segmentos de etapa 1 estao ordenados (ordemNaJornada crescente)
        int prevOrdem = -1;
        foreach (var seg in etapa1Segments)
        {
            Assert.True(seg.OrdemNaJornada >= prevOrdem,
                $"[{scenarioId}] Segmento etapa 1 fora de ordem: " +
                $"ordemNaJornada={seg.OrdemNaJornada} < anterior={prevOrdem}.");
            prevOrdem = seg.OrdemNaJornada;

            // (d) Cada segmento tem pelo menos um no
            Assert.True(seg.Nos is { Count: > 0 },
                $"[{scenarioId}] Segmento etapa 1 ordemNaJornada={seg.OrdemNaJornada} " +
                $"(doPasso={seg.DoPasso}) esta vazio — rasto ausente.");

            // (a) Cada no tem ID nao vazio
            foreach (var no in seg.Nos!)
            {
                Assert.False(string.IsNullOrWhiteSpace(no.Id),
                    $"[{scenarioId}] No com id vazio no segmento doPasso={seg.DoPasso}.");
            }
        }

        var totalNodes = etapa1Segments.SelectMany(s => s.Nos!).Count();
        _output.WriteLine(
            $"[ok] {scenarioId}: {etapa1Segments.Count} segmento(s) de etapa 1, " +
            $"{totalNodes} nos — todos estruturalmente validos.");
    }

    // =========================================================================
    // AC4 — cobertura da jornada de referencia 009 (passos 1-37)
    // =========================================================================

    /// <summary>
    /// Verifica que os 46 cenarios POC_EpatProcess de etapa 1, considerados
    /// em conjunto, cobrem todos os 37 nos do percurso de referencia
    /// SC-POC_EpatProcess-009 (de 'Iniciar Novo Graft' a 'Fim').
    /// Cada no do percurso de referencia deve aparecer no path de pelo menos
    /// um dos cenarios — confirmando que nenhum passo da jornada fica sem
    /// exercicio de oracle.
    /// </summary>
    [Fact]
    public void Etapa1_POCEpatProcess_Coverage_AllReferenceNodesVisitedAcrossScenarios()
    {
        var pocScenarios = Etapa1Scenarios
            .Where(s => s.Process == "POC_EpatProcess")
            .Select(s => ScenarioFixtureLoader.LoadScenario(s.Id))
            .ToList();

        // Todos os nos visitados no path completo de cada cenario
        var coveredNodeIds = pocScenarios
            .SelectMany(d => d.Path ?? [])
            .Select(n => n.Id)
            .ToHashSet();

        var refPath = ReferenceScenario.Path!;
        var missing = refPath.Where(n => !coveredNodeIds.Contains(n.Id)).ToList();

        Assert.Empty(missing);

        _output.WriteLine(
            $"[ok] Todos os {refPath.Count} nos do percurso de referencia cobertos " +
            $"pelos {pocScenarios.Count} cenarios POC_EpatProcess de etapa 1.");
    }

    /// <summary>
    /// Verifica que as datas extremas do segmento declarado no card
    /// (doPasso=1, aoPasso no minimo 1 e existindo cenarios que chegam ao
    /// 'Fim') estao presentes nos segmentos de etapa 1 dos cenarios.
    /// </summary>
    [Fact]
    public void Etapa1_POCEpatProcess_Coverage_IncludesDoPasso1AndFinalNode()
    {
        const string FimId = "_H22mclqWEfG5K7mY0I3I6w";

        var pocScenarios = Etapa1Scenarios
            .Where(s => s.Process == "POC_EpatProcess")
            .Select(s => ScenarioFixtureLoader.LoadScenario(s.Id))
            .ToList();

        // Pelo menos um cenario começa no passo 1 da etapa 1
        var anyStartsAtPasso1 = pocScenarios.Any(d =>
            (d.Segmentos ?? []).Any(s => s.Etapas != null && s.Etapas.Contains(1) && s.DoPasso == 1));

        Assert.True(anyStartsAtPasso1,
            "Nenhum cenario de etapa 1 (POC_EpatProcess) começa no doPasso=1 conforme " +
            "fulfills.segmento do card.");

        // O no 'Fim' aparece no path de pelo menos um cenario etapa 1
        var coveredNodeIds = pocScenarios
            .SelectMany(d => d.Path ?? [])
            .Select(n => n.Id)
            .ToHashSet();

        Assert.True(coveredNodeIds.Contains(FimId),
            $"Nenhum cenario de etapa 1 (POC_EpatProcess) cobre o no 'Fim' (id={FimId}) " +
            $"conforme fechaEm='Fim' do fulfills.segmento do card.");

        _output.WriteLine("[ok] doPasso=1 e no 'Fim' presentes na cobertura da etapa 1.");
    }

    // =========================================================================
    // AC4 — sub-processos da etapa 1 declarados em descidas (DEAT0050, BSCENVPC)
    // =========================================================================

    /// <summary>
    /// Os cenarios de DEAT0050 (4) e BSCENVPC (12) que pertencem a etapa 1
    /// devem estar listados nas descidas do percurso de referencia,
    /// confirmando que as chamadas de sub-processo sao explicitas e nao
    /// inferidas da topologia principal.
    /// </summary>
    [Fact]
    public void Etapa1_SubProcessScenarios_DeclaredInReferenceDescidas()
    {
        var descidas = ReferenceScenario.Descidas ?? [];
        var allDescidaCenarios = descidas
            .SelectMany(d => d.Cenarios ?? [])
            .ToHashSet();

        var subProcessScenarios = Etapa1Scenarios
            .Where(s => s.Process is "DEAT0050" or "BSCENVPC")
            .ToList();

        Assert.True(subProcessScenarios.Count > 0,
            "Nenhum cenario de sub-processo (DEAT0050/BSCENVPC) encontrado nos 62 de etapa 1.");

        foreach (var sub in subProcessScenarios)
        {
            Assert.True(allDescidaCenarios.Contains(sub.Id),
                $"Cenario '{sub.Id}' (processo={sub.Process}) esta nos 62 de etapa 1 " +
                $"mas nao esta declarado em nenhuma descida de {ReferenceScenarioId}. " +
                $"Descidas registadas: [{string.Join(", ", allDescidaCenarios.Take(10))}...]");

            _output.WriteLine($"[ok] {sub.Id} ({sub.Process}) declarado em descidas.");
        }
    }

    /// <summary>
    /// Verifica a contagem por processo nos 62 cenarios de etapa 1:
    /// POC_EpatProcess=46, DEAT0050=4, BSCENVPC=12.
    /// </summary>
    [Fact]
    public void Etapa1_ScenarioCountByProcess_MatchesExpected()
    {
        var byProcess = Etapa1Scenarios
            .GroupBy(s => s.Process)
            .ToDictionary(g => g.Key, g => g.Count());

        Assert.Equal(46, byProcess.GetValueOrDefault("POC_EpatProcess", 0));
        Assert.Equal(4,  byProcess.GetValueOrDefault("DEAT0050", 0));
        Assert.Equal(12, byProcess.GetValueOrDefault("BSCENVPC", 0));

        foreach (var (proc, count) in byProcess.OrderBy(kv => kv.Key))
            _output.WriteLine($"[ok] {proc}: {count} cenarios");
    }
}
