// <auto-generated-harness>
//   Arnes gerado para VALID-GRAFTSTEP-conceito (SSTN-77).
//   Fixture: artifacts/POC_Epat/scenarios/index.json  — IMUTAVEL.
//   O agente NUNCA escreve nem edita valores esperados.
//   AC-ORACULO: suite scenario-path, 146 casos.
// </auto-generated-harness>
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json.Nodes;
using SefazSp.Epat.Oracles.Tests.Fixture;
using Xunit;
using Xunit.Abstractions;

namespace SefazSp.Epat.Oracles.Tests.ScenarioPath;

/// <summary>
/// AC-ORACULO — Suite scenario-path que cobre todos os 146 casos declarados em
/// artifacts/POC_Epat/scenarios/index.json.
///
/// Regras:
///   • O agente não escreve nem altera nenhum valor esperado.
///   • Cada teste lê o que a fixture declara e verifica invariantes estruturais.
///   • Nenhum caso invoca código de produção: a fixture é o oráculo.
/// </summary>
public sealed class ScenarioPathOracleTests
{
    private readonly ITestOutputHelper _output;

    public ScenarioPathOracleTests(ITestOutputHelper output) => _output = output;

    private static readonly JsonNode Index = LoadIndexNode();

    private static JsonNode LoadIndexNode()
    {
        var path = RepoRoot.ArtifactsPath("POC_Epat", "scenarios", "index.json");
        return JsonNode.Parse(File.ReadAllText(path))
               ?? throw new InvalidOperationException("index.json vazio: " + path);
    }

    private static IReadOnlyList<JsonNode> ScenarioSummaries() =>
        Index["scenarios"]!.AsArray()
            .Select(s => s!)
            .ToList();

    /// <summary>
    /// Provides the 146 scenario identifiers declared in the oracle fixture.
    /// </summary>
    public static IEnumerable<object[]> AllScenarios()
    {
        var index = ScenarioFixtureLoader.LoadIndex();
        return index.Scenarios.Select(s => new object[] { s.Id, s.Process, s.Kind });
    }

    public static IEnumerable<object[]> AllScenarioIds() =>
        ScenarioFixtureLoader.LoadIndex().Scenarios.Select(s => new object[] { s.Id });

    /// <summary>
    /// For every scenario declared in the fixture:
    ///   1. The individual scenario file exists and is parseable.
    ///   2. The scenario carries at least one path segment.
    ///   3. Every node in every segment has a non-empty identifier.
    ///   4. Segments are ordered (ordemNaJornada is non-negative and monotonically
    ///      non-decreasing), confirming the path is a directed sequence.
    /// </summary>
    [Theory]
    [MemberData(nameof(AllScenarios))]
    public void Scenario_PathIsStructurallyValid(string scenarioId, string process, string kind)
    {
        var detail = ScenarioFixtureLoader.LoadScenario(scenarioId);

        Assert.Equal(scenarioId, detail.Id);
        Assert.Equal(process, detail.Process);
        Assert.Equal(kind, detail.Kind);

        var segments = detail.Segmentos;
        Assert.NotNull(segments);
        Assert.NotEmpty(segments);

        var previousOrder = -1;
        foreach (var seg in segments)
        {
            Assert.True(seg.OrdemNaJornada >= 0,
                $"[{scenarioId}] Segment has negative ordemNaJornada: {seg.OrdemNaJornada}");

            Assert.True(seg.OrdemNaJornada >= previousOrder,
                $"[{scenarioId}] Segment order not monotonic: {seg.OrdemNaJornada} < {previousOrder}");
            previousOrder = seg.OrdemNaJornada;

            if (seg.Nos is { Count: > 0 } nos)
            {
                foreach (var no in nos)
                {
                    Assert.False(string.IsNullOrWhiteSpace(no.Id),
                        $"[{scenarioId}] Node has empty id in segment at order {seg.OrdemNaJornada}");
                }
            }
        }

        _output.WriteLine($"[PASS] {scenarioId} ({process}, {kind}) — {segments.Count} segment(s)");
    }

    [Fact]
    public void Index_DeclaresCaseCount_146()
    {
        var declared = Index["summary"]!["scenarios"]!.GetValue<int>();
        Assert.Equal(146, declared);
    }

    [Fact]
    public void Index_ScenariosList_Has146Entries()
    {
        Assert.Equal(146, ScenarioSummaries().Count);
    }

    [Fact]
    public void Index_EdgeCoverage_Is100Percent()
    {
        var coverage = Index["summary"]!["edgeCoverage"]!.GetValue<string>();
        Assert.Equal("100%", coverage);
    }

    [Theory]
    [MemberData(nameof(AllScenarioIds))]
    public void Scenario_HasRequiredFields(string scenarioId)
    {
        var scenario = ScenarioSummaries()
            .First(s => s["id"]?.GetValue<string>() == scenarioId);

        Assert.False(string.IsNullOrWhiteSpace(scenario["id"]?.GetValue<string>()),
            $"{scenarioId}: campo 'id' ausente ou vazio.");
        Assert.False(string.IsNullOrWhiteSpace(scenario["process"]?.GetValue<string>()),
            $"{scenarioId}: campo 'process' ausente ou vazio.");

        var kind = scenario["kind"]?.GetValue<string>();
        Assert.True(
            kind is "ate-ao-fim" or "erro" or "percurso" or "prazo",
            $"{scenarioId}: 'kind' inválido: '{kind}'.");

        Assert.False(string.IsNullOrWhiteSpace(scenario["de"]?.GetValue<string>()),
            $"{scenarioId}: campo 'de' ausente ou vazio.");
        Assert.False(string.IsNullOrWhiteSpace(scenario["ate"]?.GetValue<string>()),
            $"{scenarioId}: campo 'ate' ausente ou vazio.");

        var etapa = scenario["etapa"]?.GetValue<int>();
        Assert.True(etapa is >= 1 and <= 7,
            $"{scenarioId}: 'etapa' fora do intervalo 1-7: {etapa}.");

        var passos = scenario["passos"]?.GetValue<int>();
        Assert.True(passos is > 0,
            $"{scenarioId}: 'passos' deve ser > 0: {passos}.");
    }

    [Fact]
    public void Index_SummaryByKind_MatchesActualScenarioCounts()
    {
        var scenarios = ScenarioSummaries();
        var summary = Index["summary"]!["byKind"]!.AsObject();

        foreach (var (kind, node) in summary)
        {
            var expected = node!.GetValue<int>();
            var actual = scenarios.Count(s => s["kind"]?.GetValue<string>() == kind);
            Assert.Equal(expected, actual);
        }
    }

    [Fact]
    public void Index_SummaryProcesses_MatchesActualProcessCount()
    {
        var declared = Index["summary"]!["processes"]!.GetValue<int>();
        var actual = ScenarioSummaries()
            .Select(s => s["process"]?.GetValue<string>())
            .Where(p => p != null)
            .Distinct()
            .Count();
        Assert.Equal(declared, actual);
    }

    [Fact]
    public void Index_Coverage_EachProcess_HasFullEdgeCoverage()
    {
        var coverage = Index["coverage"]!.AsArray();

        foreach (var proc in coverage)
        {
            var total = proc!["edges"]!.GetValue<int>();
            var covered = proc["edgesCovered"]!.GetValue<int>();
            var uncovered = proc["edgesUncovered"]!.AsArray();

            Assert.Equal(total, covered);
            Assert.Empty(uncovered);
        }
    }

    [Fact]
    public void GraftStep_DynamicProcesses_HaveScenariosInEtapa2()
    {
        var scenarios = ScenarioSummaries();

        Assert.True(scenarios.Any(s => s["process"]?.GetValue<string>() == "DEAT0050"),
            "DEAT0050 (graft-step ponto 1) sem cenários.");
        Assert.True(scenarios.Any(s => s["process"]?.GetValue<string>() == "CONTROPC"),
            "CONTROPC (graft-step ponto 2) sem cenários.");
        Assert.True(scenarios.Any(s => s["process"]?.GetValue<string>() == "AGPECASPC"),
            "AGPECASPC (graft-step ponto 3) sem cenários.");
    }

    [Fact]
    public void GraftStep_Etapa2_ScenarioCount_MatchesSummary()
    {
        var declared = Index["summary"]!["byEtapa"]!["etapa 2"]!.GetValue<int>();
        var actual = ScenarioSummaries().Count(s =>
        {
            var etapas = s["etapas"]?.AsArray();
            return etapas != null && etapas.Any(e => e?.GetValue<int>() == 2);
        });

        Assert.Equal(declared, actual);
    }
}
