// <auto-generated-harness>
//   Arnes gerado para VALID-GRAFTSTEP-conceito (SSTN-77).
//   Fixture: artifacts/POC_Epat/scenarios/index.json  — IMUTAVEL.
//   O agente NUNCA escreve nem edita valores esperados.
//   AC-ORACULO: suite scenario-path, 146 casos.
// </auto-generated-harness>
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Nodes;
using Xunit;

namespace SefazSp.Epat.Oracles.Tests.ScenarioPath;

/// <summary>
/// AC-ORACULO — Suite scenario-path que cobre todos os 146 casos declarados em
/// artifacts/POC_Epat/scenarios/index.json.
///
/// Regras:
///   • O agente não escreve nem altera nenhum valor esperado.
///   • Cada teste lê o que a fixture declara e verifica invariantes estruturais.
///   • Nenhum caso invoca código de produção: a fixture é o oráculo.
/// </summary>
public sealed class ScenarioPathOracleTests
{
    // ── Fixture ────────────────────────────────────────────────────────────────

    private static readonly JsonNode Index = LoadIndex();

    private static JsonNode LoadIndex()
    {
        var path = RepoRoot.ArtifactsPath("POC_Epat", "scenarios", "index.json");
        return JsonNode.Parse(File.ReadAllText(path))
               ?? throw new InvalidOperationException("index.json vazio: " + path);
    }

    private static IReadOnlyList<JsonNode> AllScenarios() =>
        Index["scenarios"]!.AsArray()
            .Select(s => s!)
            .ToList();

    // ── AC-ORACULO: totais declarados ─────────────────────────────────────────

    [Fact]
    public void Index_DeclaresCaseCount_146()
    {
        var declared = Index["summary"]!["scenarios"]!.GetValue<int>();
        Assert.Equal(146, declared);
    }

    [Fact]
    public void Index_ScenariosList_Has146Entries()
    {
        var scenarios = AllScenarios();
        Assert.Equal(146, scenarios.Count);
    }

    [Fact]
    public void Index_EdgeCoverage_Is100Percent()
    {
        var coverage = Index["summary"]!["edgeCoverage"]!.GetValue<string>();
        Assert.Equal("100%", coverage);
    }

    // ── AC-ORACULO: cada caso tem campos obrigatórios ─────────────────────────

    public static IEnumerable<object[]> AllScenarioIds()
    {
        var path = RepoRoot.ArtifactsPath("POC_Epat", "scenarios", "index.json");
        var idx = JsonNode.Parse(File.ReadAllText(path))!;
        return idx["scenarios"]!.AsArray()
            .Select(s => new object[] { s!["id"]!.GetValue<string>() });
    }

    [Theory]
    [MemberData(nameof(AllScenarioIds))]
    public void Scenario_HasRequiredFields(string scenarioId)
    {
        var scenario = AllScenarios()
            .First(s => s["id"]?.GetValue<string>() == scenarioId);

        // id
        Assert.False(string.IsNullOrWhiteSpace(scenario["id"]?.GetValue<string>()),
            $"{scenarioId}: campo 'id' ausente ou vazio.");

        // process
        Assert.False(string.IsNullOrWhiteSpace(scenario["process"]?.GetValue<string>()),
            $"{scenarioId}: campo 'process' ausente ou vazio.");

        // kind — deve ser um dos valores válidos
        var kind = scenario["kind"]?.GetValue<string>();
        Assert.True(
            kind is "ate-ao-fim" or "erro" or "percurso" or "prazo",
            $"{scenarioId}: 'kind' inválido: '{kind}'.");

        // de + ate — origem e destino
        Assert.False(string.IsNullOrWhiteSpace(scenario["de"]?.GetValue<string>()),
            $"{scenarioId}: campo 'de' ausente ou vazio.");
        Assert.False(string.IsNullOrWhiteSpace(scenario["ate"]?.GetValue<string>()),
            $"{scenarioId}: campo 'ate' ausente ou vazio.");

        // etapa — número de etapa válido (1-7)
        var etapa = scenario["etapa"]?.GetValue<int>();
        Assert.True(etapa is >= 1 and <= 7,
            $"{scenarioId}: 'etapa' fora do intervalo 1-7: {etapa}.");

        // passos — pelo menos 1
        var passos = scenario["passos"]?.GetValue<int>();
        Assert.True(passos is > 0,
            $"{scenarioId}: 'passos' deve ser > 0: {passos}.");
    }

    // ── AC-ORACULO: distribuição por kind bate com o summary ─────────────────

    [Fact]
    public void Index_SummaryByKind_MatchesActualScenarioCounts()
    {
        var scenarios = AllScenarios();
        var summary = Index["summary"]!["byKind"]!.AsObject();

        foreach (var (kind, node) in summary)
        {
            var expected = node!.GetValue<int>();
            var actual = scenarios.Count(s => s["kind"]?.GetValue<string>() == kind);
            Assert.Equal(expected, actual);
        }
    }

    // ── AC-ORACULO: processos cobertos ────────────────────────────────────────

    [Fact]
    public void Index_SummaryProcesses_MatchesActualProcessCount()
    {
        var declared = Index["summary"]!["processes"]!.GetValue<int>();
        var actual = AllScenarios()
            .Select(s => s["process"]?.GetValue<string>())
            .Where(p => p != null)
            .Distinct()
            .Count();
        Assert.Equal(declared, actual);
    }

    // ── AC-ORACULO: cobertura de arestas ─────────────────────────────────────

    [Fact]
    public void Index_Coverage_EachProcess_HasFullEdgeCoverage()
    {
        var coverage = Index["coverage"]!.AsArray();

        foreach (var proc in coverage)
        {
            var procName = proc!["process"]!.GetValue<string>();
            var total = proc["edges"]!.GetValue<int>();
            var covered = proc["edgesCovered"]!.GetValue<int>();
            var uncovered = proc["edgesUncovered"]!.AsArray();

            Assert.Equal(total, covered);
            Assert.Empty(uncovered);
        }
    }

    // ── Graft-step: os pontos dinâmicos pertencem a cenários de etapa 2 ───────

    [Fact]
    public void GraftStep_DynamicProcesses_HaveScenariosInEtapa2()
    {
        var scenarios = AllScenarios();

        // DEAT0050 é atingido via graft-step — deve ter cenários
        var deatScenarios = scenarios.Where(s => s["process"]?.GetValue<string>() == "DEAT0050").ToList();
        Assert.True(deatScenarios.Count > 0, "DEAT0050 (graft-step ponto 1) sem cenários.");

        // CONTROPC é atingido via graft-step — deve ter cenários
        var contrScenarios = scenarios.Where(s => s["process"]?.GetValue<string>() == "CONTROPC").ToList();
        Assert.True(contrScenarios.Count > 0, "CONTROPC (graft-step ponto 2) sem cenários.");

        // AGPECASPC é atingido via graft-step — deve ter cenários
        var agpeScenarios = scenarios.Where(s => s["process"]?.GetValue<string>() == "AGPECASPC").ToList();
        Assert.True(agpeScenarios.Count > 0, "AGPECASPC (graft-step ponto 3) sem cenários.");
    }

    [Fact]
    public void GraftStep_Etapa2_ScenarioCount_MatchesSummary()
    {
        var declared = Index["summary"]!["byEtapa"]!["etapa 2"]!.GetValue<int>();
        var scenarios = AllScenarios();
        var actual = scenarios.Count(s =>
        {
            var etapas = s["etapas"]?.AsArray();
            return etapas != null && etapas.Any(e => e?.GetValue<int>() == 2);
        });
        Assert.Equal(declared, actual);
    }
}
