// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SefazSp.Epat.Infrastructure.Persistence;

#nullable disable

namespace SefazSp.Epat.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EpatRuntimeDbContext))]
    [Migration("20260819193401_InitialEpat")]
    partial class InitialEpat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("SefazSp.Epat.Infrastructure.Persistence.EpatSnapshotRow", b =>
                {
                    b.Property<string>("StoreKind")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("StoreKind", "ProcessId");

                    b.ToTable("EpatSnapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
