// <auto-generated>
//   Gerado por tools/gen-scaffold.ps1 a partir do pacote POC_Epat.
//   Fonte fixada por sha256 em artifacts/POC_Epat/manifest.json.
//   NAO EDITAR: uma nova extraccao reescreve este ficheiro.
// </auto-generated>
#nullable enable

using SefazSp.Epat.Application.Abstractions;

namespace SefazSp.Epat.Application.Abstractions.Processes;

/// <summary>
/// Traducao directa do xpdExt:ProcessInterface 'AGURETPC' do XPDL.
/// Implementacoes entregues no pacote: AGPECASPC.
/// O destino da chamada dinamica e resolvido em runtime, mas o CONJUNTO de destinos
/// e derivado do XPDL e validado no arranque - gaps.dynamic-subprocess = interface-registry-validated.
/// Um destino sem implementacao quebra o teste de registo, nao a producao.
/// </summary>
public interface IAGURETPC
{
    Task<ProcessCallResult> ExecuteAsync(AiimCaseRef caseRef, CancellationToken ct);
}
