// <auto-generated>
//   Gerado por tools/gen-scaffold.ps1 a partir do pacote POC_Epat.
//   Fonte fixada por sha256 em artifacts/POC_Epat/manifest.json.
//   NAO EDITAR: uma nova extraccao reescreve este ficheiro.
// </auto-generated>
#nullable enable

namespace SefazSp.Epat.Application.Abstractions.Runtime;

/// <summary>
/// Graft step: o pai NAO inicia os filhos - espera que se anexem, possivelmente em
/// momentos diferentes, e so prossegue quando todos terminarem. Uma instancia por solidario.
/// gaps.graft-step = correlation-join: o contrato fica do lado do pai e o filho apenas sinaliza,
/// para nao obrigar processos de pacotes externos a registarem-se.
///
/// POR DEFINIR antes de implementar, registado no glossario: a chave de correlacao formal,
/// o criterio de encerramento e o timeout para um filho que nunca termina. No iProcess
/// os tres estao implicitos na identidade do caso.
/// </summary>
public interface IGraftJoin
{
    Task<GraftToken> ParkAsync(string correlationKey, CancellationToken ct);
    Task AttachAsync(string correlationKey, string childInstanceId, CancellationToken ct);
    Task SignalCompletedAsync(string correlationKey, string childInstanceId, CancellationToken ct);
}

public readonly record struct GraftToken(string CorrelationKey, int AttachedCount);
