// <auto-generated>
//   Gerado por tools/gen-scaffold.ps1 a partir do pacote POC_Epat.
//   Fonte fixada por sha256 em artifacts/POC_Epat/manifest.json.
//   NAO EDITAR: uma nova extraccao reescreve este ficheiro.
// </auto-generated>
#nullable enable

using SefazSp.Epat.Domain.Abstractions;
using SefazSp.Epat.Domain.ValueObjects;

namespace SefazSp.Epat.Domain.Cases;

/// <summary>
/// O caso do AIIM: o estado de negocio que o processo carrega.
/// 209 campos de negocio, dos quais 147 sao tocados pelo cenario da POC.
/// Os outros 62 ficam, marcados com [OutOfPocScope]: cortar dados do caso e
/// diferente de cortar trabalho, e o legado carrega-os na mesma.
/// Os 19 do envelope tecnico ficam de fora por decisao registada no glossario -
/// vivem em SefazSp.Epat.Application.Execution.
/// </summary>
public sealed class AiimCase
{
    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public string AFR { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    public IReadOnlyList<string> AGUARDAR { get; set; } = [];

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public bool ANULACAODTJ { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string APLICACAO { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    public IReadOnlyList<string> ARRAYINT { get; set; } = [];

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 255
    public string AUX { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 150
    public FieldValue<string> BCCRELATORIO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long CASENUMBER { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public long CASERETORNO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 150
    public FieldValue<string> CCRELATORIO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int CD_DRT { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long CDIMPOSTO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public string CHEFEUJ { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public bool CIENCIA { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int CNTINSTANCIASUF { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 3
    public FieldValue<string> CNTPECA1 { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 3
    public FieldValue<string> CNTPECA2 { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 3
    public FieldValue<string> CNTPECA3 { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 3
    public FieldValue<string> CNTPECA4 { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long CODIGOMUNICIPIO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int CODMUNAIIM { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int CODMUNICIPIO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 12
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string CODNOTIFICAO { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 4
    public string? CODTEXTO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public string CODUADRT { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public FieldValue<string> CODUADTJ { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public string COORDENADOR { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public bool CORRECAO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 20
    public string? CPFCNPJ { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int CRCASA { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int CRCONTRIBUINTE { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 10
    public string CTL_RETIRAT { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public bool CTRLIATV { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public DateOnly DATACIENCIA { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public FieldValue<DateOnly> DATACONTROLE { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public DateOnly DATADEFESA { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public DateOnly? DATADIAUTIL { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public DateOnly DATAENCPREPNOT { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public DateTime DATAFINALMF { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public DateOnly DATAINICIOPERIO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string DATETIMEPC { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int DAYSOVER { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 8
    public IReadOnlyList<string> DEAT0050 { get; set; } = [];

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public bool DEFESAADMITIDA { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 250
    public string DESCREGRA { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public bool DILIGENCIA { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 20
    public string DILIGENCIADESTI { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 10
    public string DOCCONTROL { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    public string DOCSPERMITIDOS { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    public string DOCSREQUERIDOS { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 255
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string DSCRECURSO { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    public string? DSTIPOINTIMACAO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public FieldValue<DateOnly> DTCIENCIA { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public DateOnly DTFIMCQ { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public DateOnly DTGERNOTIFICACA { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public DateOnly DTPUBLICACAODE { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 250
    public string EMAILRELATOR { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 255
    public string EMAILVISTAS { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public bool EXCLUSAOSOLIDAR { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public bool EXISTENOTIFICAC { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    public string FIELDSNAMES { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    public string FIELDSTYPES { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    public string FIELDSVALUES { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long FIMSTRING { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public bool FLAGCONTRARAZAO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public bool FLAGCRZ { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public bool FLAGRETIRATE { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public long FLDISPCIENCIA { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public long FLEXISTEPECA { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public bool FLGALC { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public bool FLGTERMODEC { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 10
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string FORMA { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 20
    public string FORMACORRECAO { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    public string FORNECEDOR { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public bool HADEFESA { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public bool HAMANIFESTACAO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public DateTime HORAFINAL { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public TimeOnly HRFIMCQ { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long IDAIIM { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long IDAIIMANTERIOR { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long IDAIIMORIGINAL { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public int IDARQDEFESA { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int IDDECISAOAIIM { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int IDDECISAODEBITO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string IDFORNECEDOR { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 250
    public string IDINTIMADO { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int IDMOTIVOINTIMAC { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long? IDMUNICIPIO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    public string IDPECAS { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    public string IDPECASCNT { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    public string IDPECASSF { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public FieldValue<int> IDPROCESSO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 250
    public string IDSINTIMADOS { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    public string IDTIPOIMPUGNACA { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long? IDTIPOINTIMACAO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public int IDX_AGUARDAR { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long INDICESUBDIN { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public bool INDNAORECORRER { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int INDRESPPRM { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string INSPETORNF { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int INSTANCIA { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public int INSTANCIAPC { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int INTIMACAOCARTA { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int INTIMACAOCOUNT { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int INTIMACAODE { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public long INTIMADOSQTDE { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 255
    public string LINKIPE { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public string LOGINAFR { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public string LOGINCOORDENADO { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string LOGINENTREGAMF { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 8
    public string NOMEETAPA { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    public string NOMEPROCESSO { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public string NOTIFICACAO { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public string NOTIFICADOS { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public bool NOVOMODELO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long NR_AIIM { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long NR_RAT { get; set; }

    /// <summary>
    /// Numero do RAT original
    /// Numero do RAT que deu origem ao AIIM, distinto de NR_RAT. Nome DEDUZIDO do identificador em 2026-08-06 por ruling LABEL-CONFLICT, porque o rotulo do formulario apontava para outro campo. PENDENTE DE RATIFICACAO pela SEFAZ.
    /// </summary>
    public long NR_RATORIG { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long NRAIIM { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    public IReadOnlyList<string> NRSUBPRO { get; set; } = [];

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 5
    public FieldValue<string> ORIGEM { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public bool OUTRADRT { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long PERIODOEMDIAS { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long POSICAOFIM { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long POSICAOINICIO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public DateOnly PRAZOCIENCIA { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public DateOnly PRAZODEFESA { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public TimeOnly PRAZODEFESAT { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public DateTime PRAZOFINAL { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public DateOnly PRAZORECEBIMENT { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public DateOnly PRAZORELATO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public DateOnly PRAZORETIRADAVI { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public DateOnly PRAZOVISTA { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 35
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string PROCESS_IDPC { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 8
    public string PROCRETORNO { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public bool PUBLICACAODE { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public bool PUBLICADODEC { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public DateTime PZCIENCIADT { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long QTDINTIMADOS { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int? QTPECASCNT { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public int QTPECASCNTPC { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int? QTPECASSEFAZ { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int RECAPIT { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public bool RECURSOOFICIO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int REGRAINSDOC { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 10
    public string RESPOSTACQ { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 2
    public string? SFDIASREPRESENT { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 3
    public FieldValue<string> SFPECA1 { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 3
    public FieldValue<string> SFPECA2 { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 3
    public FieldValue<string> SFPECA3 { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 3
    public FieldValue<string> SFPECA4 { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 10
    public string SITUACAOCARREGA { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public int STARTDEAT0010 { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public int STATUSOFICIO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int STATUSPETICAO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int STATUSPRJ { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int STATUSRECURSOS { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 10
    public string STATUSSUBPROC { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public FieldValue<int> STSADMTITCNT { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public FieldValue<int> STSADMTITDRF { get; set; }

    /// <summary>
    /// Status da Peticao
    /// Situacao da peticao, distinta do campo STATUSPETICAO. Nome DEDUZIDO do identificador em 2026-08-06 por ruling LABEL-CONFLICT, porque o rotulo do formulario colidia com outro campo. PENDENTE DE RATIFICACAO pela SEFAZ.
    /// </summary>
    public int STSPETICAO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int STSPRMSF { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int STSRESPCNT { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int STSRESPSF { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 24
    public string SW_CASEDESC { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long SW_CASENUMPC { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long SW_CASENUMPOC { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 20
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string SW_CASEREF { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public int SW_CP_INCPERIOD { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public int SW_CP_INCREMENT { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public int SW_CP_NUMINC { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 1
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string SW_CP_PERIODTYP { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public int SW_CP_VALUE { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public int SW_GEN_IDX { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 24
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string SW_HOSTNAMEPC { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 24
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string SW_HOSTNAMEPOC { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public int SW_IP_INCPERIOD { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public int SW_IP_INCREMENT { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public int SW_IP_NUMINC { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 1
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string SW_IP_PERIODTYP { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public int SW_IP_VALUE { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public long SW_MAINCASEPC { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long SW_MAINCASEPOC { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 24
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string SW_MAINHOST { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 8
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string SW_MAINPROCPC { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 24
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string SW_NODENAME { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public long SW_PARENTCASEPC { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 24
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string SW_PARENTHOST { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 8
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string SW_PARENTPOC { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 64
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string SW_PARENTREF { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 24
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string SW_PRODESC { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 8
    public string SW_PRONAME { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 24
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string SW_QPARAM1 { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 24
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string SW_QPARAM2 { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 12
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string SW_QPARAM3 { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 12
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string SW_QPARAM4 { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public long SW_QRETRYCOUNT { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 24
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string SW_STEPDESC { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 8
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string SW_STEPNAME { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 2
    public string? TEMPORESPOSTA { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 6
    public string TIPODILIGENCIA { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 10
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string TIPODOCUMENTO { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    public FieldValue<string> TIPOVISTAS { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    // XPDL: comprimento maximo 50
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public string TPNOTIFICACAO { get; set; } = default!;

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int TROCATPNOTIFICA { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    [OutOfPocScope("declarado no XPDL mas nunca lido, escrito, testado nem mapeado")]
    public int ULTIMAVERSAO { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public bool VICIOREPRESENTA { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public int VOLTARSEGINSTAN { get; set; }

    /// <summary>
    /// Identificador do TIBCO. Termo de negocio ainda nao respondido no glossario.
    /// </summary>
    public decimal VRAIIM { get; set; }

}
